### ISSUE TITLE
Create checkbox and radio inputs

### ISSUE THREAD

**Issue by JoseRenan** [primer/react#1050]
## Description

Hi! I'm using the primer components but I couldn't find any example of using the checkbox and radio inputs. I saw that it exists on primer/css but not on primer/react. I don't know if it's supposed to be this way since I didn't found anything related to it the roadmap.

### Design

Link to mockups/prototypes: https://primer.style/css/components/forms#checkboxes-and-radios

### Usage

```jsx
<Checkbox checked onChange={() => console.log('checked')} />
```

**Comment by SaadBazaz** [comment]
Any update on this? Need it.

**Comment by lesliecdubs** [comment]
Hi @SaadBazaz! Checkboxes and radio inputs both exist in Primer React now. Here are some links to the docs:
- [Checkbox](https://primer.style/react/Checkbox)
- [Radio](https://primer.style/react/Radio)

**Comment by SaadBazaz** [comment]
Awesome. Thanks for the update, @lesliecdubs .
