### ISSUE TITLE
Browser reset styles not applied to components

### ISSUE THREAD

**Issue by pmarsceill** [primer/react#1139]
**Describe the bug**
When using primer.css, different UI elements are rendered consistently across browsers because we use `normalize` to reset user agent styles. Primer components does not use any browser reset styles so some components will get user agent styes applied.

**Note:** As this is a public repo, please be careful not to include details or screenshots from unreleased GitHub products or features. In most cases, a good bug report should be able to describe the new component without including business logic or feature details, but if you must discuss context relating to an unreleased feature, please open an issue in the private [Design Systems repo](https://github.com/github/design-systems/issues/new/choose) and link to it here.

**To Reproduce**
1. Add a button component
2. See the User Agent styles applied

**Expected behavior**
Consistency between Primer.css and PRC in how styles are displayed across browsers

**Screenshots**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/896475/112866156-7736d900-9087-11eb-94ca-3e19059967d1.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser ALL
 - Version 25

**Comment by T-Hugs** [comment]
@pmarsceill I believe the `<BaseStyles>` component is meant to address this. The `<BaseStyles>` component should be an ancestor of all other Primer Components.

**Comment by pmarsceill** [comment]
cc @emplums @colebemis we chatted about this in Slack ☝️
