### ISSUE TITLE
TextInput bg colour not being applied

### ISSUE THREAD

**Issue by miguel-amaton-sp** [primer/react#1142]
**Describe the bug**
The background color (defined in theme reference as `colors.input.bg`) is being ignored by the TextInput.tsx component. Apparently, this can be fixed by including the property in the list of default styles like so:

![image](https://user-images.githubusercontent.com/79318680/112908149-3b623a80-90ac-11eb-9848-22066e99ae62.png)

After running the test, a snapshot refresh was required, which showed the new property being applied correctly.

**Note:** As this is a public repo, please be careful not to include details or screenshots from unreleased GitHub products or features. In most cases, a good bug report should be able to describe the new component without including business logic or feature details, but if you must discuss context relating to an unreleased feature, please open an issue in the private [Design Systems repo](https://github.com/github/design-systems/issues/new/choose) and link to it here.

**To Reproduce**
1. Include the `<TextInput />` component somewhere
2. Check the background colour of the `span` wrapper
3. The bg colour is not set

**Expected behavior**
Since there's a property in theme reference that exposes the bg property for this component, it should be used.

**Screenshots**
I find it difficult to showcase this issue using screenshots :P 

**Desktop (please complete the following information):**
 - OS: `Windows 10`
 - Browser: `Google Chrome`
 - Version: `25`

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
This is not really a very big issue, and it's a one liner fix. But apparently I don't have enough disk space to make a PR myself! I'm sorry x.x

Thanks!

**Comment by pksjce** [comment]
Should be fixed by https://github.com/primer/react/pull/1661
