### ISSUE TITLE
Can't select text inside a ConfirmationDialog in docs

### ISSUE THREAD

**Issue by T-Hugs** [primer/react#1178]
**Describe the bug**
For some reason, you can't select text within a dialog that is rendered on the docs site. See [this comment](https://github.com/primer/components/pull/1165/files#r616171963) for a video.

**To Reproduce**
1. Go to https://primer.style/components/Dialog2
2. Click Open to open the dialog.
3. Try to select text (e.g. "Some content") within the dialog

**Expected behavior**
Text can be selected, such as in the storybook

**Screenshots**
https://user-images.githubusercontent.com/4608155/115301851-9cfb4f00-a116-11eb-8720-8894f600efda.mp4

**Comment by pavelkeyzik** [comment]
Looks like the issue can be closed 🎉

**Comment by rezrah** [comment]
Bug still exists in `ConfirmationDialog`. Reopening.
