### ISSUE TITLE
Make @primer/octicons-react a peer dependency

### ISSUE THREAD

**Issue by daaku** [primer/react#1204]
My package uses @primer/octicons-react v13 but this package pulls in v11 resulting in unnecessary increase in my bundle size. Maybe a peer dependency is the right solution here?

**Comment by rezrah** [comment]
To be completed at the same time as https://github.com/github/primer/issues/241

**Comment by colebemis** [comment]
Upgrading to `@primer/octicons-react` `v16.x` should solve this issue ✅
