### ISSUE TITLE
Docs: Conflict of sx & system props usage recommendation

### ISSUE THREAD

**Issue by stu039** [primer/react#1363]
Quite a small one: 

I can see on the documentation [here](https://primer.style/components/overriding-styles#when-to-use-the-sx-prop) regarding usage of the sx prop, that system props are recommended to be used over the sx prop where possible. However on the system prop documentation [here](https://primer.style/components/system-props) it is claimed that system props are deprecated and one should use the sx prop except in the Box component.

Just a little confusing to follow as there is conflicting info here.

**Comment by colebemis** [comment]
Good catch. Thank you, @stu039! That second bullet point on the `sx` prop page should be deleted. Would you like to open a PR to make that change?

**Comment by colebemis** [comment]
Closed by https://github.com/primer/react/commit/83258e99e5954f2f6a74892b0e742f0d44f79aea
