### ISSUE TITLE
Forms components

### ISSUE THREAD

**Issue by alegauss** [primer/react#1374]
### Discussed in https://github.com/primer/react/discussions/1373

<div type='discussions-op-text'>

<sup>Originally posted by **alegauss** August 10, 2021</sup>
There are no Form components in Primer React, just TextInput. What is the best practice for using Forms components? Like Combobox, Text Area, Radio and etc...

Thanks,
Alexandre</div>

**Comment by rezrah** [comment]
Hi @alegauss, I’m closing this as there’s already an open Discussion on the topic. We can provide updates on our plans to release form components there.
