### ISSUE TITLE
Inaccurate type for TextInput's onChange property

### ISSUE THREAD

**Issue by jclem** [primer/react#1377]
**Describe the bug**

I expected the `onChange` property of `TextInput` to have the same type as `JSX.InstrinsicElements['input']`, but it appears that `currentTarget` on the event is more than `HTMLInputElement`:

<img width="709" alt="CleanShot 2021-08-11 at 15 04 56@2x" src="https://user-images.githubusercontent.com/412282/129109702-77999eac-2698-4671-a9cc-e48c2ddf2a9d.png">

**To Reproduce**
1. Create a component with `TextInput` whose `value` is a piece of string state
2. Try to set the string state with `onChange={e => setState(e.currentTarget.value)}`

**Expected behavior**

No type error occurs.

**Screenshots**

See above with the current typing for `onChange`.

**Comment by colebemis** [comment]
Added this to our planning project board. Thank you!
