### ISSUE TITLE
Breadcrumbs.Item with a long name will be out of the screen

### ISSUE THREAD

**Issue by pavelkeyzik** [primer/react#1379]
## Describe the bug

As you may see in screenshots section that if we're using a long name for Breadcrumb.Item then it's out of the screen. The case of using long names in breadcrumbs is article name with a long title.

## To Reproduce
1. Just add a long text in Breadcrumb.Item
2. And change size of the window to small one

## Expected behavior
Text is not running out of the screen

## Screenshots

<img width="585" alt="image" src="https://user-images.githubusercontent.com/17102399/129373052-ad744e49-ec3e-44f9-9e80-8dba4b515504.png">

## Desktop
 - OS: Mac OS
 - Browser Safari
 - Version 14.0.3

## Additional context
If you have any ideas how we can fix it then I'll be happy to do PR.

I've tried to add `white-space: break-spaces` rule. It works except the thing that '/' element is always at the end of line. 

Another idea is to change the way how '/' is added between elements. Instead of using `:after` we can add this as component while mapping elements [here](https://github.com/primer/react/blob/main/src/Breadcrumb.tsx#L46) but I haven't tried this yet.

**Comment by colebemis** [comment]
Added to our backlog. Thank you!

**Comment by colebemis** [comment]
cc @vdepizzol for design input on how we should handle long breadcrumbs

**Comment by ashygee** [comment]
Sorry for the late reply @colebemis! I am going to add this to our Breadcrumbs tracking issue.
