### ISSUE TITLE
Buttons have incorrect sizes

### ISSUE THREAD

**Issue by vdepizzol** [primer/react#1389]
**Describe the bug**
While documenting https://github.com/github/primer/issues/263, I realized that Primer React buttons have incorrect sizes when compared to Figma references and Primer CSS implementation, usually being 2px taller than expected.

This issue is probably due to borders being ignored in the calculation after specifying line-height + padding.

The total height of regular buttons should be `32px` on the medium size, `28px` on the small size, and `40px` on the large size.

### Related

https://github.com/github/primer/issues/41 (on "Using borders")

**Comment by mperrotti** [comment]
I actually like the 2px higher buttons better, and I'd advocate for updating Figma instead. This is just my personal preference though, and I defer to you and the rest of the team.

**Comment by vdepizzol** [comment]
@mperrotti we're trying to stick with a 4 or 8px grid for component sizes, to make sure that components can work well together. I guess that's another thing we should document in our interface guidelines 😄.

**Comment by pksjce** [comment]
Also the icon sizes don't correlate to the expected button sizes. So I'm assuming we don't change the size of icons for buttons which have them.

https://github.com/primer/octicons/blob/main/docs/content/packages/react.mdx#sizes

**Comment by pksjce** [comment]
This is all fixed. Is the fix ideal? Maybe not. But the issue doesn't exist any more with the new Button component
