### ISSUE TITLE
uniqueId() causes hydration warnings with server-side rendering

### ISSUE THREAD

**Issue by jclem** [primer/react#1392]
**Describe the bug**

When using server-side rendering, the [`uniqueId()` function](https://github.com/primer/react/blob/8ee008dc6e0a342c6ca5dd8f07bbbb5dd113a11b/src/utils/uniqueId.ts) causes hydration warnings because the `idSeed` counter is globally shared for all renders for all users while it's reset to 10,000 on the client.

Additionally, this has the unintended side effect of leaking information about how many times a given page is visited (per rendering process, at least).

**To Reproduce**

Render any Primer component that uses `uniqueId()` using server-side rendering.

**Expected behavior**

The same ID is used on the server as on the client.

**Screenshots**

<img width="982" alt="CleanShot 2021-08-24 at 13 10 38@2x" src="https://user-images.githubusercontent.com/412282/130660093-bb405e3c-c579-4f22-b2ea-f530d815fd42.png">

**Comment by colebemis** [comment]
Added to our [project board](https://github.com/github/primer/projects/4?fullscreen=true). Thank you!

**Comment by jfuchs** [comment]
Looks like this isn't a new problem to React (https://github.com/facebook/react/issues/4000, https://github.com/facebook/react/issues/5867). I've looked around at a few solutions, and I like _most_ of what React-aria does:

- Use context to keep a counter in state, so you don't run into issues like a counter shared across renders
- Allow nesting the provider for that context, which updates a separate counter of how deeply nested those providers are. That way you can wrap an additional provider around some asynchronously loaded part of the tree without worrying about server & client pulling their counters in a different order.
- exposes everything in a handy hook

I do think there's a bug in their solution, for which I've opened [an issue](https://github.com/adobe/react-spectrum/issues/2277).

One option for us, if that issue gets fixed, is to pull in `@react-aria/ssr` as a dependency. Or we could roll something similar ourselves.

**Comment by jfuchs** [comment]
One other catch is that you have to be careful about where you include the provider in the tree — you have to place them to avoid ever having two components in the calling `useSSRSafeId` with the same ssr context in different sequences. E.g., this:

```
function Component() {
  const a = useFetch(...)
  const b = useFetch(...)

  return <>
    {a && <SubComponent data={a} />}
    {b && <SubComponent data={b} />}
  </>
}

function SubComponent() {
  const id = useSSRSafeId()
  return <div id={id} />
}
``` 

will be unsafe, but you can wrap each conditional call to `SubComponent` with a non-conditional call to `SSRProvider` to make it safe: 

```
function Component() {
  const a = useFetch(...)
  const b = useFetch(...)

  return <>
    <SSRProvider>
      {a && <SubComponent data={a} />}
    </SSRProvider>
    <SSRProvider>
      {b && <SubComponent data={b} />}
    </SSRProvider>
  </>
}
```

**Comment by jclem** [comment]
This could also be fixed by allowing me to set IDs manually in many Primer components. For example, ActionList _only_ allows me to use auto-generated IDs unless I take the much larger step of using a custom renderer everywhere for it.
