### ISSUE TITLE
Avatar: document `src` and `alt` props

### ISSUE THREAD

**Issue by colebemis** [primer/react#1405]
## Problem 

The [props table](https://primer.style/react/Avatar#props) for the Avatar component does not include the `src` and `alt` props.

[![CleanShot 2021-09-05 at 17 51 08](https://user-images.githubusercontent.com/4608155/132146579-527be16b-f870-47f6-822f-2ffe1eb6f5a9.png)](https://primer.style/react/Avatar)

## Context

Prop documentation for Avatar is generated by [react-docgen-typescript](https://www.npmjs.com/package/react-docgen-typescript). `src` and `alt` are missing for the docs because they're not included in the props type definition for Avatar: https://github.com/primer/react/blob/main/src/Avatar.tsx#L6-L12

## Do this

- [ ] Add `src` and `alt` to the props type definition for Avatar

## Open questions

- Should `src` and `alt` be required?

---
cc @joelhawksley @ashygee

**Comment by joelhawksley** [comment]
@colebemis I think they should both be required, yes. Perhaps @alliethu can offer her opinion re: accessibility?

**Comment by alliethu** [comment]
@colebemis @joelhawksley 

As long as the avatar is always text-adjacent to the username, I would suggest dynamically generating an empty or null `alt` attribute value (i.e. `alt=""`), informing the Screen Reader to ignore the image since its description would be redundant.

For more info, [Webaim's article on alt text](https://webaim.org/techniques/alttext/)

**Comment by joelhawksley** [comment]
@alliethu that's really helpful context. Avatars are sometimes next to usernames (such as in this comment thread) but sometimes are not! Sounds like we might need to document this difference.

**Comment by alliethu** [comment]
@joelhawksley @siddharthkp @colebemis   
I should have clarified earlier.. It looks like the current implementation of avatars are rendered as`<img>s`, not `<svg>`s. As long that is still the case, when the avatar is _not_ text-adjacent to the username, I would suggest dynamically generating an alt attribute with the username. i.e. `alt="{username}"`.
