### ISSUE TITLE
Allow ActionList.Item to be an anchor

### ISSUE THREAD

**Issue by jfuchs** [primer/react#1413]
## Description

Allow ActionList.Item to be a link, so that an ActionList could be used as a navigation menu

### Component API

Possibilities:

```
<Item as={Link} href={...} />
```

```
<LinkItem href={...} />
```

**Comment by mattcosta7** [comment]
As far as the component API - I think the case of

`<Item as={Link} href="" />` might be better generalized as `<Item as={Link} {...LinkProps} />` which would encapsulate the react-router scenario of `<Item as={ReactRouterLink} {...ReactRouterLinkProps} />`

**Comment by jclem** [comment]
To generalize upon what @mattcosta7 was saying, `<Item as={T} {...P} />` where `T` is `string | React.ComponentType` and `P` is `React.ComponentProps<T> & ItemProps`.

**Comment by smockle** [comment]
From @mattcosta7 in https://github.com/primer/react/issues/1413#issuecomment-915409164:
> As far as the component API - I think the case of
> 
> `<Item as={Link} href="" />` might be better generalized as `<Item as={Link} {...LinkProps} />` which would encapsulate the react-router scenario of `<Item as={ReactRouterLink} {...ReactRouterLinkProps} />` (which would use to={LinkDescriptor} instead of href directly)

From @jclem in https://github.com/primer/react/issues/1413#issuecomment-915413364:
> To generalize upon what @mattcosta7 was saying, `<Item as={T} {...P} />` where `T` is `string | React.ComponentType` and `P` is `React.ComponentProps<T> & ItemProps`.

We’ve [previously explored type-safe `as`](https://github.com/github/primer/discussions/130#discussioncomment-696081) using [`@radix-ui/react-polymorphic`](https://www.radix-ui.com/docs/primitives/utilities/polymorphic). Here’s a quick demo of how this could work: https://codesandbox.io/s/as-prop-demo-forked-ox2b1?file=/src/App.tsx

**Comment by jfuchs** [comment]
Given these usage options...

```
        <ActionList
          items={[
            {text: 'A) Vanilla link', as: 'a', href: '/about'},
            {text: 'B) as React Router link', href: '/about', as: ReactRouterLikeLink},
            {text: 'C) React Router link via renderItem', href: '/about', renderItem: props => (
              <ReactRouterLikeLink component={ActionList.Item} {...props} />
            )},
            {text: 'D) NextJS style via renderItem', renderItem: props => (
              <NextJSLikeLink>
                <ActionList.Item as="a" {...props} />
              </NextJSLikeLink>
            )}
          ]}
        />
```

Is there anything else we'd need? Is there a reason to support B if C is an option?

**Comment by jclem** [comment]
From the perspective of Next.js, D looks great. I'm less familiar with react-router, but @mattcosta7 can probably weight in there.

**Comment by mattcosta7** [comment]
React Router is _supposedly_ dropping support for as/component type stuff, I believe in v6 in a push to make sure people actually render 'a' tags for links, so i'm not sure if that will be supported in the future, but `<ActionList.Item as={ReactRouteLikeLink}>` would be

**Comment by jfuchs** [comment]
Okay, I think we can drop B... and maybe we could drop A too? It's syntactic sugar for 

```
            {text: 'A. Vanilla link', as: 'a', renderItem: ({...props}) => (
              <ActionList.Item as="a" href="/about" {...props} />
            )},
```

And maybe that wouldn't be used very often if everyone needs to use RR links or Next links anyway?
