### ISSUE TITLE
System Properties being recommended, but also deprecated

### ISSUE THREAD

**Issue by AwesomestCode** [primer/react#1420]
On the docs for [system props](https://primer.style/react/system-props) it says that users should "[p]lease use the ``sx`` prop instead." However, if I go to the documentation for the (``sx`` prop)[https://primer.style/react/overriding-styles], I am told to "[u]se system props instead of the sx prop whenever possible."

This is very confusing. Each page is telling me to use the other. Which one should I *actually* use?

**Comment by colebemis** [comment]
👋  Hi, @AwesomestCode! Sorry for the confusion. We're moving away from system props on most components (except utility components like Box and Text). I've removed the line about system props in the `sx` prop documentation. Hope that provides some clarity :)
