### ISSUE TITLE
Component List

### ISSUE THREAD

**Issue by AwesomestCode** [primer/react#1421]
## Description

On many pages, GitHub has "lists" (e.g., pull requests, issues). After looking around for a while, I couldn't find any React component in Primer that does this.

### Design

I've attached a screenshot in the "Usage" section.

### Component API

Probably just several divs as children?

### Usage

Use case is a list. Basically what GitHub currently uses for displaying open PRs/issues.

Example:

<img width="1273" alt="Screenshot 2021-09-12 at 17 17 26" src="https://user-images.githubusercontent.com/53128754/133003095-734aea29-888d-4dbf-9605-28cd78df5422.png">

## Implementation

N/A, not a GitHub employee

## Timeline

I'd prefer for this to be implemented quickly, but I understand that external feature requests probably don't have that high of a priority.

## Further Notes

Please reply if you've read over this (even just a "read") would be greatly appreciated! Also, I know something similar can be achieved by putting boxes in grids, but that seems suboptimal.

**Comment by malikkotob** [comment]
Hi @AwesomestCode! Not a Github employee, but have you seen the [ActionList](https://primer.style/react/ActionList) component? Its intended use case seems very much in line with what you're describing. Not sure what your use case is exactly, but where it would potentially fall short is if you had a listing of content that didn't necessarily need to be a set of actionable/selectable items.

Note that it's marked as being in alpha, and is additionally not yet being advertised from the components nav (though I'm not sure if that's intentional or not). 
![image](https://user-images.githubusercontent.com/7820280/135568401-49f4e132-9072-4786-9a0d-6b913fca9431.png)

It would be super helpful for someone from Github to chime in. Wouldn't want to lead you down the wrong path in case this is a component that is primarily intended for internal use :)

**Comment by AwesomestCode** [comment]
I’ve taken a quick look. It seems to look drastically different from what I was asking for—see the screenshot of the PR list menu I was referring to above. Thanks for the help though! On Fri, Oct 1, 2021 at 01:11, malikkotob ***@***.***> wrote:  
Hi @AwesomestCode! Not a Github employee, but have you seen the ActionList component? Its intended use case seems very much in line with what you're describing. Not sure what your use case is exactly, but where it would potentially fall short is if you had a listing of content that didn't necessarily need to be a set of actionable/selectable items.
Note that it's marked as being in alpha, and is additionally not yet being advertised from the components nav (though I'm not sure if that's intentional or not).

It would be super helpful for someone from Github to chime in. Wouldn't want to lead you down the wrong path in case this is a component that is primarily intended for internal use :)

**Comment by malikkotob** [comment]
Ah maybe the screenshot I was showing was confusing the matter. That was just a screenshot showing that `ActionList` isn't one of the listed components in the primer documentation - it wasn't a sample of an actual `ActionList`. One of the samples under the group section looks relatively similar to me, but maybe it's not exactly what you're looking for?
![image](https://user-images.githubusercontent.com/7820280/135633440-b5633ec1-098f-4b7e-a867-492b112ea1fe.png)

It looks like you're able to supply a leading visual (e.g. icon), your primary text, description text, etc. Looks like there's even a custom `renderItem` prop that lets you provide a callback to pass each list `ActionList.Item` through in case you need more control.

I dropped this markup into a boiler plate `create-react-app` project (with primer of course) to see how close I could get to the open PRs look-and-feel. Still more to do to achieve 1:1 parity, but seems like this could fit the bill?

![image](https://user-images.githubusercontent.com/7820280/135637529-1075599f-c00f-44d3-84e5-93e341afbfad.png)

**Comment by AwesomestCode** [comment]
Yeah—I skimmed through the documentation quickly and didn't notice the "group" section. After seeing your screenshot, it looks like it could work, even though it looks a bit different than desired. I've also tried using boxes which also sort of work. I'm on my phone right now, but I'll attach a screenshot of that tomorrow

**Comment by malikkotob** [comment]
Looking forward to seeing the screenshot! If you have the bandwidth, might be worth exploring how far you can get with the two options (I haven't checked, but I even wonder if `ActionList` is using `Box` under-the-hood to handle its flexing).

Also, if I'm reading docs/intended use cases properly, one upside to `ActionList` over `Box` as the baseline to your list is that it's likely more straightforward to plug right into `ActionList` to generate each list item as a clean `<li><a></a></li>` set of markup (via the custom item renderer). What isn't clear is if it would be straightforward to have the group overall (i.e. immediate parent of each `<li>`) output as `<ul>`/`<ol>` if your use case requires it. Just some things to consider on the accessibility front. Not to say that you couldn't just wrap each `Box` with an `<a>` on your own, but I would imagine the primer team would bake some accessibility niceties that go hand-in-hand with lists overtime, while you might find yourself needing to handle that on your own if you go the `Box` route.

I could be off, but it's worth exploring. @smockle and @khiga8 may have thoughts on this as well!

**Comment by rezrah** [comment]
Hi @AwesomestCode, I'm closing this issue as it appears to no longer be relevant given your [most recent comment](https://github.com/primer/react/issues/1421#issuecomment-943299076). If you would still like support on this however, please feel free to reopen it and provide an update on your situation.

**Comment by AwesomestCode** [comment]
I’d still like native support for it—the current method feels kinda hacky even if it works.
