### ISSUE TITLE
Visual bug on mobile table of contents

### ISSUE THREAD

**Issue by colebemis** [primer/react#1430]
## Problem

The mobile table of contents on https://primer.style/react documentation pages has an unexpected black line.

### Current

![CleanShot 2021-09-16 at 14 58 19](https://user-images.githubusercontent.com/4608155/133691266-ee7ae7ed-655f-4f14-8f88-e0b9cd29fb73.png)

https://primer.style/react/Box

### Expected

![CleanShot 2021-09-16 at 15 00 32](https://user-images.githubusercontent.com/4608155/133691433-cda47973-c6b4-4f56-9616-09fbc93ce5d3.png)

https://primer.style/view-components/components/box

**Comment by SferaDev** [comment]
[(doctocat) theme/src/components/layout.js](https://github.com/primer/doctocat/pull/255/files#diff-3b0e5bbe71b45a4c9eb24943876bed9538777aab09e2dfb633505da858b62828)

```diff
- borderColor: 'border.gray',
+ borderColor: 'gray.2',
```
