### ISSUE TITLE
Preview components in different themes

### ISSUE THREAD

**Issue by colebemis** [primer/react#1433]
## Background

Primer React components can be rendered in many [different themes](https://primer.style/primitives/colors#themes). See the [Theming](https://primer.style/react/theming) for more details.

| Light | Dark |
| --- | --- |
| ![CleanShot 2021-09-16 at 16 27 32](https://user-images.githubusercontent.com/4608155/133701180-38b3c117-a887-4c7f-91db-b9a6f7127502.png) | ![CleanShot 2021-09-16 at 16 28 17](https://user-images.githubusercontent.com/4608155/133701293-11f17083-533f-4d3b-b0e6-e967f8a2aaed.png) |

In fact, one of the criteria for a component to be [alpha](https://primer.style/contribute/component-lifecycle#alpha) is that "the component is compatible with color modes and can adapt to different themes."

## Problem

We don't have an easy way to preview components in different themes in documentation examples and Storybook.

## Tasks

- [ ] Implement a way to preview components in different themes in documentation examples
- [x] Implement a way to preview components in different themes in Storybook https://github.com/primer/react/pull/1436

**Comment by jfuchs** [comment]
Isn't this done for docs with `cmd` + `ctrl` + `t`? Do we want something more obvious like a visible switch in every example?

**Comment by SferaDev** [comment]
> Isn't this done for docs with `cmd` + `ctrl` + `t`? Do we want something more obvious like a visible switch in every example?

I believe something like what ViewComponents documentation has

![image](https://user-images.githubusercontent.com/2181866/134223240-d974d8d4-ab03-4ad0-8e71-9eac4de7e97d.png)

**Comment by pksjce** [comment]
> Implement a way to preview components in different themes in documentation examples

@colebemis - You mentioned other colormodes? I couldn't find a reference to them. Could you link them for me?

**Comment by colebemis** [comment]
@pksjce All of the color schemes are listed here: https://github.com/primer/react/blob/main/src/theme-preval.js#L113-L132

You can access the list of color schemes in code with the `useTheme` hook:

```js
import {useTheme} from '@primer/components'

function Component() {
  const {theme} = useTheme()
  // Object.keys(theme.colorSchemes) -> ['light', 'dark', 'dark_dimmed', 'dark_high_contrast']
}
```
