### ISSUE TITLE
Link property "muted" causes hydration warnings

### ISSUE THREAD

**Issue by jclem** [primer/react#1455]
**Describe the bug**

When rendering a Link like `<Link href="/" muted>Hello</Link>`, hydration warnings are emitted:

```text
Warning: Prop `muted` did not match. Server: "undefined" Client: "true"
```

The DOM output by this is `<a href="/" muted>Hello</a>` (note the unexpected "muted" property).

I'm not sure why this is happening, but I'm wondering if it's styled-components adding "muted" because that is a valid property on _some_ elements (e.g. `HTMLVideoElement`).

**To Reproduce**

See [this CodeSandbox](https://codesandbox.io/s/headless-rain-15jtz?file=/pages/index.js) and look at the browser console.

**Expected behavior**

No `muted` attribute is added to the `HTMLAnchorElement` and no hydration warning is logged.

**Comment by SferaDev** [comment]
I believe you need to add the styled-components plugin to babelrc if you want hydration property mismatch warnings dissappear.
