### ISSUE TITLE
Fix ActionList.Item hover and focus background color

### ISSUE THREAD

**Issue by colebemis** [primer/react#1480]
ActionList.Item is missing a hover and focus background color in dark high contrast and color blind themes.

![CleanShot 2021-09-29 at 17 43 01](https://user-images.githubusercontent.com/4608155/135367375-d2245c88-0d9a-4578-ac97-a24c2b1976de.gif)

This makes hover and focus states invisible in new Projects dropdown menus when viewing in dark high contrast or color blind themes.

![CleanShot 2021-09-30 at 07 38 36](https://user-images.githubusercontent.com/4608155/135476433-bd6c66c5-9838-41de-912c-0ca8e6ec6b85.gif)

**To Reproduce**
1. Go to https://primer.style/react/storybook?path=/story/composite-components-actionlist--single-select-list-story&globals=dayScheme:dark_high_contrast
2. Notice that hovering or clicking on items in the list doesn't change the background color

**Expected behavior**

ActionList.Item should change background colors when hovering or focusing. See example in the dark theme:

![CleanShot 2021-09-29 at 17 43 40](https://user-images.githubusercontent.com/4608155/135367437-75323fee-773a-481e-bb31-513dc03709c8.gif)

![CleanShot 2021-09-30 at 07 39 38](https://user-images.githubusercontent.com/4608155/135476639-a2dec91f-5ed9-4759-b7f8-8c11551840c0.gif)

**Additional context**

The hover and focus background colors are currently hard-coded in the ActionList.Item component ([source](https://github.com/primer/react/blob/main/src/ActionList/Item.tsx#L18-L46)) because it was built before the new [functional color system](https://primer.style/primitives/colors#functional-variables) variables where published. Now that the new functional variables are published, let's use those instead. Whoever takes this on should work with @auareyou to pick the right color variables.

**Comment by tallys** [comment]
update: Working session with @colebemis @mperrotti and @auareyou on the books for next week - looking to use the functional variables to unblock this work and scope longer term considerations around states and themes.

FYI @alliethu (getting this on your radar bc this can affect accessibility)

**Comment by broccolini** [comment]
Status update from planning meeting: WIP https://github.com/primer/primitives/pull/259 - @mperrotti is going to review with @vdepizzol this week.
