### ISSUE TITLE
Making Avatars in an AvatarStack clickable in an accessible way

### ISSUE THREAD

**Issue by glortho** [primer/react#1511]
👋🏼 We use the [AvatarStack](https://primer.style/react/AvatarStack) component, together with [Avatar](https://primer.style/react/Avatar), to show assignees on board cards in Memex:

<img width="328" alt="Screen Shot 2021-10-12 at 10 46 46" src="https://user-images.githubusercontent.com/526284/136978596-f295440e-c10c-41a6-9e26-cecfa004ae1e.png">

We are making individual assignees clickable so that you can toggle filtering by that assignee ([demo](https://memex-c25vj1qcj-monalisa.vercel.app/orgs/app/projects/1/views/1?layout=board)):

https://user-images.githubusercontent.com/526284/136979134-8655a82c-0c6a-4303-96dd-0b8628781976.mp4

In this demo 👆🏼, I have coerced the Avatar component (`<img/>`) to behave like a button/a by adding an `onClick` handler and a style attribute `cursor: pointer`.

For accessibility purposes, I'd rather actually wrap the Avatar component in an invisible, zero-padded button. Doing that breaks the stack styling, however, as you can see here:

<img width="328" alt="Screen Shot 2021-10-12 at 09 26 37" src="https://user-images.githubusercontent.com/526284/136979535-b8c75314-60eb-4125-a503-ad6857f7a3d6.png">

I can start to hack around this by adding the `pc-AvatarItem` class to the button I've wrapped the Avatar with, but that yields some other styling issues, and it's obviously not good form to be explicitly hoisting the class name this way.

Do you have suggestions for how best to go about this for now, and longer term?

**Comment by gaknoll** [comment]
Issue has been transferred to the [github/primer repo](https://github.com/github/primer/issues/465). Closing out this duplicate issue for now.
