### ISSUE TITLE
useTheme should know which colorscheme is currently applied

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#1664]
When an unknown colorscheme is applied, the ThemeProvider falls back to a base theme, which is nice for ensuring a user sees something reasonable, but may not be the expected theme. 

This behavior is a little hard to test for, since there's no property returned from `useTheme` describing which colorScheme is currently applied in the context.

```jsx
<ThemeProvider {...{colorMode: night, nightScheme: dark_colorblind}}>...</ThemeProvider>
```

for instance, gives a `useTheme` return of 

```js
const theme = useTheme()
=> {
   colorMode: "night"
   colorScheme: "dark_colorblind"
   dayScheme: "light"
   nightScheme: "dark_colorblind"
   resolvedColorMode: "night"
   theme: {}
}
```

but when I pass an invalid colorScheme like

```jsx
<ThemeProvider {...{colorMode: night, nightScheme: dark_protanopia}}>...</ThemeProvider>
```

```js
const theme = useTheme()
=> {
   colorMode: "night"
   colorScheme: "dark_protanopia"
   dayScheme: "light"
   nightScheme: "dark_protanopia"
   resolvedColorMode: "night"
   theme: {}
}
```

This does `console.error`, however since themes can be provided at runtime it might be helpful to be able to determine which theme is currently applied in a given context.

Based on the above, the current way to do that seems like

```js
theme.theme && theme.colorScheme && theme.colorScheme in theme.theme.colorSchemes ? theme.colorScheme : _some other color scheme - the default one _
```

A `resolvedColorScheme` property returned from useTheme, that returns which color scheme is actually active in a context might be a nice way to internalize that check _and_ provide a nice way to validate that the correct them is applied from a consumer.

```jsx
const themeProps = {colorMode: night, nightScheme: dark_protanopia}
<ThemeProvider {...themeProps}>
   <Component />
</ThemeProvider>

const Component = () => {
   const theme = useTheme()
   return <div id="testme" data-test-colorscheme={theme.resolvedColorScheme} />
}

assertEquals(window.testme.dataset.testColorscheme, theme.resolvedColorScheme)
```

**Comment by colebemis** [comment]
Added to our inbox. Thank you!

**Comment by colebemis** [comment]
@mattcosta7 What's the urgency of this? Is it blocking any Memex work?

**Comment by mattcosta7** [comment]
Nope - not blocking anything @colebemis, the hack we have in place to test this is ok for the time being

**Comment by mattcosta7** [comment]
@colebemis  - opened a pr for it https://github.com/primer/react/pull/1679
