### ISSUE TITLE
Strange checkbox rendering in `ActionList` with `shape-rendering: crispedges;` in Chrome

### ISSUE THREAD

**Issue by dmarcey** [primer/react#1666]
**Describe the bug**

After upgrading to the latest version of `primer/react` in the new Projects experience, I noticed that the checkboxes look strange 

![image](https://user-images.githubusercontent.com/5487287/144054881-ddd12772-8f03-4313-aa33-3ffb74fb73bc.png)

I believe that this is due to the fact that the checkboxes are now using a `<rect />` for the checkbox as of:

https://github.com/primer/react/commit/250e4b00f4d996b6125d381bae2487b57156687c#diff-008c41e7105eb2bb0be2768425e46a21944dcbffc988ca984f91d3d11d280efdR339-R348

Now that we're using a `<rect />` there, in projects, which is hosted in `github.com` and will have all the css from `github.com` in its stylesheet, those icons are getting affected by a global style rule:

```css
rect {
    shape-rendering: crispedges;
}
```

In MacOS + Chrome, on a non-retina display, the checkboxes are rendered like the screenshot above. In other environments (or if I move the browser window to my laptop's display), the checkboxes are rendered normally. Also, if I add a style rule of:

```css
rect {
    shape-rendering: auto;
}
```

the checkboxes look how I would expect.

I can reproduce in the PRC storybook, by manually adding that rule (the bottom checkbox has `crispedges` the top does not`):

![image](https://user-images.githubusercontent.com/5487287/144056499-6a00aed7-0297-46bb-9913-26f3f6f002f1.png)

We could come up with a projects-specific fix, but that would mean that other consumers of PRC that are hosted in the `github.com` environment might have to come up with a similar fix, so I wasn't sure if it was worth it to add something like `shape-rendering: auto` to the component in PRC (if that is indeed the correct fix).

**Comment by siddharthkp** [comment]
This is the global declaration in `github.com` in [commit-acitivity.scss#L17](https://github.com/github/github/blob/deab55d89c624406e4a92c9493be98633c0446af/app/assets/stylesheets/custom/github/commit-acitivity.scss#L17):

```css
rect {
  shape-rendering: crispedges;

  &.max {
    fill: var(--color-attention-fg);
  }
}
```

This feels like a global scope creep? I want to say this isn't intentional and probably needs to be scoped 🤔

If we can't move that rule, we can absorb that into primer with `shape-rendering: auto` in the component as a workaround/hot-fix.

cc: @simurai Can i get your thoughts on this?

**Comment by simurai** [comment]
@siddharthkp Based on the PR https://github.com/github/github/pull/2373 where it was added, I think initially it was meant for those Insights graphs? E.g. making those bars in https://github.com/primer/react/graphs/commit-activity look sharp:

![image](https://user-images.githubusercontent.com/378023/144526695-6dc6031f-4bbe-42d9-bff6-59d35a9d113f.png)

Yeah, would be great to limit the scope a bit. Hard to say, but maybe to `g.bar rect`. Or the more generic `.graphs rect`. I'll add it to our backlog. 👍

**Comment by siddharthkp** [comment]
@simurai Thanks! How do we test visual regressions in github .com that might result from this?

**Comment by simurai** [comment]
There were talks about visual regression testing in the past few years. But as of today it's still a manual process:

1. Deploy to review-lab
2. Click around to see if something looks off

I know, it sounds a bit tedious and risky... and it is.

**Comment by joelhawksley** [comment]
We have considered various approaches to this in https://github.com/github/design-infrastructure/issues/29, and I've been doing some investigations into ways of snapshotting computed styles for parts of the DOM, albeit in a very experimental fashion.

@siddharthkp how do you think we might test for visual regressions?

**Comment by siddharthkp** [comment]
@joelhawksley For primer libraries or applications like github.com?

For primer/react, I am adding [chromatic](https://www.chromatic.com) which works by screenshotting each story in **storybook** and comparing it with the previous snapshot (https://github.com/primer/react/pull/1683)

A similar flow would work nicely for primer-css as well.
