### ISSUE TITLE
Documentation: component is deprecated with no link to a recommended alternative

### ISSUE THREAD

**Issue by mazanec202** [primer/react#1692]
**Describe the bug**
In the documentation are some components (e.g. [Dropdown](https://primer.style/react/Dropdown)) marked as deprecated, however, no recommended alternative is proposed.

**To Reproduce**
1. Go to https://primer.style/react/Dropdown
2. See `Deprecated` label
3. See no proposed alternative

**Expected behavior**
A link taking the user to a recommended alternative is given to the user

**Screenshots**
![image](https://user-images.githubusercontent.com/18451042/144671717-c9503d17-b88e-436c-81e0-2c39bce9a032.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 96.0.4664.45

**Comment by siddharthkp** [comment]
Hi! 

Thanks for pointing this out! Updated the docs: https://github.com/primer/react/pull/1808

**Comment by mazanec202** [comment]
Hi, just out of curiosity, is there any way to access [DropdownMenu](https://primer.style/react/DropdownMenu) other than going through the deprecated [Dropdown](https://primer.style/react/deprecated/Dropdown)? I.e., shouldn't DropdownMenu be in the list of components on the left side? Or is it omitted because it is still in Alpha? I ask because I didn't know about the existence of DropdownMenu until now.


Thanks for your answer! I have used React Primer for the first time, so apologies if my question is stupid :)

**Comment by siddharthkp** [comment]
Hi! There is a PR that adds DropdownMenu to the nav :) You'll see it there soon.

> Or is it omitted because it is still in Alpha?

That was the idea initially, but we're changing that.
