### ISSUE TITLE
Eslint plugin overzealously merging PointerBox['bg'] into 'sx'

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#1756]
**Describe the bug**

When enabling the eslint plugin `primer-react/no-system-props` the `bg` prop on `PointerBox` is determined to be a system prop, which is fixed to nesting in sx, instead of staying at the root. 

https://github.com/primer/react/blob/main/src/PointerBox.tsx#L12-L29 

The pointerbox implementation reads the bg prop though, to pass the color to the svg rendering the caret.

This bg should either be left alone when autofixing, and not report an eslint error, _or_ the props sx['bg'] should be used to determine the carets stroke/fill

**Comment by colebemis** [comment]
@mattcosta7 Upgrading to `eslint-plugin-primer-react@0.7.3` should fix this 👍
