### ISSUE TITLE
TextInput: trailingVisual elements with onClick are triggered by hitting enter.

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#1769]
**Describe the bug**

Not sure if this is expected behaviour...

For some reason when adding a button inside the input when pressing enter the method on that button gets called. This is unexpected behaviour as we would like to use this for a clear button instead of it triggering an onSubmit event.

```
<form onSubmit={() => alert("hit enter to submit")}>
   <TextInput trailingVisual={<button onClick={() => alert("clicked on trailing visual")}>test</button>} placeholder="Search" size="large" />
</form>
```
[Sandbox Example](https://codesandbox.io/s/quirky-johnson-peu2t?file=/src/App.js)

**To Reproduce**
1. Enter something in the search field 
2. Press enter

**Expected behavior**
Only trigger the onSubmit call.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/980622/148084650-9ac65a04-745a-4901-8357-5b0942ab075b.mov
)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 15.1

**Comment by pksjce** [comment]
Hi! thanks for the issue. Our solution to this is to basically create a `trailingAction` prop which accepts buttons or other components which we can then make sure work independently.
We intended to do it in https://github.com/github/primer/issues/552
I can have a PR up to fix this asap.

**Comment by siddharthkp** [comment]
Hi! 👋 

html `button` has a default type of `type=submit`. [Ref: MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)

When you use a `Button` component from primer, we should default to `type=button`.

```jsx
// 👍 
<TextInput 
  trailingVisual={<Button onClick={}>Copy</Button>} 
/>
```

If you want to use a custom html element for `trailingVisual`, the ownership of that attribute shifts to the user!

```jsx
// 👎 
<TextInput 
  trailingVisual={<button onClick={}>Copy</button>} 
/>

// 👍 
<TextInput 
  trailingVisual={<button type="button" onClick={}>Copy</button>} 
/>
```

**Comment by mperrotti** [comment]
@siddharthkp can we close this? I think your response is sufficient.

**Comment by siddharthkp** [comment]
The remaining suggestion here is to add `type="button"` to <Button> by default (html default is type="submit"). Leaving it up to @pksjce to decide
