### ISSUE TITLE
Flash component renders differently in server vs client

### ISSUE THREAD

**Issue by peterbe** [primer/react#1773]
**Describe the bug**

We use it like this:
```jsx
import { Flash } from '@primer/components'

...

<Flash variant="warning">
   <p>
      Bla
   </p>
</Flash>
```

When rendered in NextJS on the server, the HTML it generates becomes:
```html
<div class="Flash-sc-4y90bn-0 bIFBCA">
  <p>
    Bla
  </p>
</div>
```

But in the browser, it becomes:
```html
<div class="Flash-sc-4y90bn-0 eTFOFY">
  <p>
    Bla
  </p>
</div>
```

If you have access, please see: https://github.com/github/docs-engineering/issues/1388
If not, open https://docs.github.com/en/rest/reference/repos and note how the "We've recently moved some of the REST API documentation ..." flash message changes color as the page re-renders in the client. 

**Note:** As this is a public repo, please be careful not to include details or screenshots from unreleased GitHub products or features. In most cases, a good bug report should be able to describe the new component without including business logic or feature details, but if you must discuss context relating to an unreleased feature, please open an issue in the private [Design Systems repo](https://github.com/github/design-systems/issues/new/choose) and link to it here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siddharthkp** [comment]
This is a great bug report! Thanks for taking the time, i'll find out what's up.
