### ISSUE TITLE
Button state selected

### ISSUE THREAD

**Issue by YousefED** [primer/react#1783]
How do I use the React components to show a button as Selected?

With the CSS Primer, this is demonstrated here: https://primer.style/css/components/buttons#selected

![image](https://user-images.githubusercontent.com/368857/148786436-48fe4371-3fd4-4ed4-8dcc-2ece827d9c26.png)

**Comment by mperrotti** [comment]
We don't currently have a way to do this.

@pksjce - this is something to consider with the work you're doing on buttons right now

**Comment by siddharthkp** [comment]
Hi @YousefED, (just curious) where do you use this pattern?

**Comment by pksjce** [comment]
We didn't consider it originally. Though the solution seems to be just to add background and box shadow, do some testing and push it both for Button and Button2
