### ISSUE TITLE
Repo Language Component Proposal

### ISSUE THREAD

**Issue by thornsberrysara** [primer/react#1792]
## Description

Add a label within a <Box> that shows the programming language and color indicator of a repository.
<img width="497" alt="Screen Shot 2022-01-13 at 10 28 55 AM" src="https://user-images.githubusercontent.com/40149173/149359404-72d223f7-5022-493b-ac1c-592918ea9a1f.png">

### Design

- [ ] Design is finalized. Link to mockups/prototypes:
- [ ] Design is being finalized by feature team. Link to any in progress mockups:
- [x] Assistance requested in finalizing design

### Usage

This component should be used as a label with a short, 1-2 word description of what it is indicating.

## Implementation

Please describe how you would like this component to be built. Design systems is happy to help with the implementation of new components (as time/roadmap allows) but also recognizes that sometimes feature teams prefer to implement components themselves.

- [ ] Feature team would like to implement this component
- [ ] Feature team would like the Design Systems team to implement this component
- [ ] This component is already built, feature team requests assistance moving it to Primer React Components from outside application
- [x] Other: (please describe below)
Would be happy to assist with the implementation, unless this is something that needs to be completed internally.

**Comment by siddharthkp** [comment]
Hi! 

Not sure if I understand the proposal here for primer-react, can you please elaborate a bit?
