### ISSUE TITLE
Error with command: npm install @primer/react

### ISSUE THREAD

**Issue by mohamedmehdigara** [primer/react#1829]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-01-31T13_58_03_031Z-debug.log

**Comment by rezrah** [comment]
Closing for now. Feel free to reopen if you're still having issues.
