### ISSUE TITLE
Element-bound events with `useOnEscapePress` are triggering all `escape` events globally

### ISSUE THREAD

**Issue by iansan5653** [primer/react#1854]
A change introduced in `34.4.0` was to add support for `useOnEscapePress` to bind events to specific elements instead of just the document root (and to implement that new functionality in the `useOverlay` hook):

> https://github.com/primer/react/pull/1824 [4eab65e5](https://github.com/primer/react/commit/4eab65e57571d64a0f8a4fcb4aafbf47d3e98a2d) Thanks [@siddharthkp](https://github.com/siddharthkp)! - Overlay: Attach escape handler to overlay container instead of document to fix stopPropagation

This makes sense, because the events need to be bound to the overlay container so that the overlay can `stopPropogation` and keep its events contained.

However, this hook is using a global function with a global array of event handlers, even with the element-bound events. So when an escape event is triggered on a top-level overlay, it still calls every escape event handler ever registered:

https://github.com/primer/react/blob/96473f398bb0fe5f2eff1b3e8bb9110a009f1894/src/hooks/useOnEscapePress.ts#L3-L19

An example of the undesirable behavior that this bug causes is visible in the [Nested Overlays](https://primer-react-68602yp8g-primer.vercel.app/react/storybook?path=/story/internal-components-overlay--nested-overlays) story:

- Click the dropdown arrow next to "Star"
- Click "+ Create List"
- Press <kbd>Escape</kbd>
  - Only the top overlay should close, but both do instead
- Click the dropdown arrow next to "Star" again
  - Both overlays open in incorrect order because the top overlay was never cleaned up properly

I see two possible ways to fix this:

1. For element-bound `useOnEscapePress` events, bind/unbind the passed handler function directly. This seems simple but I'm not sure why the behavior is the way it is in the first place - there may be a reason for it. Example of this change:
```ts
    if (element) element.addEventListener('keydown', escapeCallback)
    else document.addEventListener('keydown', escapeCallback)
    return () => {
      if (element) element.removeEventListener('keydown', escapeCallback)
      else document.removeEventListener('keydown', escapeCallback)
    }
```
2. Or, only use `useOnEscapePress` for global (root-bound) events, and just bind the escape event using react's native `onKeyPress` property instead.

cc @siddharthkp @mattcosta7

**Comment by siddharthkp** [comment]
@iansan5653 #1861 Should take care of this! I've added a story if you want to see the new behavior: https://primer-react-jhga7sawh-primer.vercel.app/react/storybook?path=/story/internal-components-overlay--memex-nested-overlays
