### ISSUE TITLE
ModuleNotFoundError in clean create-react-app

### ISSUE THREAD

**Issue by chadfawcett** [primer/react#1863]
**Describe the bug**
I wanted to try to simplify and reproduce an issue I'm having in a project, so thought I'd throw together a codesandbox with a minimal setup to reproduce. However, I can't even use `@primer/react` within codesandbox from the looks of it.

**To Reproduce**
1. [Create a new React codesandbox](https://codesandbox.io/s/new) (basic create-react-app)
2. Add `@primer/react` and `styled-components` as dependencies
3. Try to import `ThemeProvider`

https://codesandbox.io/s/priceless-knuth-qkiq9?file=/src/App.js

**Expected behavior**
I expected to be able to import `ThemeProvider` within a create-react-app project without error.

**Screenshots**
<img width="951" alt="Screen Shot 2022-02-11 at 3 33 47 PM" src="https://user-images.githubusercontent.com/3250463/153684622-67a59e6a-012b-49c6-a78c-783dde523089.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser: Chrome
 - Version: Version 98.0.4758.80

**Comment by pksjce** [comment]
Thanks for the issue @chadfawcett. I think this is a problem with codesandbox itself. Though there's not many other complaints on their issues page.
I found this issue and added our failure as a comment there. Will hope for a speedy reply from codesandbox. They seemed to have been active on this thread recently. Else maybe @siddharthkp knows how we could get their attention faster. 🙏 
https://github.com/codesandbox/codesandbox-client/issues/6172#issuecomment-1038515409

I'm suggesting a workaround to try out [stackblitz](https://stackblitz.com/edit/react-wupdy4).

**Comment by chadfawcett** [comment]
Thanks @pksjce for pointing out the upstream issue. Happy to close this issue and follow along on the codesandbox one if you'd like. Saw that you linked to this issue though, so I'll leave that up to you.

I'll check out stackblitz!

**Comment by pksjce** [comment]
Codesandbox finally made the fix! The above broken example works now!
