### ISSUE TITLE
StyledOcticon doesn't have mr props as shown in Header component page docs

### ISSUE THREAD

**Issue by rafae2k** [primer/react#1912]
**Describe the bug**

In [Header component page](https://primer.style/react/Header) `<StyledOcticon />` is shown with a `mr` prop.

However this prop doesn't exists in `<StyledOcticon />`.

**Screenshots**

![Screen Shot 2022-03-01 at 09 36 08](https://user-images.githubusercontent.com/53544360/156170611-cde688f8-74b7-43d6-b6eb-60e81034bb5e.png)

**Comment by rezrah** [comment]
Thanks @rafae2k - The example has been updated in the v35 RC branch, which will be reflected on primer.style next week. In the meantime, you can see the [updated example here](https://primer-react-micskta7h-primer.vercel.app/react/Header#examples).

TL;DR:

```diff
-<StyledOcticon icon={MarkGithubIcon} size={32} mr={2} />
+<StyledOcticon icon={MarkGithubIcon} size={32} sx={{mr: 2}} />

```
