### ISSUE TITLE
`Button` display type changed from `inline-block` to `grid` changing existing arrangements.

### ISSUE THREAD

**Issue by Swiftwork** [primer/react#1978]
**Describe the bug**
The new `Button` component has a block type display `display: grid`, while the old type was inline `display: inline-block`. Causing existing arrangements to behave differently as can be seen when using a `ButtonGroup`.

**To Reproduce**
```tsx
<ButtonGroup>
  <Button variant="danger">Delete Session</Button>
  <Button>Share</Button>
  <Button>Save</Button>
  <Button>Publish</Button>
</ButtonGroup>
```

**Expected behavior**
One of:
1. The `Button` display type is changed to an inline type such as `inline-grid`.
2. `ButtonGroup` changes display type to `inline-flex`.
3. A dynamic prop that changes such as the `block`.

Preference leaning towards the first alternative as this should be the most backward compatible.

**Screenshots**
![image](https://user-images.githubusercontent.com/455178/158848258-60cafdb4-23e6-4a98-9bef-0b415e76b932.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: 35.0.1

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: 35.0.1

**Comment by pksjce** [comment]
Hi! Thanks for raising this issue. We are still deciding within the team how block and inline buttons will work going forward. Meanwhile, you can use the `sx` prop here to provide inline behaviour for the button and make it behave as you want.

**Comment by Swiftwork** [comment]
@pksjce Thank you for the update, that is the method I am currently going with. I set `display: inline-flex` on my `<ButtonGroup>` using sx.
