### ISSUE TITLE
Button content grid cells are equal

### ISSUE THREAD

**Issue by dusave** [primer/react#1979]
**Describe the bug**
With version 35.x, Buttons have a new content grid, containing spots for leading and trailing icons along with the content of the button. The issue is that the columns are all `1fr` by default, giving much more space to the icon cells than they need whilst compressing the content cell.

**To Reproduce**
1. Create a button with leading and/or trailing icons, along with content
2. See error

<img width="333" alt="image" src="https://user-images.githubusercontent.com/2447456/158883921-38619ad8-dd35-4c03-902d-f0cf3f3d84b1.png">

**Expected behavior**
Grid cells should be `gridTemplateColumns: "min-content 1fr min-content"`
<img width="334" alt="image" src="https://user-images.githubusercontent.com/2447456/158884004-037c9707-9002-406e-bbe9-7d134f33282d.png">

**Comment by lesliecdubs** [comment]
Hey @dusave, I'm so sorry we didn't get back to you on this much sooner! Apologies 🙏🏻 

Are you able to confirm this is still a problem?

**Comment by tallys** [comment]
Update, @langermank is working on resolving this right now 🎉

**Comment by lesliecdubs** [comment]
Noting that the linked PR includes breaking changes, so we'd schedule them to go out with the next major release.

**Comment by langermank** [comment]
Addressed here https://github.com/primer/react/pull/2792
