### ISSUE TITLE
Iii

### ISSUE THREAD

**Issue by saingsocheat** [primer/react#1985]
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-550017427');
</script><head/>
<install: get = service cloud.firestore {
  match /databases/{database}/documents {

**Comment by siddharthkp** [comment]
👀 👀 👀 👀 👀 

This seems like a mistake or an attempt at code injection :)
