### ISSUE TITLE
Padding on small buttons is nonstandard

### ISSUE THREAD

**Issue by iansan5653** [primer/react#1988]
**Describe the bug**

Small buttons (`Button` with `size="small"`) have `4px` padding on top and bottom and `12px` padding on the sides. This side padding does not match a spacing value from the theme (which goes from `8px` to `16px`). This is not a major issue, but it does present annoying difficulties when trying to make other components look consistent with button padding. All spacing values should be consistent with the theme.

**To Reproduce**

```tsx
<Button size="small">Example small button</Button>
```

**Expected behavior**

I expected the padding to match a spacing value from the [theme](https://primer.style/react/theme-reference).

**Comment by siddharthkp** [comment]
Hi!

For what it's worth, 12px will be added to the theme in the future: https://primer.style/primitives/spacing

> But it does present annoying difficulties when trying to make other components look consistent with button padding.

Is this because making an component match the size of a button can't be done without using non-theme px values?

**Comment by iansan5653** [comment]
> Is this because it's hard to match the size of a button without using out of theme px values?

Yep. I don't remember exactly what I was doing when I opened this, but I think most likely I was trying to adjust the padding in an `Input` to match the height of an adjacent `Button`.

**Comment by siddharthkp** [comment]
> I was trying to adjust the padding in an Input to match the height of an adjacent small Button.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1863771/186436645-a42fec51-9330-4d50-8f56-1fde3a2c239c.png">

Not sure if it's Button + Input, but would be useful to know what combination it was because form components need to be the same size out of the box

**Comment by iansan5653** [comment]
Yeah I'm really not sure. Maybe it was a custom component that I wanted to match the size of the `Button` with. I'd be happy closing this if you'd like, considering I no longer know what the exact use case was.

**Comment by siddharthkp** [comment]
I'm okay with that. But i'm super curious so if you run into again, feel free to open back with the code!
