### ISSUE TITLE
`UnderlineNav` is missing examples for usage with icons/counters

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#2011]
While the [CSS](https://primer.style/css/components/navigation#underline-nav) one has examples of usage with icons this React one doesn't.

<img width="1000" alt="Screenshot 2022-04-05 at 12 05 40" src="https://user-images.githubusercontent.com/980622/161740698-5864d99c-eebb-4d96-9f50-e18ccdbfa7ea.png">

**Comment by siddharthkp** [comment]
I'd love to see `UnderNav` support [Button-ish API](https://primer.style/react/Button#counter-component) to add support `icon` /`leadingVisual`/ `counter` :)

**Comment by lesliecdubs** [comment]
Noting that the new `UnderlineNav` v2 (currently a draft that will replace the existing `UnderlineNav` upon completion) will support icons https://primer.style/react/drafts/UnderlineNav2#with-icons and counters https://primer.style/react/drafts/UnderlineNav2#loading-state-for-counters, thanks to @broccolinisoup! 😃

I'm going to update this issue to "closed as completed." Keep your eye on the [Primer changelog](https://github.com/github/primer-changelog/discussions) for updates when the new `UnderlineNav` is fully released!
