### ISSUE TITLE
Theme provider is not respecting `colorMode="auto"` 

### ISSUE THREAD

**Issue by jfuchs** [primer/react#2045]
**Describe the bug**

**To Reproduce**
1. Go to https://codesandbox.io/s/clever-volhard-w8csh2?file=/src/App.tsx
2. Toggle your system color mode
3. Note button not changing

**Expected behavior**
Button changes color mode

**Screenshots**
![CleanShot 2022-04-22 at 11 41 06@2x](https://user-images.githubusercontent.com/21195/164774964-03d73943-efe9-41d0-93c3-ed737df978b3.png)
![CleanShot 2022-04-22 at 11 42 23@2x](https://user-images.githubusercontent.com/21195/164775158-44b3e88a-39b7-49cc-8ce2-28e1896cf8bf.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome latestish

**Additional context**
- I believe the issue was introduced in https://github.com/primer/react/pull/1936
- Reloading the page will give the correct auto color mode initially

**Comment by siddharthkp** [comment]
Can confirm! The theme is correct on first render based on system settings but isn't responding to changes to system settings after that


https://user-images.githubusercontent.com/1863771/165057963-147ebdbb-ebe2-4d27-b2a1-6766142accc1.mov
