### ISSUE TITLE
FormControl.Label causing Layout Shift

### ISSUE THREAD

**Issue by filipedeschamps** [primer/react#2051]
**Describe the bug**
`FormControl.Label` is causing Layout Shift on page load (see gif below)

**To Reproduce**
1. Create a page using `FormControl` with a `FormControl.Label` component. For example:

```
        <FormControl>
          <FormControl.Label>Username</FormControl.Label>
          <TextInput />
        </FormControl>
```

2. Refresh the page.

**Expected behavior**
`<FormControl.Label>` should not flash on page load.

**Screenshots**
# Gif of the page being refreshed

![layout-shift](https://user-images.githubusercontent.com/4248081/166147568-883ee5bf-3c1c-4cce-b20b-33586cbfd488.gif)

# Static image showing the exact frame where `<FormControl.Label>` is invisible

![image](https://user-images.githubusercontent.com/4248081/166147565-896eedf9-cbb4-46ce-adb5-a1f8ab0c612d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser tested on Chrome (latest) and Safari (latest)

**Additional context**

There's no logic applied to the `<FormControl.Label>` component. Here's the code from the gif above:

```js
return (
    <form style={{ width: '100%' }} onSubmit={handleSubmit}>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        {globalErrorMessage && <Flash variant="danger">{globalErrorMessage}</Flash>}

        <FormControl id="username">
          <FormControl.Label>Nome de usuário</FormControl.Label>
          <TextInput
            ref={usernameRef}
            onChange={clearErrors}
            name="username"
            size="large"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            aria-label="Seu nome de usuário"
          />
          {errorObject?.key === 'username' && (
            <FormControl.Validation variant="error">{errorObject.message}</FormControl.Validation>
          )}

          {errorObject?.type === 'string.alphanum' && (
            <FormControl.Caption>Dica: use somente letras e números, por exemplo: nomeSobrenome4 </FormControl.Caption>
          )}
        </FormControl>
        <FormControl id="email">
          <FormControl.Label>Email</FormControl.Label>
          <TextInput
            ref={emailRef}
            onChange={clearErrors}
            name="email"
            size="large"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            aria-label="Seu email"
          />
          {errorObject?.key === 'email' && (
            <FormControl.Validation variant="error">{errorObject.message}</FormControl.Validation>
          )}
        </FormControl>
        <FormControl id="password">
          <FormControl.Label>Senha</FormControl.Label>
          <TextInput
            ref={passwordRef}
            onChange={clearErrors}
            name="password"
            type="password"
            autoCorrect="off"
            autoCapitalize="off"
            spellCheck={false}
            size="large"
            aria-label="Sua senha"
          />
          {errorObject?.key === 'password' && (
            <FormControl.Validation variant="error">{errorObject.message}</FormControl.Validation>
          )}
        </FormControl>
        <FormControl>
          <FormControl.Label visuallyHidden>Criar cadastro</FormControl.Label>
          <Button variant="primary" size="large" type="submit" disabled={isLoading} aria-label="Criar cadastro">
            Criar cadastro
          </Button>
        </FormControl>
      </Box>
    </form>
  );
```

**Additional context (bonus)**

I'm in love with Primer. It's been a long time since I've been this happy developing interfaces.

To everyone involved in this project: **you are amazing** 🤝

**Comment by EnixCoda** [comment]
I'm also having this issue. [demo](https://plkyud.csb.app/)

The issue occurs because the `FormControl` is using double-render strategy.
https://github.com/primer/react/blob/03f3427ae18c70a143a43545f31bcbcba03ef2e4/src/utils/create-slots.tsx#L25-L30

I _guess_ wrapping the input component with slot as well would solve this issue, everything would be rendered since the 2nd render.
https://github.com/primer/react/blob/03f3427ae18c70a143a43545f31bcbcba03ef2e4/src/FormControl/FormControl.tsx#L133-L138

**Comment by siddharthkp** [comment]
Hi! 

First of all, sorry @filipedeschamps, we missed your initial message!

Thanks for reporting this. This is related to the flawed slots implementation, we are tracking it here: https://github.com/primer/react/issues/1690

**Comment by iansan5653** [comment]
I think this is likely solved by https://github.com/primer/react/pull/2216; now both renders should happen before the first paint so there should be no visible flash. I don't see the problem on my end anymore. Please let us know if you do still see it!
