### ISSUE TITLE
Types incompatible with React 18

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#2065]
**Describe the bug**

When updating an application using primer to react and `@types/react` to v18, multiple primer components fail type checks on children, since `React.FC` no longer passes implicit children props (mirroring more closely the behavior of `React.VFC` from v17.

Related issue reported in #2103 

**To Reproduce**

**Expected behavior**

Primer types work correctly with react 18

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siddharthkp** [comment]
Oh that's a shame, would need a sweeping change but at least it's straightforward: https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc
