### ISSUE TITLE
Error when trying to use `ThemeProvider` in react-ts

### ISSUE THREAD

**Issue by assapir** [primer/react#2072]
**To Reproduce**
1. Create a new react app that uses typescript. (I have done that using vite, but I don't think it's matters)
2. Add @premier/react (need to use `--legacy-peer-deps` with npm, otherwise there is a clash between React 17 from premier and 18 from the current project)
3. add the code from the Getting Started tutorial:
```
import {ThemeProvider} from '@primer/react'

function App() {
  return (
    <ThemeProvider>
      <div>...</div>
    </ThemeProvider>
  )
}
```
4. run `npx tsc`
5. Error show up:
```sh
❯ npx tsc
src/App.tsx:8:6 - error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ThemeProviderProps'.

8     <ThemeProvider>
```

**Expected behavior**
No error will show up.

**Desktop (please complete the following information):**
 - OS: Atch linux
 - Browser: Not relevant.
 - Version: 35.2.1
 - TypeScript version: 4.6.4

**Additional context**

**Comment by mattcosta7** [comment]
@assapir  I think this is likely a duplicate of #2065 

react 18 types changed `React.FC` and `React.FunctionComponent` to no longer pass children by default, which many primer types rely on.

**Comment by assapir** [comment]
Yes, seems so, I will close that. Thanks!
