### ISSUE TITLE
useColorSchemeVar should provide explicit color assistance/types and/or primer reexports primitives

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#2086]
**Describe the bug**

In order to use things like scale values from primer/primitives, primer/react recommends using https://primer.style/react/theming#creating-local-color-scheme-variables

`primer/react` doesn't explicitly export the colors, or provide the primitive colors on the theme to access them from, which means that this import needs to either by an indirect import (primer/primitives is a dependency of primer/react), but different versions can be a dependnecy on _other_ code.  for instance, a component could rely on an older version of primitives, or even the eslint plugin can rely on a different version of primer/primitives - so which version is actually used depends on the bundling algo. 

Tools that try to prevent access to non-explicitly depended on packages also may get angry from the indirect imports

The other option is to manually import _another_ version of primer/primitives, which might not conform well to implicitly used version.

I'd suggest that `useColorSchemeVar` potentially allow for access to the full color set, as well as types that better align with the possible color schemes, to help ensure that generated colors are valid everywhere - even if just as suggestions

Primer could also just re-export the primitives consumers might access as a way to tie these together and import everything from primer

**Comment by mattcosta7** [comment]
Yep - @primer/react means components will always get the correct version, but if a user was to install `@primer/primitives` to work with the guidance on `useColorSchemeVar` now, they might install a version that _isn't_ the same as the one primer/react depends on, which I think might be where the gremlins could show up (either having 2 versions installed, or resolving to 1 version at build time, and which one!?)

**Comment by mattcosta7** [comment]
@siddharthkp 

Would something like

`useColorSchemeVars(colors => [partial<Record<color schemes, color>, fallback]>` work here, to at least avoid leaking the primitives dependency into user code?

Not sure how that might Play with consumer themes outside of primitives default, since I'm not sure whether there's access to this from the theme provider currently, but something along that pattern seems like it might help here?

I don't know that we'd need to return a tuple with a fallback, if the assumption is that consumers should be complete here instead - just having that to maintain parity with the current impl

**Comment by siddharthkp** [comment]
Yep, that's exactly what I was thinking of.

Either that or exporting primitives from primer/react:

```diff
- import {useColorSchemeVar } from '@primer/react'
- import {colors} from '@primer/primitives'

+ import {useColorSchemeVar, primitives} from '@primer/react'
```

**Comment by mattcosta7** [comment]
not stale

**Comment by mattcosta7** [comment]
not stale

**Comment by mattcosta7** [comment]
not stale
