### ISSUE TITLE
Error in SSR due to useLayoutEffect in CheckBox

### ISSUE THREAD

**Issue by Swiftwork** [primer/react#2111]
**Describe the bug**
Warning observed with useLayoutEffect and SSR in the CheckBox component.
https://github.com/primer/react/blob/main/src/Checkbox.tsx#L62

**To Reproduce**
1. Setup a next.js project
2. Add primer
3. Add checkbox to page
4. See warning

**Expected behavior**
Replace `useLayoutEffect` with `useIsomorphicLayoutEffect` similar to this PR https://github.com/primer/react/pull/1583.

**Screenshots**
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: 35.2.2

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: 35.2.2

**Comment by Swiftwork** [comment]
I'll look at creating one Monday :)

**Comment by siddharthkp** [comment]
Fixed in https://github.com/primer/react/pull/2155 :)
