### ISSUE TITLE
FromControl causes SSR/hydration error with incorrect id

### ISSUE THREAD

**Issue by Swiftwork** [primer/react#2113]
**Describe the bug**
`FromControl` causes SSR and hydration error with incorrect id between server and client.

**To Reproduce**
1. Create a next.js project
2. Add a basic `FormControl`
3. Observe SSR error in the console

[Reproduction in code can be found here](https://github.com/Swiftwork/next-primer-form-control)

**Expected behavior**
FormControl should render the on the server as the client.

**Screenshots**
> Warning: Prop `id` did not match. Server: "react-aria-1" Client: "react-aria-2"

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: 35.2.2

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: 35.2.2

**Comment by siddharthkp** [comment]
Thanks for reporting this. This is related to our flawed slots implementation, we are tracking it here: https://github.com/primer/react/issues/1690

**Comment by Swiftwork** [comment]
Not stale

**Comment by siddharthkp** [comment]
Not stale, related to https://github.com/primer/react/issues/1690

**Comment by lesliecdubs** [comment]
Is it possible this has been since been resolved as part of https://github.com/primer/react/issues/1690? @siddharthkp could you please confirm?

**Comment by peterbe** [comment]
Still a bug. I'm using a simple NextJS v13 with https://primer.style/react/Autocomplete 

All I did was:
```tsx
export function Input() {
  return (
    <form>
      <FormControl>
        <FormControl.Label id="autocompleteLabel-basic">
          Pick a branch
        </FormControl.Label>
        <Autocomplete>
          <Autocomplete.Input />
          <Autocomplete.Overlay>
            <Autocomplete.Menu
              items={[
                { text: "main", id: "0" },
                { text: "autocomplete-tests", id: "1" },
                { text: "a11y-improvements", id: "2" },
                { text: "button-bug-fixes", id: "3" },
                { text: "radio-input-component", id: "4" },
                { text: "release-1.0.0", id: "5" },
                { text: "text-input-implementation", id: "6" },
                { text: "visual-design-tweaks", id: "7" },
              ]}
              selectedItemIds={[]}
              aria-labelledby="autocompleteLabel-basic"
            />
          </Autocomplete.Overlay>
        </Autocomplete>
      </FormControl>
    </form>
  )
}
```

I can, kinda, solve this by doing something like this:

```tsx

const [isReady, setReady] = useState(false)
useEffect(() => {
  setReady(true)
}, [])

...

{isReady && <Autocomplete> ... </Autocomplete>}
```
