### ISSUE TITLE
Buttons should support href as a prop

### ISSUE THREAD

**Issue by jdrush89** [primer/react#2118]
**Describe the bug**
According to https://github.com/primer/react/issues/1972, LinkButtons have been removed in favor of `<Button as="a" />`.  If this is the recommended way of doing link buttons, then passing an href to the Button component should forward that prop to the a element.  Otherwise, an onClick that sets the window.location.href has to be used which is more code and clunkier.

**To Reproduce**
1. Go to https://primer.style/react/Button
2. Update the first example to `<Button as="a" href="http://google.com">Default</Button>`
3. Click on the Button in the first example
![image](https://user-images.githubusercontent.com/955442/172441354-62c3df2f-43f8-4123-a379-071932b15351.png)

**Expected behavior**
The user should be navigated to the url passed in as the href.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 101.0.4951.67 (Official Build) (32-bit)

**Comment by AdamShwert** [comment]
This bug also causes an issue where when you middle mouse click on a button, nothing happens because the href prop is not passed through. We are currently still using LinkButtons as a result so as to not lose functionality until this issue is resolved
