### ISSUE TITLE
The popover component should auto close when clicking outside of element.

### ISSUE THREAD

**Issue by Lukeghenco** [primer/react#2135]
**Describe the bug**
I am trying to use the [Popover](https://primer.style/react/Popover) component in DotCom for the file comments within our React app prototype & it does not work as I assumed when clicking outside of the Popover component. I expected it to close the popover like the overlay, details or selection menu components do. Instead, the component stays open. Maybe there needs to be a [closeOnOutsideClick](https://primer.style/react/Details#usedetails-hook-configuration-options) prop option that the component can be passed (e.g. `<Popover closeOnOutsideClick={true} />`) like the **Details** component, if we don't always want to default to outside clicks closing the popover.

https://user-images.githubusercontent.com/15013243/174690037-13d31be9-5ab2-41f9-a0c4-17e4a11ba1cd.mov

**Additional context**
[This is probably a good code pattern to solve this for the component](https://stackoverflow.com/a/54292872)

**Comment by siddharthkp** [comment]
Hi! 

How do you feel about using the accessible ActionMenu instead of Popover here?

https://primer.style/react/ActionMenu#with-a-custom-anchor

**Comment by Lukeghenco** [comment]
@siddharthkp that is a great recommendation, but it doesn't have the pre-existing styles that we are using on the Files page. 

We need the directional caret. You can test it [here](https://github.com/github/github/pull/222170/files#r902700995) on current production to get the look and feel.

## 1 example on the Diff Files page comment

<img width="268" alt="Screen Shot 2022-06-21 at 7 33 42 AM" src="https://user-images.githubusercontent.com/15013243/174826572-1a769bcd-f390-4bf3-9037-6ab758cbbd6f.png">

## 2 examples on Issue comments

<img width="731" alt="Screen Shot 2022-06-21 at 7 42 00 AM" src="https://user-images.githubusercontent.com/15013243/174828015-5c0835e1-de67-423e-b606-afdcfcc88ba2.png">

<img width="665" alt="Screen Shot 2022-06-21 at 7 42 05 AM" src="https://user-images.githubusercontent.com/15013243/174828035-db747272-3105-4996-b23e-730bafccea90.png">

### Final Thoughts

The `ActionMenu.Anchor` would work for us outside of it missing the directional caret styling. I do feel very strongly that the **Popover** should have an auto-dismiss `closeOnOutsideClick` prop at minimum.

**Comment by siddharthkp** [comment]
Yep, the design change is recent. Let me get @vdepizzol and @ashygee for comments as well. 

> I do feel very strongly that the Popover should have an auto-dismiss closeOnOutsideClick prop at minimum.

That's fair! We definitely can consider adding that.
FYI, Popover has other accessibility issues as well. For example, it does not implement a focus trap. You might like [AnchoredOverlay](https://primer.style/react/AnchoredOverlay) as a better building block (you would have to add the caret though)

**Comment by langermank** [comment]
@Lukeghenco for clarity, do we need the caret for visual parity with the non-React implementation? If that's not the case, is there room here for small visual updates? As @siddharthkp described we're moving away from using carets in overlay type patterns.

**Comment by Lukeghenco** [comment]
@langermank if we are moving away from carets as a design in overlay type patterns, I think we are good for implementing the **ActionMenu** in place of the **Popover**. If we plan to keep Popover though, the non-React implementation does close when clicking outside of the popover as shown in the pics and links for [my comment above](https://github.com/primer/react/issues/2135#issuecomment-1161843686)

**Comment by siddharthkp** [comment]
> I have moved forward with using ActionMenu for my current work though, without directional carets.

That's great to hear.

I'm going to keep this issue open for Popover and take it to the next prioritisation meeting
