### ISSUE TITLE
useDetails + Details typings issue introduced in v27 and still present today

### ISSUE THREAD

**Issue by jeffwilcox** [primer/react#2146]
**Describe the bug**

The `useDetails` hook typings seem to have recently regressed. We're trying to move our
app up to the latest Primer React generation and hitting issues.

We're on React v17 and otherwise had a good experience working through the breaking changes.

Not enough of a TypeScript expert in terms of how they're generated from Primer to be too helpful
but willing to learn.

This regressed from v26 --> v27 with the big refactor to generate typings instead of being manually
maintained per https://github.com/primer/react/releases/tag/v27.0.0. Confirmed just now that this
basic app is OK in v26 and not in v27, and the same issue exists currently with 35.3.0.

**To Reproduce**

1. Create a new React app with TypeScript (if doing today, you want React 17 and not 18, since 18 isn't ready yet for Primer React)...
2. Install Primer React, verified using 35.3.0 but this was introduced in 27.0.0
3. Add any of the Details samples from the Primer React docs at https://primer.style/react/Details. In our case, I've added the 3rd example from the docs, the code of which is below
4. TypeScript error

```
ERROR in src/App.tsx:9:6
TS2769: No overload matches this call.
  Overload 1 of 2, '(props: { slot?: string | undefined; style?: CSSProperties | undefined; title?: string | undefined; ref?: ((instance: HTMLDetailsElement | null) => void) | RefObject<...> | null | undefined; ... 254 more ...; sx?: BetterSystemStyleObject | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type '{ children: (string | Element)[]; onToggle: (e: SyntheticEvent<HTMLElement, Event>) => void; open: boolean | undefined; ref: RefObject<HTMLElement>; }' is not assignable to type '{ slot?: string | undefined; style?: CSSProperties | undefined; title?: string | undefined; ref?: ((instance: HTMLDetailsElement | null) => void) | RefObject<...> | null | undefined; ... 254 more ...; sx?: BetterSystemStyleObject | undefined; }'.
      Types of property 'ref' are incompatible.
        Type 'RefObject<HTMLElement>' is not assignable to type '((instance: HTMLDetailsElement | null) => void) | RefObject<HTMLDetailsElement> | null | undefined'.
          Type 'RefObject<HTMLElement>' is not assignable to type 'RefObject<HTMLDetailsElement>'.
            Property 'open' is missing in type 'HTMLElement' but required in type 'HTMLDetailsElement'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<"details", any, SxProp, never, "details", "details">): ReactElement<StyledComponentPropsWithAs<"details", any, SxProp, never, "details", "details">, string | JSXElementConstructor<...>>', gave the following error.
    Type '{ children: (string | Element)[]; onToggle: (e: SyntheticEvent<HTMLElement, Event>) => void; open: boolean | undefined; ref: RefObject<HTMLElement>; }' is not assignable to type '{ slot?: string | undefined; style?: CSSProperties | undefined; title?: string | undefined; ref?: ((instance: HTMLDetailsElement | null) => void) | RefObject<...> | null | undefined; ... 254 more ...; sx?: BetterSystemStyleObject | undefined; }'.
      Types of property 'ref' are incompatible.
        Type 'RefObject<HTMLElement>' is not assignable to type '((instance: HTMLDetailsElement | null) => void) | RefObject<HTMLDetailsElement> | null | undefined'.
     7 |   const {getDetailsProps, setOpen} = useDetails({closeOnOutsideClick: true})
     8 |   return (
  >  9 |     <Details {...getDetailsProps()}>
       |      ^^^^^^^
    10 |       <Button as="summary">Delete item</Button>
    11 |       Are you sure?
    12 |       <Button variant="danger" onClick={() => setOpen(false)}>Yes I'm sure</Button>


```

**Expected behavior**

No TS error.

**Code from the docs**

Note, I've dropped the variant from the Button props so that this code will work on ancient Primer Components
as well as newer bits to confirm the regression.

```
const {getDetailsProps, setOpen} = useDetails({closeOnOutsideClick: true})
    return (
      <Details {...getDetailsProps()}>
        <Button as="summary">Delete item</Button>
        Are you sure?
        <Button onClick={() => setOpen(false)}>Yes I'm sure</Button>
      </Details>
    )
```

**Comment by jeffwilcox** [comment]
+ zip of the app sans `node_modules` if it helps

[sample1.zip](https://github.com/primer/react/files/8981759/sample1.zip)

**Comment by jeffwilcox** [comment]
p.s. our hack for now is `any` as always, `<Details {...getDetailsProps() as any}>`

**Comment by siddharthkp** [comment]
Hi! Sorry for taking forever to respond.

I was able to download the zip file you gave and reproduce the type error. I have added it to the team's inbox to work on a fix

**Comment by lesliecdubs** [comment]
Hi @jeffwilcox, is this still an issue blocking you from upgrading to the latest release of Primer React?

**Comment by jeffwilcox** [comment]
@lesliecdubs we've moved to the latest versions by using the `as any` workaround mentioned above... I'm not potentially offended by that as much as some other devs.

Blocking - no
Potentially frustrating to TypeScript + React devs wanting to use useDetails - yes

Maybe a doc note would be a sufficient fix for now.

```
 <Details {...getDetailsProps() as any}>
```

**Comment by lesliecdubs** [comment]
Thanks for the insight!

@siddharthkp as FR, what do you think about adding the suggested note to the docs this week, and then we could move this issue to the backlog for consideration of further improvements in the future?
