### ISSUE TITLE
Old version documentation

### ISSUE THREAD

**Issue by mpcen** [primer/react#2160]
I'm unable to find a link to documentation for older version (i.e - v26.x). Where can I find this?

**Comment by colebemis** [comment]
We don't have deployed documentation for old versions but you can use GitHub's tag feature to view documentation associated with specific releases. Example: Documentation for v26.0.0: https://github.com/primer/react/tree/v26.0.0/docs/content

**Comment by siddharthkp** [comment]
Hi! 

I tried to deploy a version of the docs from the link @colebemis shared: https://primer-6e3be6d13d-13348165.drafts.github.io

Hopefully this helps!

**Comment by rezrah** [comment]
@emilybrick - this may be relevant to your docs exploration / research?

**Comment by lesliecdubs** [comment]
It looks like we've provided an answer here so I'm going to go ahead and close this. @mpcen please reopen or let us know if the links provided don't help.
