### ISSUE TITLE
Cannot specify tabIndex on ActionList.LinkItem

### ISSUE THREAD

**Issue by jdrush89** [primer/react#2165]
**Describe the bug**
I am not able to specify a tabindex on an ActionList.LinkItem.  I would like the link item to be tabbable, but it seems like the focuszone handling focus within the list is overriding that.

**To Reproduce**
1. Go to https://primer.style/react/ActionMenu
2. Enter the following code to the first example:
```
<ActionMenu>
  <ActionMenu.Button>Menu</ActionMenu.Button>

  <ActionMenu.Overlay>
    <ActionList>
      <ActionList.Item onSelect={event => console.log('New file')}>New file</ActionList.Item>
      <ActionList.Item>Copy link</ActionList.Item>
      <ActionList.Item>Edit file</ActionList.Item>
      <ActionList.Divider />
      <ActionList.Item variant="danger">Delete file</ActionList.Item>
      <ActionList.LinkItem href="www.github.com" tabIndex={0}>Link</ActionList.LinkItem>
    </ActionList>
  </ActionMenu.Overlay>
</ActionMenu>
```
3. Open the Menu and press 'tab'

**Expected behavior**
The Link should be reachable with tab instead of having to use the down arrows.  The main use case I have for this currently is in the ref selector in the code tab of github.  There can be thousands of refs in the menu when it is opened, and at the bottom is a link to 'view all' that is very difficult to reach for keyboard users. 

**Screenshots**
![image](https://user-images.githubusercontent.com/955442/176931479-18f4fc86-f0dc-4f24-870e-3663190dcd74.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 103.0.5060.66 (Official Build) (32-bit)

**Comment by lesliecdubs** [comment]
Hi @jdrush89 👋 Did Owen's comment above provide a solution you are able to run with?
