### ISSUE TITLE
Dark mode `:hover` in `ActionList` component is not configurable

### ISSUE THREAD

**Issue by Ebonsignori** [primer/react#2193]
Per https://github.com/github/docs-engineering/issues/2007 the dark mode `ActionList` `:hover` is unreadable, see [this screenshot](https://twitter.com/lustcoder/status/1549383921946828803).  

We can override the `:hover` for the `ActionList.Item` in our codebase, but have to use `!important` to have the styles apply. 

It would be ideal if we could configure these lines to be optional or to change the color to something that works better:
https://github.com/primer/react/blob/40da598e8d41b688eba53f4c594bff66b269f5f4/src/ActionList/Item.tsx#L170-L174

**Comment by siddharthkp** [comment]
Hi Evan!

I noticed that docs uses an `a` tag inside ActionList, which gets the global link color which ActionList doesn't optimise for right now (links in ActionList do not have accent color)

How do you feel about using [ActionList.Link](https://primer.style/react/ActionList#with-links) or even better [NavList](https://primer.style/react/NavList) (which supports [nesting](https://primer.style/react/NavList#with-sub-items)), would that be a good fit for this use case?

Example of NavList in different github themes: https://primer.style/react/storybook/?path=/story/composite-components-navlist--with-sub-items&globals=colorScheme:all

---

Screenshot from docs:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/1863771/183104803-4cde7a29-4fc5-4ff4-b05a-e5cb13829e59.png"> 

Screenshot of ActionList with links:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/1863771/183105006-c93adb3f-b451-428b-9852-2d9f92c255c1.png">

**Comment by lesliecdubs** [comment]
👋🏻 Hi @Ebonsignori, did Sid's [answer above](https://github.com/primer/react/issues/2193#issuecomment-1206563871) help? Let us know if we be of further assistance.

**Comment by gracepark** [comment]
Hi @lesliecdubs and @siddharthkp! I was working with @Ebonsignori and currently he's OOO, so I can take this one. `NavList` is awesome and works great! Thanks for the heads up. We'll use that!

**Comment by lesliecdubs** [comment]
Awesome, thanks for confirming @gracepark! I'm going to go ahead and close this issue, but please don't hesitate to reopen it or visit us in #primer if further questions come up.
