### ISSUE TITLE
ThemeProviderProps does not accept children.

### ISSUE THREAD

**Issue by aspnxdd** [primer/react#2194]
When using Typescript in a React App, the ThemeProvider FC does not support children to be passed.
![image](https://user-images.githubusercontent.com/43625217/181254603-727da27a-ef5f-4648-8234-c8810fa342a3.png)

A custom workaround I made is:
```ts
const CustomThemeProvider: React.FC<
  ThemeProviderProps & { children: ReactNode }
> = ({ children, ...props }) => {
  return <ThemeProvider {...props}>{children}</ThemeProvider>;
};
```
But it would be handy to include the children in the ThemeProviderProps:
```ts
export type ThemeProviderProps = {
  theme?: Theme
  colorMode?: ColorModeWithAuto
  dayScheme?: string
  nightScheme?: string
  preventSSRMismatch?: boolean
  children?: React.ReactNode
}
```

**Comment by mattcosta7** [comment]
this likely needs a more complete fix as described in - https://github.com/primer/react/issues/2065

the issue if react 18 types, which primer as a whole is not yet compatible with
