### ISSUE TITLE
Unable to install primer react 

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [primer/react#2202]
**Error while installing primer react**
I am installing primer react with react@18.2.0 with @primer/react@35.5.0 but facing following Errors
![image](https://user-images.githubusercontent.com/77089227/181682948-0d87aed1-ffe1-40b6-8105-c2a0f9f57c1f.png)

**To Reproduce**
1. Create react app
2. `npm install @primer/react` installing  primer react

**Expected behavior**
Primer react should be installed without any conflicts

**Screenshots**
![image](https://user-images.githubusercontent.com/77089227/181682948-0d87aed1-ffe1-40b6-8105-c2a0f9f57c1f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Browser chrome
 - Version Version 103.0.5060.134 (Official Build) (64-bit)

**Comment by SGI-CAPP-AT2** [comment]
@lesliecdubs can I solve this with any solution ?

**Comment by lesliecdubs** [comment]
👋🏻 Hi @SGI-CAPP-AT2! Thanks for letting us know about this. We don't support React 18 yet but are planning to look into it soon. I'd encourage you to watch the release notes to see when it ships.

I'm going to go ahead and close this issue as we have an issue internally where we're tracking progress on this.

Thanks!
