### ISSUE TITLE
ActionMenu: Page scrolls when moving focus to first item

### ISSUE THREAD

**Issue by siddharthkp** [primer/react#2250]
Steps to reproduce:

1. Open an ActionMenu with click (not keyboard). Focus will stay on the anchor.
2. Press ArrowDown to move focus from anchor to first item

This also fires page scroll event

In docs,

https://user-images.githubusercontent.com/6636360/185539825-0ec1bf4a-e307-4d1a-9c3d-84ee9b117a57.mov

In memex,

https://user-images.githubusercontent.com/1863771/185975424-d5e3bfc0-48ea-436c-b4e4-c24df9f6776c.mov

#### Impact:

Low, tiny annoyance for users that use both mouse and keyboard in the menu

#### Solution:

We might need to prevent the scroll event when moving focus for the first time in [useMoveFocusToMenuItem](https://github.com/primer/react/blob/main/src/hooks/useMenuKeyboardNavigation.ts#L86)

**Comment by Shubhambawner** [comment]
Hello @siddharthkp @colebemis ,
may I work on this issue ?

**Comment by siddharthkp** [comment]
Sure, go for it! :)

**Comment by Shubhambawner** [comment]
Hello, can you please help me in setting p the project locally?
I forked repo, then cloned the fork locally, and then ran the script `npm run setup` as described in [here](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md)
attaching the screenshot here:
![image](https://user-images.githubusercontent.com/73178780/186633813-e1ae1ad8-19e5-4cdd-9df2-fef412f7412d.png)

I cleaned the whole repo and re cloned it again, but the same thing repeats, if possible, please provide any setup guidelines for locally setting up the repo.

**Comment by siddharthkp** [comment]
Hi! 

`script/setup` is a bash script. You have to make sure the terminal you are using on windows supports bash. 

I'm not on windows so I'm not able to recommend you one that's good. [microsoft/windows terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) might be a good one?

**Comment by Shubhambawner** [comment]
I am using terminal that comes integrated with VS Code IDE

**Comment by siddharthkp** [comment]
That's a shame, are you able to run the commands inside the script on their own?


```
# Install dependencies
npm install

# Build
npm run build

# Install docs dependencies
pushd docs
npm install --legacy-peer-deps
popd
```

**Comment by Shubhambawner** [comment]
I tried that too at the very beginning, but after running each script manually the start command gives error:
![image](https://user-images.githubusercontent.com/73178780/186745560-c96e2c00-9a88-49db-b989-1bd3d6e9e8a0.png)

**Comment by siddharthkp** [comment]
Ah right, same story after installation as well. We haven't tested this on windows at all to know all the breaking points, so I don't know how to help you here 😢 

@colebemis any ideas?

**Comment by Shubhambawner** [comment]
I m really not able to figure out the setup for windows, shall I put it on [discussion ](https://github.com/primer/react/discussions)?

**Comment by siddharthkp** [comment]
> I m really not able to figure out the setup for windows, shall we put it on discussion

Yep, good call!

> Does the development of all repositories at [primer](https://github.com/primer) completely happen in Linux/Unix environment ?

It does. I know some folks use codespaces instead of a local clone, that should work for you as well

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1863771/187156786-aba83a1a-4ea4-4671-8a4f-ac0386c911a6.png">

**Comment by Haikyuu77** [comment]
hey @siddharthkp, can I work on this issue?

**Comment by tallys** [comment]
@lesliecdubs is this still in progress somewhere? No one is assigned, but potentially this is in progress from an external contributor. Do you have context?

**Comment by lesliecdubs** [comment]
@tallys as far as I'm aware, this is one isn't in progress. If anyone who has commented on this issue is actively working on this, please let us know!

**Comment by Shubhambawner** [comment]
I had checked this issue after recent commits in around end of 2022, it seemed that issue no longer exists as mentioned above, check it once

**Comment by lesliecdubs** [comment]
Thanks for weighing in, @Shubhambawner!

@siddharthkp can you please re-test this bug report in production, and close this out if the issue has been resolved?

**Comment by radglob** [comment]
Just tested this against production. Doesn't seem to be an issue anymore.


https://user-images.githubusercontent.com/1825422/226651950-5a26ea3d-9407-4efd-83d4-0d7c0307a3b0.mov

**Comment by lesliecdubs** [comment]
Thanks @radglob! I'm going to close this as resolved, but please feel free to comment back if anyone notices this bug again.
