### ISSUE TITLE
[RFE] stop consuming '@radix-ui/react-polymorphic' as it is deprecated upstream

### ISSUE THREAD

**Issue by AntonioMeireles** [primer/react#2256]
Hey all, 

per https://github.com/radix-ui/primitives/pull/835 which went _live_ in [September 7, 2021](https://www.radix-ui.com/docs/primitives/overview/releases#september-7-2021) use of `@radix-ui/react-polymorphic'` become deprecated, with the new prefered syntax being described [here](https://www.radix-ui.com/docs/primitives/overview/styling#changing-the-rendered-element). 

Finally, early this year, the whole `@radix-ui/react-polymorphic` package was sunsetted per https://github.com/radix-ui/primitives/pull/1331. 

This is relevant because `@prime/react` is now supposed to properly behave over **react-18** and the latest  shipping  `@radix-ui/react-polymorphic` being consumed isn't _exactly_ aware of it...  the noise bellow is what what made me dig a bit on this...

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @radix-ui/react-polymorphic@0.0.14
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   99 more (@clerk/clerk-react, @primer/octicons-react, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8 || ^17.0" from @radix-ui/react-polymorphic@0.0.14
npm WARN node_modules/@radix-ui/react-polymorphic
npm WARN   @radix-ui/react-polymorphic@"^0.0.14" from @primer/react@35.7.0
npm WARN   node_modules/@primer/react
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.8 || ^17.0" from @radix-ui/react-polymorphic@0.0.14
npm WARN   node_modules/@radix-ui/react-polymorphic
npm WARN     @radix-ui/react-polymorphic@"^0.0.14" from @primer/react@35.7.0
npm WARN     node_modules/@primer/react
```

So, in the name of keeping things clean, and up to date it may make sense, IMHO, to keep with the times

All the Best, (and keep the great work!)

António

**Comment by colebemis** [comment]
Thanks for letting us know! I'll add this to our project board

**Comment by siddharthkp** [comment]
@colebemis 

Should we bring in the types from [react-polymorphic](https://unpkg.com/browse/@radix-ui/react-polymorphic@0.0.14/dist/index.d.ts) in this repo?

**Comment by AntonioMeireles** [comment]
@joshblack, et all 

sorry the bluntness, but the approach that was taken here **IMHO** is absolutelly bonkers, specially given what  one would expect from GitHub, and doesn't bode well for any sane mind (outside GitHub's corporate scope) to bet a dime, long term, in this library. 

let's see - on one side @radix-ui/react-polymorphic was deprecated and later sunseted by its upstream because they found a much simpler/saner solution which overall has way lower maintenance overhead , on the other side - this library side - the 'solution' was instead of keeping being close to core deps evolving best practices and fix things to just fork and inline something that was deprecated and sunsetted everywhere else in the solar system. 

It's a detail, a minor one perhaps, but for someone that was evaluating the feasability of using, and ence betting long term, on this for some large internal projects it was the nail on the coffin. :/

Best Regards,
