### ISSUE TITLE
SegmentedButton - cannot specify size of the button

### ISSUE THREAD

**Issue by milemons** [primer/react#2267]
**Describe the bug**
I'd like to be able to specify the SegmentedControl.Button as a `small` size as I can with other buttons
`size` is not a supported prop of `SegmentedControl.Button` - so I tried setting the fontSize through sx prop and it still has no effect. 

**To Reproduce**
1. Go to https://primer.style/react/SegmentedControl
2. Note that `size` is not a supported prop for the Button
3. Add `sx={{fontSize: 0}}` to one of the buttons
4. Notice that nothing changes

**Expected behavior**
I expect some way to customize the size of these buttons

**Screenshots**
<img width="996" alt="image" src="https://user-images.githubusercontent.com/58820510/186496285-61833815-9dda-4968-af34-be38fc396db3.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 104

**Comment by mperrotti** [comment]
@milemons - we intentionally shipped SegmentedControl with 1 size to start, and agreed we could add more if the use case came up.

Could you tell us more about your use-case for a smaller SegmentedControl size?

---

The `sx` prop not changing styles is a bug. From a quick glance, I'm not sure what's causing that bug and I think we'll need a little more time to triage.

**Comment by lesliecdubs** [comment]
Hi there! I think there's two concerns in this issue; for our own tracking purposes, I'm going to split them out so we can better address them directly. Thanks!

**Comment by milemons** [comment]
Hello @mperrotti! We are trying to use segmented button on a page to toggle between Code/Blame views. The designs currently have all buttons specified to size small since large buttons would take up too much space. Feel free to poke at the designs [on the figma](https://www.figma.com/proto/1vWZ5yWmuaCkhoNTg1VSFa/branch/ouIw03ODgxE2M0KhHWec4G/Code-Nav-%26-Repo-Overview?page-id=1057%3A110372&node-id=1471%3A67132&viewport=19193%2C1477%2C1.06&scaling=min-zoom&starting-point-node-id=1485%3A89440&show-proto-sidebar=1)

**Comment by mperrotti** [comment]
Thanks @milemons and @colinwm, and sorry for the delayed response. I'm planning to add size options this week. I'll post an update when the PR is up.

**Comment by mperrotti** [comment]
A PR has been opened: https://github.com/primer/react/pull/2347

**Comment by mperrotti** [comment]
The PR has been merged and the `size` prop will be available on `SegmentedControl` in the next `@primer/react` release.
