### ISSUE TITLE
SegmentedButton -  sx props do not apply

### ISSUE THREAD

**Issue by lesliecdubs** [primer/react#2286]
**Describe the bug**
As originally reported in https://github.com/primer/react/issues/2267:

I'd like to be able to specify the SegmentedControl.Button as a `small` size as I can with other buttons
`size` is not a supported prop of `SegmentedControl.Button` - so I tried setting the fontSize through sx prop and it still has no effect. 

**To Reproduce**
1. Go to https://primer.style/react/SegmentedControl
2. Note that `size` is not a supported prop for the Button
3. Add `sx={{fontSize: 0}}` to one of the buttons
4. Notice that nothing changes

**Expected behavior**
`sx` prop should apply to SegmentedControl.Button.

**Screenshots**
<img width="996" alt="image" src="https://user-images.githubusercontent.com/58820510/186496285-61833815-9dda-4968-af34-be38fc396db3.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 104

**Comment by mperrotti** [comment]
Planning to work on this bug this week.

**Comment by lesliecdubs** [comment]
Thanks for the update @mperrotti! I moved this into ["Up Next: Design" on the Primer teams backlog](https://github.com/orgs/github/projects/4503/views/10?filterQuery=label%3Areact+segmentedbutton) to match the status. I'd definitely focus on #2286 first, unless you'd rather the team handle this new size through the `sx` prop in the longer term.

**Comment by mperrotti** [comment]
@lesliecdubs - I'd rather the team use the `size` prop. A PR has been merged to support the `size` prop: https://github.com/primer/react/pull/2347
