### ISSUE TITLE
Is there any option for hiding the breadcrumb on deep nesting?

### ISSUE THREAD

**Issue by sauravlikhar** [primer/react#2306]
In our use case we will have many items in the breadcrumbs. We want to hide the middle ones when the total breadcrumbs length exceeds the container width.
In more detail - 
Currently breadcrumbs are shown like this -
This is the breadcrumb item1 / This is the breadcrumb item2 / This is the breadcrumb item3 / This is the breadcrumb item4 / This is the breadcrumb item5

We want the middle ones to hide and should be shown as dots like -
This is the breadcrumb item1 / ... / This is the breadcrumb item4 / This is the breadcrumb item5 

The item 2 and 3 should be visible in a small panel when we click on the dots. 
Please have a look at this video at 5:50 for more clarity- https://www.youtube.com/watch?v=hfaveF17c7g

Also we want the item names to be truncated based on the width of the screen. 

Currently it is like this - 
This is the breadcrumb item1 with long name / This is the breadcrumb item2 with long name / This is the breadcrumb item3 with long name / This is the breadcrumb item4 with long name 

It should be like this - 
This is the breadcrumb item 1... / ... / This is the breadcrumb item3... / This is the breadcrumb item4 with long name

**Comment by sauravlikhar** [comment]
Is there any update on this question? Our product needs this functionality.

**Comment by lesliecdubs** [comment]
Hello @sauravlikhar, thanks for your patience with our response! I don't believe the Primer React Breadcrumbs currently include this functionality.

Perhaps the `Truncate` component would be useful in building out that functionality in your app: https://primer.style/react/Truncate
