### ISSUE TITLE
TextInput broke

### ISSUE THREAD

**Issue by Flaviano-Rodrigues** [primer/react#2381]
### Description

I was having a problem with TextInput. Whenever I placed an icon on it, for example using the prop "loading={true}" the input would break as shown in the screenshot below:

![screenshot](https://user-images.githubusercontent.com/112655909/192633822-df15495a-4851-44a0-b0e8-7719ba180992.png)

But if you put the prop "sx" in the input like "sx={{ flexWrap: 'nowrap' }}", the input doesn't break.

![screenshot_soluction](https://user-images.githubusercontent.com/112655909/192634007-73daabc3-2725-4c9c-a76b-de0114c19d74.png)

### Steps to reproduce

1. Insert this in your code:
```javascript

<FormControl>
  <FormControl.Label>Name</FormControl.Label>
  <TextInput  loading={true} />
</FormControl>
```
2. See error
3. Add sx prop in `<TextInput />` component like this:
```javascript
<TextInput sx={{ flexWrap: 'nowrap' }} loading={true} />
```
5. See problem solved

### Version

v35.10.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi!

I am trying to reproduce the bug with the code you provided but wasn't able to. 🤔 

Can you provide a sandbox with a reproduction? Here's a starting point: https://codesandbox.io/s/kind-driscoll-w7wfrb?file=/src/App.tsx:209-338

Thank you!

**Comment by Flaviano-Rodrigues** [comment]
> Hi!
> 
> I am trying to reproduce the bug with the code you provided but wasn't able to. 🤔
> 
> Can you provide a sandbox with a reproduction? Here's a starting point: https://codesandbox.io/s/kind-driscoll-w7wfrb?file=/src/App.tsx:209-338
> 
> Thank you!

Hi!

In Fact, in your sandbox it worked normally. I will check here and analyze what may be happening and I will return with the answer.

**Comment by Flaviano-Rodrigues** [comment]
I found the problem. In my styles.css I put it so that all elements have "flex-wrap: wrap;". Then the TextInput breaks. As I've been using this for a while and I've never had a problem I wouldn't imagine that was it. Sorry for the mistake.

**Comment by siddharthkp** [comment]
No worries, thanks for reporting back :)
