### ISSUE TITLE
`MarkdownEditor` should allow lazy-loading suggestions

### ISSUE THREAD

**Issue by iansan5653** [primer/react#2422]
In order to reduce API load and improve time-to-render, we want to lazy-load suggestions in Projects by waiting until the suggestions are actually needed before making the API request (see https://github.com/github/memex/issues/12396). The `MarkdownEditor` doesn't support this at the moment, so it would like require changing the props to accept functions instead of (or in addition to) the suggestion arrays.

I am already working on this; just opening an issue to track over here.

**Comment by japf** [comment]
cc @anleac as we discussed this topic today while working on https://github.com/github/issues/issues/3377
