### ISSUE TITLE
Select with placeholder gives console warning

### ISSUE THREAD

**Issue by ArthurClemens** [primer/react#2458]
### Description

`Select` with prop `placeholder` results in a warning:
```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>
```

### Steps to reproduce

- [CodeSandbox with problem](https://codesandbox.io/s/primer-react-select-warning-tbz3td?file=/src/App.tsx)
- [CodeSandbox with solution direction](https://codesandbox.io/s/primer-react-select-warning-solution-hf21gu?file=/src/App.tsx)

### Version

v35.12.0

### Browser

Chrome

**Comment by green6erry** [comment]
It looks like this was resolved with PR https://github.com/primer/react/pull/2511 👍
