### ISSUE TITLE
Draft components occurs ESM `import` error 

### ISSUE THREAD

**Issue by archlabx** [primer/react#2469]
### Description

```./node_modules/@primer/react/lib-esm/drafts/MarkdownEditor/_FormattingTools.js:17:38
Module not found: ESM packages (@github/markdown-toolbar-element) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

Import trace for requested module:
./node_modules/@primer/react/lib-esm/drafts/MarkdownEditor/MarkdownEditor.js
./node_modules/@primer/react/lib-esm/drafts/MarkdownEditor/index.js
./node_modules/@primer/react/lib-esm/drafts/index.js```

### Steps to reproduce

1. Just import any draft components within `Next.js` with TS.

### Version

35.12.0

### Browser

_No response_

**Comment by joshblack** [comment]
Hi there @archlabx! 👋 

Thanks for taking the time to make this issue 🙏 Unfortunately, I'm not able to replicate the issue that you're running into. Could you share additional steps to help reproduce?

To try and reproduce, I created a Next.js app and imported both `TreeView` and `MarkdownEditor` from `@primer/react/drafts` but couldn't run into the `Module note found` error that was shared.

**Comment by joshblack** [comment]
Hi there @archlabx! 👋 

Going to close this out due to inactivity. Let me know if you're still running into this issue and I'd be happy to take a look into this!
