### ISSUE TITLE
Checkbox no longer has padding styles

### ISSUE THREAD

**Issue by joshblack** [primer/react#2500]
### Description

The `Checkbox` component no longer has padding between the `<input>` and the `<label>`. This was a regression in v35.12.0.

Expected behavior from 35.11.0: https://primer-7045de1bbe-13348165.drafts.github.io/Checkbox

![image](https://user-images.githubusercontent.com/3901764/199037193-801ccb85-3ae7-4da3-86f9-9df40b76feaa.png)

Current behavior from latest:

![image](https://user-images.githubusercontent.com/3901764/199037265-46cdf99a-dcb6-4520-bf8d-273494a8eb51.png)

### Steps to reproduce

https://primer.style/react/Checkbox

### Version

v35.13.0

**Comment by siddharthkp** [comment]
the one week we didn't have chromatic 🤦

**Comment by ayobamiseun** [comment]
can i fix this issue
