### ISSUE TITLE
TreeView not scrolling properly

### ISSUE THREAD

**Issue by jdrush89** [primer/react#2501]
### Description

The Treeview seems to scroll as keyboard focus moves around only if list items are lined up with the top/bottom of the viewport. If the item is half in and half out of the viewport, the scroll stops happening.

### Steps to reproduce

Go to https://jdrush89-primer-upgrade-and-file-tree.review-lab.github.com/microsoft/TypeScript/tree/main/src and try navigating through the tree with the arrow keys

https://user-images.githubusercontent.com/955442/199053206-344596df-0628-4b4f-89ed-86c33c029c1d.mov

### Version

v35.13

### Browser

Chrome

**Comment by colebemis** [comment]
This should be fixed by upgrading in `@primer/behaviors` v1.3+

**Comment by lesliecdubs** [comment]
@jdrush89 thanks for reporting! I'm going to close this out as the solution is upgrading the behaviors package, but please reopen or comment back if you need more support.
