### ISSUE TITLE
Incorrect types for IconButton

### ISSUE THREAD

**Issue by colebemis** [primer/react#2519]
### Description

IconButton incorrectly allows a `leadingIcon` prop to be passed to the component. 

```jsx
// IconButton doesn't accept a `leadingIcon` prop.
// This should cause a TypeScript error but it doesn't.
// Instead, it causes a runtime error.
<IconButton leadingIcon={PencilIcon} />
```

Orginally reported by @milemons in [this Slack thread](https://github.slack.com/archives/C0357UQ03KN/p1667399595359759?thread_ts=1667330297.439599&cid=C0357UQ03KN)

### Steps to reproduce

See this StackBlitz for a reproduction of the bug: https://stackblitz.com/edit/react-ts-nyunix?file=App.tsx

### Version

v35.14.0

**Comment by broccolinisoup** [comment]
Thanks to @mattcosta7 for [the PR](https://github.com/primer/react/pull/2677)! I am moving this issue to `In code review` column and unassigning myself. Let me know if you have any issues with it!

**Comment by broccolinisoup** [comment]
Ah not at all! @mattcosta7 I really appreciate the fixes! 🙇🏼‍♀️  I just didn't have much time to look at them
