### ISSUE TITLE
Remove `@whitespace/storybook-addon-html` from storybook

### ISSUE THREAD

**Issue by joshblack** [primer/react#2582]
This issue tracks removing `@whitespace/storybook-addon-html` from storybook as it does not support React 18.

It seemed appropriate to remove this as a result, however if there is a use-case for this let me know! Any alternatives would be very much so appreciated 🙏

**Comment by rezrah** [comment]
👋 @joshblack this was added to help the accessibility team view rendered output more easily in Storybook in a11y reviews. Unsure how frequently it's used, but worth checking in with @alliethu about it.

**Comment by langermank** [comment]
I agree this plugin is useful for accessibility review and also general development, but I don't think it should be a blocker. Perhaps we could make our own addon to accomplish this 😄 I bet it would be simple? (famous last words)

**Comment by joshblack** [comment]
Thanks so much for the context @rezrah @langermank! I appreciate it 🙏 

Do either of you know of an alternative by any chance? I'll also keep an eye on the repo as it seems like they have been making changes recently. It seems like right now they have react-dom@18 as a peer dep but not react 🤔 

Looking forward, worse-can we can definitely bring it over as a custom add-on 👍

**Comment by lesliecdubs** [comment]
We reviewed at the PRC planning meeting today. No one had ideas for an alternate addon for this behavior. +1 to adding it as a custom add-on for now if the accessibility team requires it for their review.
