### ISSUE TITLE
MarkdownEditor Preview renders [object Object]

### ISSUE THREAD

**Issue by SaadBazaz** [primer/react#2601]
### Description

There's not much in the docs to explain how the onRenderPreview works:
 
<img width="724" alt="Screenshot 2022-11-21 at 6 12 17 PM" src="https://user-images.githubusercontent.com/51885228/203063971-429f15b6-da8e-4676-8988-7c5f7771d725.png">

I assumed that the ```renderMarkdown``` function has to 'parse' the markdown and return html. 

I tried: 
```
const renderMarkdown = async (markdown) => {
    return <ReactMarkdown children={markdown} />
}
```
and
```
const renderMarkdown = async (markdown) => {
    return  <MarkdownViewer dangerousRenderedHTML={{__html: markdown}} />
}
```

but both of them return [object Object]:

<img width="661" alt="Screenshot 2022-11-21 at 6 17 45 PM" src="https://user-images.githubusercontent.com/51885228/203064996-e84088c8-7bac-4735-b86f-5e4886566c39.png">

What am I doing wrong?

### Steps to reproduce

1. Install the latest Primer React
2. Install the latest ReactMarkdown
3. Copy and paste the [minimal MarkdownEditor example](https://primer.style/react/drafts/MarkdownEditor#minimal-example)
4. Use ReactMarkdown inside the renderMarkdown function

### Version

v35.14.2

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi!

`onRenderPreview` expects a return of promise that resolves to html string, while  `ReactMarkdown` returns a React component (which gets printed as `[Object object]`)

An example of this would be using unified + remark (the libraries behind react-markdown)

Docs: https://unifiedjs.com/learn/recipe/remark-html/#how-to-turn-markdown-into-html
Sandbox: https://codesandbox.io/s/laughing-tom-nslr56?file=/src/App.tsx

**Comment by siddharthkp** [comment]
Closing this issue as answered, but feel free to comment back if this doesn't help and I'll open it again :)

**Comment by SaadBazaz** [comment]
Thanks @siddharthkp . I'll test this out and let you know if it works.

**Comment by SaadBazaz** [comment]
@siddharthkp Worked with unified!
