### ISSUE TITLE
[Component Request] File Explorer

### ISSUE THREAD

**Issue by SaadBazaz** [primer/react#2602]
A GitHub-like File Explorer.

<img width="850" alt="Screenshot 2022-11-21 at 6 43 56 PM" src="https://user-images.githubusercontent.com/51885228/203070321-6ed1698d-ddcb-4990-8c4b-b73c10ca8d95.png">

Possible Inputs:
- File Directory Structure, with a fixed data type (type: "dir" or type: "file", and other similar controls).
- List item controls
- Action bar on top

**Comment by lesliecdubs** [comment]
Hi @SaadBazaz, thanks for requesting this component! Could you provide any more detail on the use case you have for this pattern as a standalone component?

We are working on the design for a new `DataTable` pattern that could potentially serve a similar purpose, although it is meant more to display tabular data than list data.

cc @justinbyo

**Comment by SaadBazaz** [comment]
> Hi @SaadBazaz, thanks for requesting this component! Could you provide any more detail on the use case you have for this pattern as a standalone component?
> 
> We are working on the design for a new `DataTable` pattern that could potentially serve a similar purpose, although it is meant more to display tabular data than list data.
> 
> cc @justinbyo 

Building a watered-down file explorer for git repos. Very similar to Github Web. 

Ik it'll just be an abstraction over ActionList, etc, but it'd be cool to have. 

Data Table might be better tbh.

**Comment by lesliecdubs** [comment]
Thanks for the context! We'll update you here if we prioritize this. 

In the meantime, keep your eye on the Primer React release notes; `DataTable` is likely coming in the first half of the new year.
