### ISSUE TITLE
[Component Request] File Upload Input

### ISSUE THREAD

**Issue by SaadBazaz** [primer/react#2605]
A file upload input, like the browser's default one, but more... GitHub. :)

Or, better yet, a generic <Input> component which takes `type="file"`, `type="checkbox"`, etc. Haven't come across that yet.

**Comment by SaadBazaz** [comment]
> > Haven't come across that yet.
> 
> Are you looking for https://github.com/github/file-attachment-element?

Thanks for sharing!
It's nice. 

Would prefer if it was part of Primer. And more importantly, Primer React :D

**Comment by lesliecdubs** [comment]
Noted, @SaadBazaz! We'll keep this on our radar, although know that we don't have near-term plans to build a React file attachment component. cc @justinbyo

**Comment by Mayuresh0072** [comment]
@lesliecdubs Hello, I want to work and contribute on this issue , Please assign me this issue. Thanks.

**Comment by justinbyo** [comment]
Hey @Mayuresh0072 thanks for offering. Primer hasn't designed the component or its API yet, so we're not prepared to actually implement it yet. We'll keep you updated when we're prepared to move forward on this.
