### ISSUE TITLE
Spinner does not support dark mode

### ISSUE THREAD

**Issue by samuela** [primer/react#2611]
### Description

`Spinner` does not seem to have any support for dark mode AFAICT. Here's what it looks like:

<img width="143" alt="Screen Shot 2022-11-23 at 2 58 29 PM" src="https://user-images.githubusercontent.com/226872/203660096-886c828b-b962-49ab-85f2-19602fc82ec6.png">

### Steps to reproduce

```txc
<ThemeProvider colorMode="dark" nightScheme="dark_dimmed">
  <Spinner />
</ThemeProvider>
```

### Version

35.14.2

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi! 

Spinner gets it's foreground colors from the parent, so along with `ThemeProvider`, you would need to wrap your app in `BaseStyles` as well

```jsx
import { ThemeProvider, BaseStyles, Spinner } from '@primer/react'

<ThemeProvider colorMode="dark" nightScheme="dark_dimmed">
  <BaseStyles>
   
    <Spinner />
   
  </BaseStyles>
</ThemeProvider>
```

Sandbox: https://codesandbox.io/s/magical-franklin-41yrk7?file=/src/App.tsx:484-519

**Comment by siddharthkp** [comment]
Closing this issue as answered, but feel free to comment back if this doesn't help and I'll open it again :)

**Comment by samuela** [comment]
Thanks so much @siddharthkp ! What does `BaseStyles` do exactly? Is there documentation for it anywhere? I was only aware of the existence of `ThemeProvider`

**Comment by siddharthkp** [comment]
BaseStyles are responsible for injecting global styles for primer/github

Reference: https://primer.style/react/getting-started#basestyles
Source: https://github.com/primer/react/blob/main/src/BaseStyles.tsx

(It's opt-in because some applications at github inject globals throught a different library)

**Comment by samuela** [comment]
Ahhh, got it! Ok, thank you so much @siddharthkp !!
