### ISSUE TITLE
When SSR, useLayoutEffect warning in UnderlineNav v2

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [primer/react#2617]
### Description

When entering a page with SSR in the nextjs project, the useLayoutEffect warning.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at /Users/b6pzeusbc54tvhw5jgpyw8pwz2x6gs/projects/nextjs12-sample/node_modules/@primer/react/lib/UnderlineNav2/UnderlineNavItem.js:25:7
```

### Steps to reproduce

1. Run the nextjs development server.
2. Refresh the browser to enter the page via SSR.
3. Check the development server log (not the browser console log).

### Version

35.14.2

**Comment by broccolinisoup** [comment]
👋🏼  @b6pzeusbc54tvhw5jgpyw8pwz2x6gs Thanks for reporting this issue! [This](https://github.com/primer/react/pull/2625) should fix the warning and please see the PR description about the behaviour as well.
