### ISSUE TITLE
[React 18] ButtonClose type declarations are invalid

### ISSUE THREAD

**Issue by dgreif** [primer/react#2621]
### Description

When loading the PRC type declarations in a React 18 environment, there is a type error in the `node_modules/@primer/react/lib-esm/deprecated/Button/ButtonClose.d.ts` file:

```
error TS2344: Type '"theme" | "key" | "sx" | keyof ButtonHTMLAttributes<HTMLButtonElement>' does not satisfy the constraint '"children" | "name" | "ref" | "type" | "hidden" | "theme" | "form" | "slot" | "style" | "title" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 254 more ... | "formTarget"'.
  Type '"nonce"' is not assignable to type '"children" | "name" | "ref" | "type" | "hidden" | "theme" | "form" | "slot" | "style" | "title" | "key" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 254 more ... | "formTarget"'.

276 }, "theme" | "key" | "sx" | keyof React.ButtonHTMLAttributes<HTMLButtonElement>> & React.RefAttributes<HTMLButtonElement>>;
```

Looking at this button compared to the other button types (which don't have issues), I think the main difference is that this one is set up to handle forward refs. Not positive what the fix is here, but I can work around it for now with `skipLibChecks`

Relates to #2536 

### Steps to reproduce

1. Run `tsc` in a project using PRC + React 18 types
2. See type error coming from ButtonClose types

### Version

v35.14.2

**Comment by lesliecdubs** [comment]
@joshblack let's add this into #2536, what do you say?
