### ISSUE TITLE
Autocomplete.Overlay issue with TextInputWithTokens

### ISSUE THREAD

**Issue by 72lions** [primer/react#2626]
### Description

I'm using two `Autocomplete` components with the`<Input as={TextInputWithTokens}/>` one below the other. When there are any tokens in any of the inputs, then the `X`s on each token slip through the overlay of the other `Autocomplete`
<img width="320" alt="Screenshot 2022-11-29 at 14 04 53" src="https://user-images.githubusercontent.com/520279/204538074-34401213-6445-44eb-ac16-04dd6efa90ee.png">
<img width="322" alt="Screenshot 2022-11-29 at 14 05 11" src="https://user-images.githubusercontent.com/520279/204538079-167bb9c0-207a-40ab-a3f1-6cc560f389d6.png">

### Steps to reproduce

* Create two `Autocomplete` components 
* Make sure that both have `<Input as={TextInputWithTokens}/>`
* Place them in a way that when the autocomplete overlay opens will overlap with the other `Autocomplete` component

### Version

35.14.2

### Browser

Chrome

**Comment by 72lions** [comment]
I've confirmed that the problem is that the `RemoveTokenButton` style has `z-index:1`. When I remove it then there is no overlap problem anymore.

**Comment by mperrotti** [comment]
Sorry about changing the assignees. I needed to record my screen to demo selection behavior for something unrelated.

**Comment by mperrotti** [comment]
I tested this in Storybook and could not reproduce the problem.

However it looks like that `zIndex` isn't actually doing anything, so I'm just going to remove it.
