### ISSUE TITLE
Add secondary save action to the `MarkdownEditor` component

### ISSUE THREAD

**Issue by japf** [primer/react#2670]
My team is interested in having a secondary save action when using the `MarkdownEditor` component. This secondary action would be trigger via the `Cmd+Shift+Enter` keyboard shortcut.

Today there is no easy way to achieve this because the underlying keyboard event isn't exposed (see [here](https://github.com/primer/react/blob/d995bb8485fa1dfd0a3637b4851c5ac539b8416d/src/drafts/MarkdownEditor/MarkdownEditor.tsx?q=repo%3Aprimer%2Freact+markdowneditor#L298))

After discussing with @iansan5653 it looks like there are a few options for that:

> I think there's a few decent options here for the Primer component:
> 1. Add an `onSecondaryAction` callback that is called on <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd>
> 2. Remove the `onPrimaryAction` callback altogether and let the parent handle those events by allowing them to bubble
> 3. Leave the props as-is but explicitly check for `!e.shiftKey` in the handler (maybe this should be done even if (1) or (2) are picked)

**Comment by lesliecdubs** [comment]
Thanks for the request @japf. 

@primer/accessibility-design do you have any thoughts on this new keyboard shortcut suggestion, or should we check in with #accessibility more broadly before executing on this?
