### ISSUE TITLE
ActionList.Item has a delay rendering big lists

### ISSUE THREAD

**Issue by hernanif1** [primer/react#2683]
### Description

Passing lists bigger than 100 items to ActionList.Item makes it noticeable slow.  I did a codesandbox to demonstrate the component behavior. Please let me know if you need more evidences.  

### Steps to reproduce

https://codesandbox.io/s/quiet-moon-4xj5lw?file=/src/App.tsx

https://user-images.githubusercontent.com/1771727/207038675-8257562b-650d-4a26-bcb7-cbe87cd0950d.mov

### Version

v35.10.0

### Browser

Chrome

**Comment by lesliecdubs** [comment]
Hi, thanks for the report! There are some general performance improvements we'll be looking into in the new year. In the meantime, I'll move this to our backlog.

**Comment by aarcangeli** [comment]
Note that in the second example (without ActionList.Item) you are actually spawning 25 elements instead of 250
