### ISSUE TITLE
Cannot place Overlay over anchor element if it has z-index and position set

### ISSUE THREAD

**Issue by EnixCoda** [primer/react#2703]
### Description

When trying to use Overlay with elements have `z-index` set, I cannot place the overlay above the trigger elements.

### Steps to reproduce

1. Checkout this demo https://codesandbox.io/s/primer-react-overlay-position-issue-28b3tx

### Version

v35.11.0

### Browser

Chrome

**Comment by EnixCoda** [comment]
Through my quick investigation, I think it is the hardcoded `z-index` in the Portal component causing the issue.

https://github.com/primer/react/blob/5dd4bb1f7f92647197160298fc1f521b23b4823b/src/Portal/Portal.tsx#L74

**Comment by lesliecdubs** [comment]
👋🏻 Hi, thanks for reporting and including a reproduction! This could potentially get fixed by some work we're doing to investigate using the Popover API instead of Portals (#2124). We're going to move this to our backlog for now.
