### ISSUE TITLE
Dialog v2 is missing the `sx` prop

### ISSUE THREAD

**Issue by ajhenry** [primer/react#2709]
### Description

Based on the [dialog v2 prop docs](https://primer.style/react/drafts/Dialog#dialogprops), there is an `sx` prop to control the style of dialog. However, this is missing from the component. 

### Steps to reproduce

1. Apply an `sx` prop to the `Dialog` v2 component
2. Notice that the styles are not applied

Sandbox: https://codesandbox.io/s/interesting-platform-799dti

### Version

v35.14.2

### Browser

Chrome

**Comment by lesliecdubs** [comment]
Hi 👋🏻 Thanks for filing! This seems like something we should fix. @ajhenry do you want to try giving this a go and contributing back? Feel free to drop into #primer on Slack or attend our weekly Office Hours if you'd like support!

**Comment by josepmartins** [comment]
That should be an easy fix (I think). It seems we don't pass the `sx` props to the `StyledDialog` wrapper:

https://github.com/primer/react/blob/main/src/Dialog/Dialog.tsx#L297

**Comment by ajhenry** [comment]
I’m happy to take this one on!
