### ISSUE TITLE
Proposal: Codeblock component

### ISSUE THREAD

**Issue by AyushKoul00** [primer/react#2722]
Please add support for codeblocks and/or uploading code files and seeing the contents of the file in a codeblock.

**Comment by lesliecdubs** [comment]
Hi @AyushKoul00! Is this request specific to a particular Primer React component, or are you requesting a new component for displaying codeblocks?

**Comment by AyushKoul00** [comment]
Both. I would like to request a new component which shows code similar to github (with highlighting, line numbers, etc), but I would also like this support in the MarkdownEditor component

**Comment by justinbyo** [comment]
Hey @AyushKoul00 👋 Thanks for reaching out. We've captured this idea in our backlog. If you have any other details or use cases that you want to share related to this proposal, feel free to add them to this issue.
