### ISSUE TITLE
Checkbox + Radio are not properly vertically aligned

### ISSUE THREAD

**Issue by pveierland** [primer/react#2737]
### Description

The Checkbox and Radio components are not well aligned in the vertical direction, something which appears to be more significant when using Firefox. It would be good if the components were adjusted to better visually align vertically, as the current state almost appears erroneous.

![image](https://user-images.githubusercontent.com/5587375/210531097-87af73c0-563b-4d46-8b2d-af3405d2b68e.png)

![image](https://user-images.githubusercontent.com/5587375/210531216-791ab85e-f3ad-40d3-ac76-a37b0c340809.png)

Using Firefox 107.0.1 (64-bit)

### Steps to reproduce

1. Go to https://primer.style/react/Checkbox
2. Go to https://primer.style/react/Radio

### Version

Latest

### Browser

Firefox

**Comment by joshblack** [comment]
@mperrotti would this be impacted/fixed by: https://github.com/primer/react/pull/2701? 👀

**Comment by govind15496** [comment]
Hey I am a newcomer in this project and I would like to contribute

**Comment by lesliecdubs** [comment]
Thanks for your interest to contribute, @govind15496! We already have a fix for this in the open PR #2701, but feel free to review other [good first issues](https://github.com/primer/react/labels/good%20first%20issue) in this repo.

**Comment by joshblack** [comment]
Closed by #2701
