### ISSUE TITLE
UnderlineNav throws error when screen resizes to a point where no items can render

### ISSUE THREAD

**Issue by joshblack** [primer/react#2752]
### Description

https://user-images.githubusercontent.com/3901764/211390398-e7cd542e-0e68-4b8e-8359-e8b0fd93c2bf.mov

_Video showing the browser being resized to a smaller size. As it gets smaller, items from the underline nav disappear from the list of items. When the space is small enough that no items can be rendered, an error is thrown_

### Steps to reproduce

1. Visit the storybook for `UnderlineNav`: https://primer.style/react/storybook/iframe.html?args=&id=drafts-components-underlinenav-features--overflow-template&viewMode=story
2. Make the window smaller until the error shows up

### Version

v35.16.0

**Comment by joshblack** [comment]
FYI @broccolinisoup!

**Comment by broccolinisoup** [comment]
Oh thanks for reporting this @joshblack! I'll see what is going on 👀
