### ISSUE TITLE
Why use data-component prop?

### ISSUE THREAD

**Issue by adbutterfield** [primer/react#2774]
Hello,

Sorry for the pretty random question. But I searched through the repo, and didn't see any documentation about this prop. 

I'm currently working on a new major version of the design system for my company. I was looking at the primer source code to get see if I can get any cool ideas from your awesome repo.

I was wondering about the use of `data-component` prop though, for style overrides. Is it just more convenient that overriding styles with styled components (like `${SubComponent}`)? Or is there some limitation you hit where this was the only option for overrides?

**Comment by siddharthkp** [comment]
> Is it just more convenient that overriding styles with styled components (like ${SubComponent})?

Yep! Sometimes, it's just nicer to have a selector without creating another component outside the current component. Example: https://github.com/primer/react/blob/main/src/ActionList/Item.tsx#L209

Bonus: If you want to give folks a selector to customize sub-components without exposing them in the API, this works pretty well.

**Comment by adbutterfield** [comment]
That's a great idea, the selector for customization. The current version of our design system exports all sub-components, but it isn't the best developer experience. I was going to switch to using MainComponent.SubComponent (got that idea from a talk you did a while back actually @siddharthkp), but maybe a selector is better.
