### ISSUE TITLE
Button component has no default type

### ISSUE THREAD

**Issue by pveierland** [primer/react#2806]
### Description

The `Button` component does not have a default `type` attribute. In e.g. react-bootstrap, the `Button` component by default has `type` set to `button`. Without such a default, the `type` will default to `submit` within forms, yielding the following warning when using e.g. Formik:

You submitted a Formik form using a button with an unspecified `type` attribute.  Most browsers default button elements to `type="submit"`. If this is not a submit button, please add `type="button"`.

As it is normal to add multiple buttons within a form, it seems safer and more intuitive to have a default type set to `button`, and then explicitly specify which button to use for submission.

### Steps to reproduce

1. Create page with the following form:
```
<form>
<Button type="submit">Submit</Button>
<Button>Recalculate<Button>
</form>
```

2. The second button will default to `type=submit` instead of `type=button`. Expected behavior would be that the second `Button` type would default to `button`.

### Version

v35.2.0

### Browser

Firefox

**Comment by iansan5653** [comment]
:+1: I completely agree - setting the default type to `button` seems like a no-risk change to avoid some very unintuitive browser behavior. A common case where we see this turn into bugs is with "Cancel" buttons, ie:


```tsx
<form onSubmit={submitHandler}>
  {/* ... */}

  <Button onClick={cancelHandler}>Cancel</Button>
  <Button type="submit" variant="primary">Primary</Button>
</form>
```

Pressing "Cancel" in this form will unintentionally submit the form because the button doesn't have `type="button"`.

**Comment by joshblack** [comment]
Opened up a quick PR here: https://github.com/primer/react/pull/2807 to put it on `Button` itself. Curious if you all would expect it to be there or potentially at a lower-level like `ButtonBase` for other button-like components that might use it 👀

**Comment by pveierland** [comment]
I'd vote for adding it to `ButtonBase`, as otherwise the issue would still affect `LinkButton`, and could sneak up with future `Button` variants.
