### ISSUE TITLE
The example in MarkdownEditor not displaying properly

### ISSUE THREAD

**Issue by zhoushengdao** [primer/react#2816]
### Description

I found that the example in MarkdownEditor did not display properly and the following error occurred:
```
SyntaxError: Unexpected identifier 'markdown'    // Chrome & Edge
SyntaxError: missing ( before formal parameters    // Firefox
```
The Firefox error message indicates that the markdown should be enclosed in brackets. BTW I tried it and this is working.

https://user-images.githubusercontent.com/53334669/214815264-a322f309-6240-4fc6-b0e5-e36cbb83e817.mp4

### Steps to reproduce

1. Open a browser
2. Go to https://primer.style/react/drafts/MarkdownEditor#examples
3. View the error message below the code

### Version

*

### Browser

Chrome, Firefox, Edge

**Comment by iansan5653** [comment]
Hi, thanks for the report. Would you like to contribute the fix? Looks like you'd just need to apply your suggested change to the [`MarkdownEditor.mdx`](https://github.com/primer/react/blob/main/docs/content/drafts/MarkdownEditor.mdx) doc file.

**Comment by zhoushengdao** [comment]
Ok, I will open a PR. Thank you to review and merge it.
