### ISSUE TITLE
Add instructions to test React apps built with primer/react

### ISSUE THREAD

**Issue by Zenulous** [primer/react#2836]
Recently I've been working on a project that utilizes this component library. We use jest and `react-test-renderer` to create tests for our frontend. There are issues when running the tests due to CSS definitions: 
![image](https://user-images.githubusercontent.com/45333650/215474243-50db72f4-580d-418f-bccc-43da41aca5d9.png)

Solutions for this include importing helpers like https://github.com/primer/react/blob/main/src/utils/test-helpers.tsx, and I think it can be valuable to refer to this in documentation as it took me quite some time to figure out how to properly mock CSS.

**Comment by lesliecdubs** [comment]
👋🏻 @JoseInTheArena would this be of interest to Web Systems in regards to providing documentation about how to test React apps on the paved path?
