### ISSUE TITLE
Breadcrumbs.Item with Next.js Link component gives activeClassName warning

### ISSUE THREAD

**Issue by pveierland** [primer/react#2847]
### Description

When using `Breadcrumbs.Item` with Next.js and `next/link`, the following warning occurs:

```
Warning: React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Creating an adapted version of `Breadcrumbs.Item` resolves the issue:

```
const BreadcrumbsItem = styled.a.attrs(props => ({
    className: classnames(props.selected && SELECTED_CLASS, props.className),
    'aria-current': props.selected ? 'page' : null,
    ...(typeof props.to === 'string' ? { activeClassName: 'selected' } : {}),
}))
...
```

I'm not sure if this is the desired fix, however it would be good if the issue is resolved, or that my usage is corrected if invalid.

### Steps to reproduce

1. Create a test page using Primer React 35.18.0 + Next.js 13.1.5:

```
import { Breadcrumbs } from '@primer/react';
import Link from 'next/link';

export default function TestPage() {
    return (
        <Breadcrumbs>
            <Breadcrumbs.Item
                as={Link}
                href={'/target'}
            >
                Target
            </Breadcrumbs.Item>
        </Breadcrumbs>
    );
}
```

### Version

35.18.0

### Browser

Firefox

**Comment by imrishabh18** [comment]
Hey @lesliecdubs, I would like to contribute to this issue. Can you explain a bit more about this please?

**Comment by lesliecdubs** [comment]
Hi @imrishabh18, thanks for your interest in contributing!

@broccolinisoup is a Primer React maintainer who is our first responder this week. Armagan, could you take a look at this issue and see if you can provide some breadcrumbs for next steps so @imrishabh18 could work on this?

**Comment by broccolinisoup** [comment]
Sure @lesliecdubs! Added to my to-do list. I'll make sure to respond with some more info this week!

**Comment by broccolinisoup** [comment]
Hi @imrishabh18 👋🏻 Thanks for your interest in contributing to `Primer/react`!

We have an `examples` folder in the primer/react repo and under that folder, very minimal [Next.js app](https://github.com/primer/react/tree/main/examples/nextjs) that we use as a playground for Next.js. You can use this app to replicate the issue. 

Make sure you have updated [the package.json file](https://github.com/primer/react/blob/main/examples/nextjs/package.json) with the Next.js version that was mentioned in the issue description (v13.1.5) to have the most accurate environment. Please install the packages (`npm install` in the `examples/nextjs` folder and `npm run develop` to start your dev environment)

As it is suggested in the issue, please create a `test.js` file under the [pages](https://github.com/primer/react/tree/main/examples/nextjs/src/pages) folder and copy the content (`TestPage` component in the description) and go to the url `<your-localhost>/test` and you should be able to see the warning that was mentioned on the console as well as on your terminal logs. Let us know if you need more support on this 🙌🏻  Thanks!

**Comment by broccolinisoup** [comment]
Hey @imrishabh18 👋🏻 I realised that the same issue occurs in multiple components and I pushed a [fix](https://github.com/primer/react/pull/3061) for it. I assigned the issue myself and will be closed soon. Please let me know if you have any concerns! Apologise if I caused any inconveniences! Thank you 🙏🏻

**Comment by broccolinisoup** [comment]
Hi @imrishabh18 👋🏻  I realised this behaviour is happening in multiple components and created an [issue](https://github.com/primer/react/issues/3060) for that and pushed a [PR](https://github.com/primer/react/pull/3061). I apologise if you have already started working on that. Please let me know if you have any concerns and/or if you are still keen to contribute to Primer, we can help you grab some good first issue components!
