### ISSUE TITLE
Ensure Header component uses proper semantic `header` HTML tag

### ISSUE THREAD

**Issue by Caixetadev** [primer/react#2870]
I have a question, why is the Header component not a header tag? I also noticed that it has more elements that could be other elements instead of a div.

![image](https://user-images.githubusercontent.com/87894998/217141107-cb936d2c-eadd-4c26-a92d-53a7314fe246.png)

**Comment by lesliecdubs** [comment]
Hello @Caixetadev 👋🏻 Which component/file was this code in?

**Comment by Caixetadev** [comment]
> Hello @Caixetadev 👋🏻 Which component/file was this code in?

here:
```src/Header.tsx```

**Comment by Caixetadev** [comment]
Can I open a PR for this? @lesliecdubs

**Comment by lesliecdubs** [comment]
Hi @Caixetadev. As it turns out, this component isn't in use at GitHub and is likely to be deprecated in the near future. That being said, if you'd like to submit a PR for the change, feel free.

**Comment by amarmanhala** [comment]
👋 Hi @lesliecdubs, Can I fix this issue and contribute to the project?

**Comment by lesliecdubs** [comment]
Hi @amarmanhala 👋🏻 Yes, this is still a valid issue. As per https://github.com/primer/react/issues/2870#issuecomment-1428809937 this component is likely to be deprecated in the future, but if you'd like to submit a fix in the meantime we will review the contribution.

For more details on contributing, we invite you to review the [contributor docs](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md). Thanks for participating!

**Comment by amarmanhala** [comment]
Thank you @lesliecdubs for the opportunity. I have started working on this issue.
