### ISSUE TITLE
SplitPageLayout.Pane accepts an id but doesn't apply it.

### ISSUE THREAD

**Issue by jdrush89** [primer/react#2909]
### Description

SplitPageLayout.Pane accepts an id as a prop, but doesn't apply it to any element

### Steps to reproduce

Add an id to SplitPageLayout example:

```
<Box sx={{height: 320, overflowY: 'auto', border: '1px solid', borderColor: 'border.default'}}>
  <SplitPageLayout>
    <SplitPageLayout.Header>
      <Placeholder label="Header" height={64} />
    </SplitPageLayout.Header>
    <SplitPageLayout.Pane id="test-id">
      <Placeholder label="Pane" height={120} />
    </SplitPageLayout.Pane>
    <SplitPageLayout.Content>
      <Placeholder label="Content" height={420} />
    </SplitPageLayout.Content>
    <SplitPageLayout.Footer>
      <Placeholder label="Footer" height={64} />
    </SplitPageLayout.Footer>
  </SplitPageLayout>
</Box>
```

And observe that it does not appear in the DOM.

### Version

v35.19

### Browser

Chrome

**Comment by factscub** [comment]
i would like to work on this issue. please assign.

**Comment by lesliecdubs** [comment]
Hi @factscub, thanks for your interest in contributing. However, this issue has already been assigned and has associated PRs open so it is not available for reassignment.
