### ISSUE TITLE
@primer/react PageLayout docs show double-booked anchor link for PageLayout.Pane

### ISSUE THREAD

**Issue by six7** [primer/react#2926]
There seem to be two anchor links with the name `pagelayoutpane` on the PageLayout page for `PageLayout.Pane` - one time in the docs itself and one time coming from `ComponentProps`. Effectively this prevents people linking to the props of `PageLayout.Pane` itself, see video below.

https://user-images.githubusercontent.com/4548309/220627873-d622cf90-7d2e-421a-913b-4d0b0aaa7857.mp4

https://github.com/primer/react/blob/b3786fa79905c5fd1875cb633784121692690bcc/docs/content/PageLayout.mdx?plain=1#L321

**Comment by factscub** [comment]
i would like to work on this issue.please assign.

**Comment by lesliecdubs** [comment]
Hi, thanks for reporting this bug! We're making great progress on a refreshed Primer docs experience and this should be taken care of there. We'll leave it open for now to make sure this gets resolved in the new site. Follow along here > https://github.com/github/primer/issues/1624

**Comment by lesliecdubs** [comment]
Not stale, put up a PR for quick fix: https://github.com/primer/react/pull/3681
