### ISSUE TITLE
Button style overrides for size medium break in 35.20

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#2927]
### Description

When applying size small or large, the sx overrides apply, howevever the color of the text loses its override when size=medium

https://user-images.githubusercontent.com/8616962/220628972-f09fcfa5-5f7b-49a7-9391-9bd9b2723627.mov

### Steps to reproduce

Add a button with sx overrides, and apply size=small vs size=medium

### Version

v35.20.0

**Comment by langermank** [comment]
Thanks for filing this issue! I can reproduce this, however `medium` is the default size 🤔 so you don't ever really need to set `size="medium"`. With that in mind, I'm not sure this is worth fixing (unless its an easy fix, which I suspect it might not be.) Tagging @broccolinisoup to see if she has any thoughts!

**Comment by mattcosta7** [comment]
> With that in mind, I'm not sure this is worth fixing (unless its an easy fix, which I suspect it might not be.) Tagging @broccolinisoup to see if she has any thoughts!

I'd disagree that it's not worth fixing - unless we remove `medium` as a valid size prop?  it seems like we shouldn't expose an API that breaks the styling of the feature?

**Comment by broccolinisoup** [comment]
Thanks @mattcosta7 for reporting the issue! I added a quick fix and seems to be working on the story https://github.com/primer/react/pull/2929
