### ISSUE TITLE
Labels of form elements on storybook have `VisuallyHidden` classes but they are not visually hidden

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#2947]
## Issue
Looks like the form elements on storybook ([TextInput](https://primer.style/react/storybook/?path=/story/components-forms-textinput--default) as one example) are intended to be visually hidden (see [the code reference](https://github.com/primer/react/blob/main/src/utils/story-helpers.tsx#L334)) but they are not actually visually hidden. It came up during one of the `axe-clean` [violation fix](https://github.com/primer/react/pull/2937#discussion_r1118226584) and would be great to fix all these form elements that have the same problem. 

## Proposed solution

Removed the `VisuallyHidden` parameter from the `Form.Label` component (code [ref1](https://github.com/primer/react/blob/main/src/stories/TextInput.stories.tsx#L58), [ref2](https://github.com/primer/react/blob/main/src/utils/story-helpers.tsx#L334)) in below components' stories and make sure the Default story has a visual label and add another story to demonstrate the component with a visually hidden title.

`Autocomplete`, `InlineAutocomplete`, `Select`, `TextArea`, `TextInput`, `TextInputWithTokens`

### Steps to reproduce

1. Go to the Primer React storybook https://primer.style/react/storybook
2. Check out any of the Form Elements that were mentioned above https://primer.style/react/storybook/?path=/story/components-forms-autocomplete--add-new-item
3. Inspect and see the label element in the dom that has `VisuallyHidden` class.

### Version

v35.20.0

### Browser

Chrome, Safari, Firefox, Edge, iOS Safari

**Comment by mperrotti** [comment]
I'm not understanding the problem. The `visuallyHidden` prop is meant to allow users to provide a label and hide it visually but keep it accessible to assistive technologies.

I don't think we should merge this, but if we do it would be a breaking change for people who currently use the `visuallyHidden` prop on `FormControl.Label`.
