### ISSUE TITLE
Support non-string content in `Token`

### ISSUE THREAD

**Issue by iansan5653** [primer/react#2952]
`Token` only supports strings as content, via the `text` prop. This is inconsistent with `Label`, which is a similar component that supports full `ReactNode` as `children`.

There doesn't seem to be any reason not to support complex content here, such as formatted text. 

I propose one of these options:

- Add a `children` prop but leave the `text` prop for legacy uses
- Add a `children` prop and delete the `text` prop as a breaking change
- Allow `ReactNode` instead of `string` for the `text` prop as a way to avoid a breaking change

**Comment by joshblack** [comment]
Definitely +1 to `ReactNode`, totally makes sense to have them consistent as long as there is no issues with nested markup. It doesn't seem like we'd run into that with Token since we wouldn't have a situation of nested interactive content in an interactive tag, seemingly.

**Comment by broccolinisoup** [comment]
Thanks @iansan5653 for reporting this 🙌🏻 Agreed to @joshblack +1 for the `ReactNode`

**Comment by iansan5653** [comment]
🤔 So it turns out it's a little more complicated than I expected. It looks like we force `string` content because we use the content to build an `aria-label` when the token is deletable, to indicate the keyboard shortcut for deletion. Ie: "Bug, press backspace or delete to remove". For example (shown the the most complex case when the token is interactive):

```html
<span aria-label="Bug, press backspace or delete to remove">
  <button>Bug</button>
  <span tabindex="-1" aria-hidden><!-- delete icon --></button>
</span>
```

A couple of options to address this:

- Add a `hidden` span with this content and use `aria-describedby` to link this hint text. This feels more ergonomic because it won't have to be read for every single token (particularly annoying when there are many tokens). And by not building a string from the content of the token, we avoid mandating that the contents are easily stringable.
- Render the deletion hint as a `VisuallyHidden` child of the element. This would not help with redundancy but would be an improvement over the current experience when the token is interactive, because it would properly label the button instead of the wrapping `span`.
- Remove the keyboard shortcut hint and make the delete button interactive (focusable and non-hidden with the correct role) instead.

I'm somewhat partial to the last one as it seems to also help keyboard users (who currently don't see the hint and also can't focus the delete button). Maybe it would be confusing to have multiple buttons called "Delete" when there is a set of tokens, but that could be solved from the parent container by using `list`/`listitem` to wrap the tokens.

**Comment by iansan5653** [comment]
I went ahead and opened a [PR](https://github.com/primer/react/pull/2954) with that second option. If you disagree, I don't mind reworking it with a different solution.
