### ISSUE TITLE
ActionList full variant display issues inside of an ActionMenu 

### ISSUE THREAD

**Issue by treacher** [primer/react#2977]
### Description

When using the ActionMenu component with the ActionList variant of "full" the list items don't display as expected. Please see a screenshot using https://primer.style/react/ActionMenu:

![Screenshot 2023-03-03 at 3 09 06 pm](https://user-images.githubusercontent.com/918794/222629302-1d593fe9-9048-4627-90eb-6db18aaea111.png)

Display issues observed:
- The item does not span the full width.
- The active focus styles seem to get clipped off the left side.

### Steps to reproduce

I was able to reproduce this by doing the following:

1. Go to https://primer.style/react/ActionMenu#with-selection
2. Change the `<ActionList selectionVariant="single">` line to `<ActionList selectionVariant="single" variant="full">`
3. Click on the rendered ActionMenu button.
4. Press the down key.

### Version

v35.16.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi! We haven't run into full width ActionList inside a menu yet, so for opening this issue! 🤔 

Can you tell a little more about what you're trying to do?

**Comment by treacher** [comment]
Hey 😄 the picture below shows what I'm looking to achieve by using the full variant.

![222064566-ebed8f5c-d054-4275-a9e8-890db4404303](https://user-images.githubusercontent.com/918794/223592189-da36e247-70e1-4de6-8a49-1cd2f0f2fe25.png)

This is for selecting an account when using the contact form on https://support.github.com/ when signed in.

**Comment by lesliecdubs** [comment]
Hi @treacher, thanks for filing this! The issue is in our backlog. In the meantime, is there a reason you wouldn't be able to switch to the `inset` (default) variant?

**Comment by treacher** [comment]
Thanks for that @lesliecdubs, for now we have implemented a workaround to get the desired design.
