### ISSUE TITLE
Remove duplicated `ActionMenu` file

### ISSUE THREAD

**Issue by ollie-iterators** [primer/react#2992]
### Description

Since https://github.com/primer/react/pull/2991 was merged. I was thinking about if there are some other files that need to be deleted in the src file.

I think these files need to be removed:
- ActionMenu.tsx
- ~Dialog.docs.json~
- ~Dialog.tsx~

Updated by @broccolinisoup : Dialog changes are [reverted](https://github.com/primer/react/pull/3040), so only `ActionMenu.tsx` needs to be deleted.

### Steps to reproduce

Check out the file: https://github.com/primer/react/tree/main/src

The ActionMenu and Dialog elements have been migrated to their own files but still have files in the src file.

### Version

35.2.0

**Comment by joshblack** [comment]
Thanks @ollie-iterators for taking the time to make this issue! 🙏 

This is a great point, looking into it I _think_ Dialog is related to v1 of the component (did I get that right @broccolinisoup?)

For ActionMenu, is this similar to TextInput @langermank and we should remove it, as well?

**Comment by ollie-iterators** [comment]
There may be others that were different enough that I did not put in the list like header / heading

**Comment by langermank** [comment]
@joshblack yeah, looks like I missed ActionMenu- so that should be deleted as well. I'll open a PR.

**Comment by broccolinisoup** [comment]
@joshblack Yes! They belong to the v1 and we need to keep these for now as it hasn't been migrated yet.

**Comment by lesliecdubs** [comment]
👋🏻 @langermank I'm going to assign this to you since I saw you said you'd open a PR. Give us a holler if that doesn't close this issue.

**Comment by broccolinisoup** [comment]
Just to note that `Dialog` has been moved into the folder as well. https://github.com/primer/react/pull/3019
