### ISSUE TITLE
It would be good to have a checker for dead code in the project

### ISSUE THREAD

**Issue by ollie-iterators** [primer/react#3000]
### Description

Since I submitted the issue (https://github.com/primer/react/issues/2992), I was thinking about the fact that there should be a checker for dead code or files in the project so that people can more easily find out when certain files in the src folder should be removed.

I looked it up and deadfile (https://m-izadmehr.github.io/deadfile/#/) seems to be a good resource to find dead files in JavaScript projects

### Steps to reproduce

This is related to https://github.com/primer/react/issues/2992

### Version

35.2.0

**Comment by lesliecdubs** [comment]
👋🏻 Hi @ollie-iterators, thanks for the suggestion! While we're moving some files around right now, there is the potential to introduce some dead code but this is not a common situation so we'd rather not introduce a new CI check. Appreciate your input!
