### ISSUE TITLE
Content collision on https://primer.style/design/components/filter-input

### ISSUE THREAD

**Issue by ollie-iterators** [primer/react#3013]
### Description

The content on the page https://primer.style/design/components/filter-input collides with the sidebar menu at certain page widths.
<img width="1227" alt="2023-03-10_12-15-09" src="https://user-images.githubusercontent.com/46904826/224380161-9c23666a-ee0a-4ab1-89b3-6ece846d4f5e.png">

### Steps to reproduce

1. Open the URL
2. Make the page thinner until the content collides with the sidebar menu

### Version

35.2.0

**Comment by colebemis** [comment]
Good catch. Thanks for reporting this. I'll take a look.
