### ISSUE TITLE
ActionList.Item using wrong colors and get invisible in high-contrast theme

### ISSUE THREAD

**Issue by pablonete** [primer/react#3044]
### Description

We're using a `<ActionList.Item variant="danger" ... />` and it renders wrong in high-contrast themes (both dark and light) but not on any other theme:
![image](https://user-images.githubusercontent.com/579705/225661046-4826f9d9-c9ee-4cad-a1e6-5ec542074ab0.png)
Also wrong on hover:
![image](https://user-images.githubusercontent.com/579705/225661111-218b1f91-6900-480b-9982-7fbbedc13909.png)

Interestingly, text color gets fixed on resize (e.g. just opening DevTools) while icon color stays always wrong.

https://github.com/github/github/blob/8d9083549de626e8b3fa9667a2de09840f39642f/app/assets/modules/custom-properties/components/DefinitionsTable.tsx#L74

### Steps to reproduce

I'll go with the Monolith Storybook where it's easier:
1. `npm run storybook` in a `github/github` codespace
2. Once the page opens `:6006`, click Color scheme and use `light_high_contrast`
3. Click on "CustomPropertiesSchemaPage"
4. Click on the ellipsis button at the right to show the actions menu

Expected: label and icon readable
Actual: icon visible and label transparent, the opposite on mouse hover

Some repro videos on [slack](https://github.slack.com/archives/C01L618AEP9/p1678892029899589).

### Version

v35.21.0

### Browser

Chrome, Firefox

**Comment by langermank** [comment]
I've got a fix for this in Rails, but looking at the [React code for ActionList](https://github.com/primer/react/blob/b55d8232ce9d990cc91862fff2f6f15ff2fdb65d/src/ActionList/shared.ts#L75) I'm not sure how to achieve the same thing. We need to target the `hover` state.
