### ISSUE TITLE
Focus not appearing on non-standard dialog button (re-opened after revert)

### ISSUE THREAD

**Issue by ctmayn** [primer/react#3062]
### Description

Focus does not appear at all on Primary and Danger buttons in a Dialog Footer

### Steps to reproduce

1. Go to https://primer.style/react/storybook/?path=/story/components-dialog--stress-test
2. Open the Dialog
3. Use tab to move through the footer buttons
4. Notice that once you get to the danger and primary buttons, focus is no longer visible

### Version

v35.22

### Browser

Chrome

**Comment by langermank** [comment]
This should be a quick fix. The Dialog component is using the deprecated Button component, which doesn't have the new focus styles. Here's the [source code](https://github.com/primer/react/blob/51cdbb0c3a30953ba98ff26b937ee1d13c6543aa/src/Dialog/Dialog.tsx) for Dialog.

**Comment by tallys** [comment]
@langermank assigning your way, let me know if you can take a look

**Comment by siddharthkp** [comment]
Thank you @mperrotti! 

This was reopened because of https://github.com/primer/react/pull/3527

**Comment by siddharthkp** [comment]
Copying reasons for reverting from https://github.com/primer/react/pull/3527, 

Issues found: 

1. (link is github staff only) [ui/packages/memex/src/client/pages/insights/components/insights-upsell-dialog.tsx:66](https://github.com/github/github/blob/master/ui/packages/memex/src/client/pages/insights/components/insights-upsell-dialog.tsx#L66) uses Button as="a", the types for which are not supported

   Reported in https://github.com/github/github/actions/runs/5573804589/jobs/10181608881:

   ```
   ui/packages/memex/src/client/pages/insights/components/insights-upsell-dialog.tsx(66,11): 
   error TS2322: Type '{ as: string; buttonType: "primary"; content: JSX.Element; href: string; sx: { ml: number; }; target: string; rel: string; onClick: () => void; }' is not assignable to type 'DialogButtonProps'.
   ```

2. Checking the [storybook for the pull request](https://primer-fbbec81156-13348165.drafts.github.io/storybook/?path=/story/components-dialog--basic-dialog), it looks like the focus bug was not fixed

**Comment by lesliecdubs** [comment]
@broccolinisoup during planning, we assumed this would be part of the handover of this week's release. Does that sound right to you? Can you help handle this as @joshblack takes over Release Conductor duties?

**Comment by broccolinisoup** [comment]
@lesliecdubs The PR is reverted ([Sid's comment](https://github.com/primer/react/issues/3062#issuecomment-1642250738)) so I don't think this is anymore a part of the release handover. Let me know if I am missing any context though! (I watched the recording as well for the planning session)

@mperrotti posted a thread on Slack about this as well. https://github.slack.com/archives/C02NUUQ9C30/p1689885950498289 

Assuming this is a standalone issue out of the release, we can pair on this with @mperrotti - Mike are you keen? 🙌🏻

**Comment by lesliecdubs** [comment]
Ah, thanks! Sounds good. If Mike isn't down to pair, let's send this back to the project board Inbox to re-triage.

**Comment by mperrotti** [comment]
I'd be down to pair!

**Comment by broccolinisoup** [comment]
cross linking https://github.com/github/accessibility-audits/issues/5562

**Comment by lesliecdubs** [comment]
👋 @mperrotti @broccolinisoup were y'all ever able to find time to pair on this? 

It came up today [on Slack](https://github.slack.com/archives/C01L618AEP9/p1698250298823229) (GitHub staff only) and I'm wondering if we should re-triage this, and/or get it on the radar for [active Dialog work](https://github.com/github/primer/issues/2698) (GitHub staff only).

**Comment by camertron** [comment]
This also came up while performing accessibility issue refining on https://github.com/github/accessibility-audits/issues/6477

**Comment by broccolinisoup** [comment]
>👋 @mperrotti @broccolinisoup were y'all ever able to find time to pair on this?

@lesliecdubs unfortunately not. I think it would be great to include in the [Dialog work](https://github.com/github/primer/issues/2698) if possible.

**Comment by lesliecdubs** [comment]
Thanks @broccolinisoup, I've cross-linked this issue to the `Dialog` work and we can try to plan for Primer Engineering to address it when we get further into `Dialog` remediation work in that epic.

**Comment by TylerJDev** [comment]
With [v36.5.0](https://github.com/primer/react/releases/tag/v36.5.0) released, I'm going to close this issue as fixed! Footer buttons should now have proper focus indicators.
