### ISSUE TITLE
Support tabs that are not links in TabNav

### ISSUE THREAD

**Issue by mperrotti** [primer/react#3100]
There are some cases where tabs shouldn't be links, but the `TabNav` component only supports tabs that are links.

I recommend adding props that allow consumers to use tabs as buttons and handle tab changes.

Primer ViewComponents supports this pattern using the [TabPanels](https://primer.style/view-components/components/alpha/tabpanels) component.

For example, the non-modal dialog for selecting a repo's branch or tag.
<img width="960" alt="2  Link tabs vs button tabs" src="https://user-images.githubusercontent.com/2313998/228978216-6e6721cf-ffa8-4957-8b74-6a580eaa01e4.png">

**Comment by tallys** [comment]
@mperrotti let's discuss at Primer Patterns and scope it out

**Comment by siddharthkp** [comment]
`<TabNav.Link as="button">` works but looks really odd 😅

**Comment by mperrotti** [comment]
@broccolinisoup - I think this is a duplicate of https://github.com/github/primer/issues/1800

If you agree, can you close this one?
