### ISSUE TITLE
Remove @testing-library/react-hooks in favor of @testing-library/react

### ISSUE THREAD

**Issue by joshblack** [primer/react#3132]
Noticed over in: https://github.com/primer/react/pull/3077 that later versions of `@testing-library/react-hooks` do not support React 18 🤔 

When looking into this, it seems that the recommendation is to instead use `renderHook` from `@testing-library/react` directly: https://testing-library.com/docs/react-testing-library/api/#renderhook

This work would require removing call sites of `@testing-library/react-hooks` and replacing them with `@testing-library/react`. A previous exploration of this work was done over in: https://github.com/primer/react/pull/3129

This work will require React 18 support since this is not available in the previous major version of `@testing-library/react`.

**Comment by roy9495** [comment]
Hello, may I work on this issue?

**Comment by joshblack** [comment]
Hey there @roy9495! 👋 Thanks so much for reaching out about this!

Right now, it seems like this issue has a blocker since the project currently tests across React 17 and 18. One thing I found about the work over in #3129 is that this would not work in that React 17 case since `@testing-library/react` does not have `renderHooks` exported 😞 https://github.com/primer/react/pull/3129#issuecomment-1499350137

Just wanted to bring this up, if you have any suggestions or ideas for a workaround that would help us close this issue then it would be greatly appreciate and we would love if you picked up the work for this!

**Comment by lesliecdubs** [comment]
Blocked on React 18 support
