### ISSUE TITLE
Split Page Layout Content has set styles and no way to override them

### ISSUE THREAD

**Issue by milemons** [primer/react#3134]
### Description

PageLayout.Content has marginX hardcoded [here](https://github.com/primer/react/blob/8b5307daad011627fdc96fec1a6d600f479458b5/src/PageLayout/PageLayout.tsx#L450) which cannot be overridden through sx props as it is nested below the box where sx props are applied. In addition, we have no way to pass an id or `data-` attribute down to this component to override. This causes issues for us on the new redesigned repository overview page as you can see in [this discussion](https://github.com/github/engineering/discussions/3047#discussioncomment-5546254)

### Steps to reproduce

1. View issue on repository overview page ie (github.com/github/github) with the `react_repos_overview` flag turned on.

### Version

v35.24

### Browser

Chrome, Safari, Firefox, Edge

**Comment by colebemis** [comment]
I'm going to hold off on addressing this until we have a better idea of how styling overrides will work in the new styling architecture: https://github.com/github/primer/issues/2008
