### ISSUE TITLE
Button with invisible variant has no disabled styling differences

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#3167]
### Description

Button variant 'invisible' has no discernible disabled styling.  In these examples, an invisible and outline button are disabled and enabled - but it's only noticeable which is which for the outline variant

Enabled

<img width="180" alt="Screenshot 2023-04-13 at 5 24 09 PM" src="https://user-images.githubusercontent.com/8616962/231886372-e6822fb4-e5c6-4542-82d1-227b40ee299c.png">

Disabled

<img width="269" alt="Screenshot 2023-04-13 at 5 24 03 PM" src="https://user-images.githubusercontent.com/8616962/231886374-edfa37ca-fe84-4e99-bfe4-c4c090b330a0.png">

### Steps to reproduce

disabled an invisible variant button that has text in it

### Version

latest

### Browser

Chrome

**Comment by siddharthkp** [comment]
primer/css handles this well: 

<img width="442" alt="image" src="https://user-images.githubusercontent.com/1863771/232538620-d77dfa87-23f2-43a2-adaa-f0f5fb3a9fee.png">
