### ISSUE TITLE
Odd Borders on `IconButtons` in `ButtonGroup`

### ISSUE THREAD

**Issue by mattcosta7** [primer/react#3172]
### Description

https://user-images.githubusercontent.com/8616962/232143686-d040c5e8-5cb3-459d-a98e-b7fbfbb16985.mov

In a button group, IconButtons seem to have the wrong borders on focus/hover

### Steps to reproduce

```tsx
         <ButtonGroup>
                <IconButton aria-label="" icon={GearIcon} />
                <IconButton aria-label="" icon={SortAscIcon} />
                <IconButton aria-label="" icon={SortAscIcon} />
              </ButtonGroup>
              ```

checkout hover borders

### Version

latest

**Comment by broccolinisoup** [comment]
Hi 👋  I think this issue might be related to https://github.com/primer/react/pull/2933? As far as I understand this behaviour was intentional, at least it was a tradeoff between the wiggly buttons vs border style  https://github.com/primer/react/pull/2933

**Comment by mattcosta7** [comment]
> Hi 👋 I think this issue might be related to #2933? As far as I understand this behaviour was intentional, at least it was a tradeoff between the wiggly buttons vs border style #2933 cc @langermank

Interesting.  It definitely _looks_ broken now, especially in dark mode.  

Maybe we could set the border-left's color to the non-hover color when it's not the first button, so at least the left and right borders are balanced on 'central' buttons?

**Comment by mattcosta7** [comment]
^ thae left border fix suggested above would also help out with this case where the focus outline and hoverborder on separately elements show, and it looks a little off (at least to me)

<img width="103" alt="Screenshot 2023-04-17 at 9 10 12 AM" src="https://user-images.githubusercontent.com/8616962/232493781-fb09256b-4514-480e-9af0-67522ddf4d8f.png">

**Comment by mattcosta7** [comment]
FWIW

locally I added these styles to the `ButtonGroup` overriding others (via inline styling)

```
    display: inline-table;
    flex-shrink: 0;
    border-collapse: collapse;
```

I then removed the 'border-right-width: 0' from the nested button elements

Looks like this leads to the intended behavior

https://user-images.githubusercontent.com/8616962/232794528-b15fb5f3-12a4-40d1-9526-f4854c6bd37f.mov
