### ISSUE TITLE
TreeView Navigation Link - Keyboard Accessibility

### ISSUE THREAD

**Issue by gracepark** [primer/react#3224]
### Description

Hi there,

I'm on the Docs team here at GitHub, and we're currently using the TreeView Component for navigation links with Next.js in a similar way to [this example](https://primer.style/react/TreeView#with-nextjs). 

We are using our own [NextJS Link Component](https://github.com/github/docs/blob/main/components/Link.tsx) with TreeView. This has been working great for our use case except for the fact that it's not keyboard accessible. On keyboard press Enter, it does not route to the `href` as expected as when you click. 

The TreeView component has been a great for our sidebar in terms of usability and design and we'd love if it could be keyboard accessible with navigation links. 

### Steps to reproduce

Given the Next.js example, swap out `Link` with an `a` tag:

```
function TreeLinkItem({id, href, children}) {
  const router = useRouter()
  const isCurrent = typeof href === 'string' ? router.asPath === href : router.pathname === href.pathname
  return (
    <a href={href}>
      <TreeView.Item id={id} aria-current={isCurrent ? 'page' : false} current={isCurrent}>
        {children}
      </TreeView.Item>
    </a>
  )
}
```

Use tab to focus on the TreeView item and press Enter on your keyboard.
Press Enter and you will not be routed. 

### Version

v35.2.0

### Browser

Chrome

**Comment by ericwbailey** [comment]
Hey @gracepark. I'm afraid TreeView is not an appropriate component to use for this kind of UI. 

While it may visually look like what you need for the design on the surface level, it has really specific interaction patterns and expectations for assistive technology on the code level. We have [some guidance on this for the component documentation](https://github.com/primer/react/pull/3197), but unfortunately it is still in the process of being merged.

Modifying the TreeView to accommodate the behavior you're requesting would endanger its primary use case, which is listing and taking action on a hierarchical list of files (think the sidebar in your code editor, or Windows' file explorer). This would consequently lead to accessibility issues.

The pattern you've linked to looks like a [NavList](https://primer.style/react/NavList). I would recommend exploring using that component instead, if possible.

Tagging @owenniblock, @joshblack, and @colebemis for visibility.

**Comment by gracepark** [comment]
@ericwbailey - Unfortunately, NavList is not a possibility for us because NavList only supports one level of nesting. We need sometimes up to 3-4 levels of nesting. Would it be possible to add additional nesting capabilities to NavList?

**Comment by ericwbailey** [comment]
Hey @gracepark, thanks for your patience here. Would you be able to attend the Primer Patterns + API Working Session next week on [Tuesday, May 2nd at 2pm ET](https://www.worldtimebuddy.com/)? 

This meeting is where we could discuss your use case in more detail and figure how how to extend the NavList component to accommodate it. If not, could I trouble you for a list of criteria I could bring up for you as talking points?

**Comment by heiskr** [comment]
Hey @ericwbailey, the change we would need to NavList would be that we need to support up to 4 levels of navigation. Most of the site only goes to 3 levels, but in a few cases it goes to 4 levels. The other item would be an accessibility review of the NavList component.

**Comment by gracepark** [comment]
Hi @ericwbailey - Sorry I was OOO last week. What @heiskr mentioned is correct. Please let me know if you still need additional info and I'd be happy to join the meeting.

**Comment by ericwbailey** [comment]
@heiskr Acknowledged on the nested levels need. That'll be helpful for a point to chat through in the Primer meeting.

As for an accessibility review, that is a separate workstream that I believe is currently underway. The advice we've been giving as Primer is to use the appropriate component regardless of its accessibility status in that known component is easier to quantify and remediate than bespoke solutions. 

@gracepark I've just invited you to tomorrow's Primer API session. It'll be from 2-2:45 ET, and I made sure this issue is captured in its meeting notes.

**Comment by mperrotti** [comment]
@gracepark @ericwbailey - we're going to update NavList to allow up to 4 levels of nesting. Expect a PR soon! Can this issue be closed?

**Comment by gracepark** [comment]
That's amazing thank you so much @mperrotti! Do you know if NavList would be reviewed for accessibility then as well? I think once it's accessibility 👍 we'll be able to utilize the component.

**Comment by ericwbailey** [comment]
It will!

**Comment by gracepark** [comment]
That's awesome thank you so much @mperrotti and @ericwbailey. Issue can be closed!

**Comment by gracepark** [comment]
@mperrotti - would you happen to have a link to the PR? We're going to look into timing for this on our end. Thank you!

**Comment by mperrotti** [comment]
@gracepark - sorry for the delay, I was out for a week and then at a conference. The PR is ready! https://github.com/primer/react/pull/3343

cc @lecoursen

**Comment by gracepark** [comment]
Thank you so much @mperrotti!
