### ISSUE TITLE
Refactor internal components into `internal` folder

### ISSUE THREAD

**Issue by joshblack** [primer/react#3230]
This is a follow-up to our [ADR on Internal Modules](https://github.com/primer/react/blob/main/contributor-docs/adrs/adr-016-internal-modules.md). This issues captures the remaining internal components or helpers that we should consider migrating into `src/internal` to prevent being imported outside of the package.

- [x] _CheckboxOrRadioGroup [PR](https://github.com/primer/react/pull/3263)
- [x] _getGlobalFocusStyles [PR](https://github.com/primer/react/pull/3380)
- [x] _InputCaption [PR](https://github.com/primer/react/pull/3369)
- [x] _InputLabel [PR](https://github.com/primer/react/pull/3370)
- [x] _InputValidation [PR](https://github.com/primer/react/pull/3371)
- [x] _sharedCheckboxAndRadioStyles [PR](https://github.com/primer/react/pull/3379)
- [x] _TextInputInnerAction [PR](https://github.com/primer/react/pull/3372)
- [x] _TextInputInnerVisualSlot [PR](https://github.com/primer/react/pull/3373)
- [x] _TextInputWrapper [PR](https://github.com/primer/react/pull/3375)
- [x] _UnstyledTextInput [PR](https://github.com/primer/react/pull/3376)
- [x] _ValidationAnimationContainer [PR](https://github.com/primer/react/pull/3377)
- [ ] _VisuallyHIdden

**Comment by lesliecdubs** [comment]
Thanks for filing @joshblack! Should this issue go into our Primer teams backlog "inbox" for triage by the team, or did you have other plans for it?

**Comment by joshblack** [comment]
Hey @lesliecdubs! No plans in particular, just was something that came up in PR reviews last week. Inbox triage could be a great place for it 👍

**Comment by ollie-iterators** [comment]
_VisuallyHidden.tsx is still on the page https://github.com/primer/react/tree/main/src

**Comment by green6erry** [comment]
It appears there are two `VisuallyHidden` components. It looks like the main authors were @mperrotti on the one not in `internal`, and @joshblack for the one already in `internal`. The easiest way forward would be to keep both and they are used in multiple places. Is someone able to weigh in how to proceed?

**Comment by mperrotti** [comment]
We shouldn't have two - we should just have one.

@joshblack - does your `VisuallyHidden` do anything that the original doesn't?

**Comment by ollie-iterators** [comment]
It looks like the same thing also may be happening with _TextInputInnerAction.tsx

**Comment by joshblack** [comment]
@mperrotti I think they have a difference in API and styles if I remember right and we just haven't taken the time to merge them yet. I think the difference at that point ends up being that you would toggle rendering `VisuallyHidden` instead of passing in `isVisible`, if I remember right!
