### ISSUE TITLE
`*.docs.json` markdown links do not render on primer.style

### ISSUE THREAD

**Issue by tomthorogood** [primer/react#3302]
### Description

Pretty much the title: It seems that the documentation is rendered as-is without any markdown translation. 

[Example doc code](https://github.com/primer/react/blob/main/src/Octicon/Octicon.docs.json)

![Screenshot of the StyledOcticon documentation on primer.style with a visible markdown link, and no clickable element](https://github.com/primer/react/assets/1092941/5a54e5bc-e8f6-43a7-925b-bf7d4128f35b)

I found lots of these throughout the docs, but this was relevant to me (vis-a-vis #3301). I had a look around but lack too much context to find the silver bullet to fix the rendering issue across all the docs, so I figured I'd open an issue instead :) 

### Steps to reproduce

1. [Go here](https://primer.style/react/StyledOcticon#styledocticon)
2. Have a look! 😅 

### Version

N/A

**Comment by colebemis** [comment]
Good catch. Thanks for flagging this, @tomthorogood! We have this fixed in https://primer.style/design using `ReactMarkdown`: https://github.com/primer/design/blob/main/src/layouts/react-component-layout.tsx#L312

Would you be interested in opening a PR to copy over that implementation into this repo?

**Comment by tomthorogood** [comment]
@colebemis Sure thing, thanks so much for the pointer!

**Comment by tomthorogood** [comment]
Just updating that I was working on this but had a First Responder rotation so was unable to finish it off. I hope to do so this week!

**Comment by tomthorogood** [comment]
An [associated PR](https://github.com/primer/react/pull/3441) has been opened for review
