### ISSUE TITLE
`ToggleSwitch` default and playground stories do not render in Storybook v7

### ISSUE THREAD

**Issue by joshblack** [primer/react#3348]
When using Storybook v7, certain `ToggleSwitch` stories do not render and contain the following error:

```
Cannot add property parameters, object is not extensible
```

Specifically:

- [ ] ToggleSwitch / Default
- [ ] ToggleSwitch / Playground
- [ ] ToggleSwitch / Docs

All other stories render as expected

**Comment by lesliecdubs** [comment]
Note: will only show up in development right now as that's where we're running Storybook v7 for now.
