### ISSUE TITLE
Flash / alert banner text wrap around icon 

### ISSUE THREAD

**Issue by lukasoppermann** [primer/react#3385]
### Description

If a flash banner has text that flows on multiple lines it wraps around the icon.

![Issue shown in react docs](https://github.com/primer/react/assets/813754/44561dbb-f07b-4a77-830f-07f9a196bf2d)

## Expected 
Text should wrap within a block and icon should be in front.

<img width="1337" alt="Screenshot of expected result" src="https://github.com/primer/react/assets/813754/eb5c8eab-44f4-44c0-b960-93e9a2a1b4dc">

### Steps to reproduce

1. Go to https://primer.style/react/Flash#with-an-icon
2. Edit the flash alert to include more text so that it wraps onto a second line

### Version

v35.25.1

### Browser

Chrome

**Comment by Shivam-Amin** [comment]
Hey there! Can I work on this issue?
- And if I understand correctly, I have to separate icon & text at some gap, as shown in expected section.

**Comment by lesliecdubs** [comment]
@Shivam-Amin yes, we would welcome the contribution! Let us know if you have questions.

> I have to separate icon & text at some gap, as shown in expected section.
Yes, the change requested is for all subsequent lines of text to be indented. You may use the Banner implementation from the sister Primer ViewComponents library as an example: https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/alpha/banner/playground

**Comment by lesliecdubs** [comment]
@Shivam-Amin can you confirm that you are running Node.js v16? You can check your node version with `node -v`. If you're not on 16, you can manage the version installed with [`nvm`](https://github.com/nvm-sh/nvm#intro).

If you haven't already checked these out, here's a link to the [contributor docs](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#developing-components) which may be helpful.

**Comment by Shivam-Amin** [comment]
@lesliecdubs, still I'm facing the same issue after switching to Node.js v16. & Do I have to install storybook in order to run the site locally?

![Regarding the error I'm facing at the time of running npm run setup](https://github.com/primer/react/assets/106419448/63fda80a-48fa-4850-b1b8-4c6193b6b90f)

**Comment by lesliecdubs** [comment]
I'm going to tag in one of our first responders to see if they can help troubleshoot.

**Comment by josepmartins** [comment]
hey @Shivam-Amin 👋 ! 

can you try doing the setup manually? this is the script https://github.com/primer/react/blob/main/script/setup, basically you'll need to:

- run `npm install` && `npm run build` on the root directory 
- `cd /docs` and then `npm install --legacy-peer-deps`

once in the main root directory you should be able to `npm run start:storybook` locally 

cc @joshblack in case there's something I'm missing 😅

**Comment by Shivam-Amin** [comment]
I still facing the same error while running ```npm run build```.
- I read the contrubution guide line & the setup script. With that I also re cloned the repo & followed the step from setup.
- I'm trying to find the solution, just thought to share with you too.

**Comment by amareshvarma** [comment]
@lesliecdubs @josepmartins I have done exactly what you have mentioned above
![Primer-error](https://github.com/primer/react/assets/31888121/c4b79c32-e572-4abf-843e-5d15b3d022d9)

**Comment by Shivam-Amin** [comment]
@amareshvarma Use node version 16.
- You can switch node version using nvm.

**Comment by amareshvarma** [comment]
@Shivam-Amin were you able to run successfully?

**Comment by Shivam-Amin** [comment]
Not yet. But trying to solve it.

**Comment by amarmanhala** [comment]
Hi @lesliecdubs Can I fix this issue?

**Comment by Shivam-Amin** [comment]
Hi @amarmanhala, As I'm not able to set up the project locally, I'm not able to solve this issue.
- But If you can go ahead, as I'm not able to work on it.
- I would love if you let me know how you set up the project locally(I mean the steps).

**Comment by lesliecdubs** [comment]
Reassigning to you, @amarmanhala!

**Comment by amarmanhala** [comment]
Thank you @lesliecdubs

**Comment by amarmanhala** [comment]
Hi @lesliecdubs, As I was working on this issue, I need your thought on it. Which icon placement option do you think is more intuitive and user-friendly? 1. Icon at the Top (screenshot 1) or Icon in the center?  I liked the 2 options.
1
<img width="1222" alt="flash1" src="https://github.com/primer/react/assets/46095869/a196a8be-0690-4c7c-a853-d8c19fd44708">
2
<img width="1221" alt="flash2" src="https://github.com/primer/react/assets/46095869/10c13385-383a-42d1-bf78-aa8edf09aa1d">

**Comment by lesliecdubs** [comment]
Hi @amarmanhala 👋🏻 Ideally, we would prefer the icon to be aligned horizontally with the first line of text, as shown in the "Expected" section of the issue summary:

<img width="1337" alt="Image of a blue banner with rounded corners, with an i information icon beside title and message text" src="https://github.com/primer/react/assets/3902488/57f61921-ee08-47df-a2de-8a279a91d85e">

**Comment by amarmanhala** [comment]
Okay got it now, Thank you @lesliecdubs for your explanation!

**Comment by broccolinisoup** [comment]
I believe this issue requires a breaking change please see https://github.com/primer/react/pull/3634#pullrequestreview-1647835818 and https://github.com/primer/react/pull/3634#issuecomment-1739930260

**Comment by lukasoppermann** [comment]
This should be changed in the new banner implementation.
