### ISSUE TITLE
Storybook components that use useEffect throw error when changing to colorMode: all

### ISSUE THREAD

**Issue by lukasoppermann** [primer/react#3406]
### Description

When the `useEffect` hook is used and one switches to `colorScheme: all` (or back) storybook throws an error.

See: https://primer.style/react/storybook/?path=/story/components-actionlist-features--child-with-side-effects&globals=colorScheme:all

<img width="1855" alt="React error on production, does not really make sense due to compression" src="https://github.com/primer/react/assets/813754/a63276c6-43a3-49f7-a67f-7259096575be">

Locally the error I get is:

```js
Error
Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```
<img width="936" alt="Screenshot of error locally (see above)" src="https://github.com/primer/react/assets/813754/f14ed8b4-5264-4ed0-abc5-4eaeee8dea9b">

Which makes sense, as we plot 9 instances instead of just one, when switching to `all`.

However I don't know how to fix this, and I am running into this issue for my own component story as well.

### Steps to reproduce

1. Go to: https://primer.style/react/storybook/?path=/story/components-actionlist-features--child-with-side-effects&globals=colorScheme:dark
2. Switch to `Color Scheme: all` in the top bar above the preview
3. Observe the error
4. A hard refresh clears the error

### Version

v35.24.0

### Browser

Chrome

**Comment by lukasoppermann** [comment]
> I've been investigating this, and the problem isn't with ThemeProvider, it's caused by hooks in stories.

Sorry if that was not clear from my description. I tried to write exactly this.

> 1. Always render 9 examples, but set display: none on the examples that don't match the current color scheme. I have a stash with this workaround.

I fear this would have a performance impact.

> 2. Force a refresh when switching to or from rendering "all" color schemes

**This is what I would currently prefer.** 👍 

> 3. Get rid of the "all" option so we only ever render a single example

The `all` option has been proven valuable in the past, its great to compare.

**Comment by mperrotti** [comment]
@lukasoppermann - I fully agree with you.

However, I'm having trouble getting the refresh to happen before the story is rendered. I'll keep you posted.
