### ISSUE TITLE
Allow custom widths for `PageLayout.Pane`

### ISSUE THREAD

**Issue by iansan5653** [primer/react#3419]
`PageLayout.Pane` only allows three values for the `width` prop: `"small" | "medium" | "large"`. The real default values of these keywords can be found here:

https://github.com/primer/react/blob/84993e7a557534047955f895e8a7889c0e6ce969/src/PageLayout/PageLayout.tsx#L526

These are fine when the pane is used for a vertical menu like it usually is, but there are other use-cases as well. For example, you might want to have a details/preview pane that takes up a third or more of the screen width by default. This should ideally be _much_ wider than `320px`. In this case, it would be very useful to be able to set a custom width.

For a resizable pane, we also need to be able to set minimum and maximum widths:

```tsx
width={{
  min: '400px',
  default: '550px',
  max: '700px'
}}
```

**Comment by mperrotti** [comment]
I see the value in making this update - especially the min/max for resizable panes. It would also be good to take a look at how this is being used and codify the most commonly used values.

@lesliecdubs - I think we can give this back to eng to implement.
