### ISSUE TITLE
ActionMenu overflow when there are too many ActionList items

### ISSUE THREAD

**Issue by lowply** [primer/react#3486]
## Summary

As shown in the following screen recording, ActionMenu overflows when there are too many ActionList items and blocks users from selecting items in the hidden part of the list.

https://github.com/primer/react/assets/18643/b9dc539d-5afe-43d5-bcb3-2ac334f43425

In the regular HTML `select` element this doesn't happen because the menu renders over the browser window. ActionMenu is, OTOH, a React component which cannot be rendered over the browser window. To mitigate this issue, there should be a scroll bar on the right side of the list so users can view and select all items regardless of the number of the items in the list.

This was originally reported in https://github.com/github/helphub/issues/4215.

### Steps to reproduce

See https://ghe.io/lowply/action-menu-example/blob/main/src/ActionMenuComponent.tsx

### Version

v35.26.0

### Browser

Safari

**Comment by amareshvarma** [comment]
I would like to work upon this issue

**Comment by amareshvarma** [comment]
@lowply The steps to reproduce is redirecting to github enterprise, can we have to available with out redirecting to github enterprise

**Comment by siddharthkp** [comment]
Hi @lowply, How do you feel about using [SelectPanel](primer.style/react/SelectPanel) instead? It has better UX (like search) for long lists

**Comment by lowply** [comment]
@amareshvarma Can you see this? https://lowply-org.github.io/action-menu/

@siddharthkp Thanks for the idea! TIL about SelectPanel and I like its scroll UI and filtering functionality. However in our use-case we can't have the selectable items - we need out users to jump to a certain URL when they click an item in the pull-down menu.

**Comment by lesliecdubs** [comment]
@lowply can you share any more information about how you're using the `ActionMenu`, and what you would expect for this experience to be for a user utilizing assistive technology like a screenreader? 

If it's a long list of items, we were wondering how you were thinking about making sure the UX of selecting an item was not too much trouble.

**Comment by lowply** [comment]
@lesliecdubs Hi 👋🏻 Please see https://github.com/github/helphub/issues/4215 for more context about this issue. Feel free to ping me on Slack if you have any other questions!

**Comment by mperrotti** [comment]
I'm wondering if a [SelectPanel](https://primer.style/design/components/selectpanel) would make more sense for this use-case. The filtering behavior would make it easier to select from a long list of options.

Either way, I think that the height of our overlays should max out at the height of the viewport and then scroll vertically within the overlay. @lesliecdubs - should we create a Primer React issue to support that behavior?

**Comment by lesliecdubs** [comment]
Thanks for jumping in @mperrotti. `SelectPanel` was also Sid's initial suggestion, but it doesn't currently support the desired functionality (https://github.com/primer/react/issues/3486#issuecomment-1668702967) which was having `SelectPanel` items direct to a URL upon selection; is that something we might want to explore supporting?

Regardless, the suggestion of maxing out overlays at the height of the viewport makes sense to me as a general optimization to guard against this type of overflow behavior. I created an issue here: https://github.com/primer/react/issues/3648, feel free to edit and add more details.

**Comment by mperrotti** [comment]
@lesliecdubs - should we close this in favor of https://github.com/primer/react/issues/3648?

**Comment by lesliecdubs** [comment]
@mperrotti good call, closing in favor of #3648. Feel free to follow along with progress there!

**Comment by lesliecdubs** [comment]
Reopening as @strackoverflow has taken a look at this but we may need more work to address #3648 overall. More to come.
