### ISSUE TITLE
[Suggestion] - add contrast property to textArea component

### ISSUE THREAD

**Issue by ValbertMartins** [primer/react#3487]
• Using forms with TextInput(using contrast) and TextArea components together

```js
<>
  <FormControl>
    <FormControl.Label>Name</FormControl.Label>
    <TextInput block contrast />
  </FormControl>

  <FormControl>
    <FormControl.Label>Name</FormControl.Label>
    <TextInput block contrast />
  </FormControl>
  
  <FormControl>
    <FormControl.Label>About</FormControl.Label>
    <Textarea block />
  </FormControl>
</>
```
• result in diferents background colors

![image](https://github.com/primer/react/assets/112519905/0da3dcd8-5bbd-4e59-8655-5e7261ff76e7)

• actually the way to fix
```jsx
<FormControl>
  <FormControl.Label>About</FormControl.Label>
  <Textarea block sx={{ backgroundColor: 'canvas.inset' }} /> 👈
</FormControl>

```
• Maybe a better way introduced in this pr #3484 

```jsx
<FormControl>
  <FormControl.Label>About</FormControl.Label>
  <Textarea block contrast/> 👈/* using contrast instead sx * /
</FormControl>
```

**Comment by mperrotti** [comment]
I think we might get rid of the `contrast` style. I'm going to ask about this in next week's Primer patterns working session.

If we _are_ getting rid of `contrast`, we should deprecate and remove it from all form controls.
If we're _not_ getting rid of `contrast`, I agree that `Textarea` should support it.

**Comment by lesliecdubs** [comment]
> I think we might get rid of the contrast style. I'm going to ask about this in next week's Primer patterns working session.

@mperrotti do you know whether it was decided to keep the `contrast` style? If so, we should consider reviewing and merging https://github.com/primer/react/pull/3484. If not, it'd be great to close these out.

**Comment by lesliecdubs** [comment]
@langermank suggests we should just add this because the `contrast` property is so pervasive in its current form. @mperrotti let us know if you have concerns, otherwise we'll move ahead.
