### ISSUE TITLE
Tooltip is broken

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#3531]
### Description

The tooltip doesn't work and the example is broken as well.

<img width="942" alt="" src="https://github.com/primer/react/assets/980622/cab3c13e-9026-4ab8-a569-fd29c56e16c6">

### Steps to reproduce

1. Go to https://primer.style/react/Tooltip
2. Try out the example

### Version

Latest

### Browser

Safari

**Comment by lesliecdubs** [comment]
@broccolinisoup could you take a quick look at this as you have been closest to ongoing work on `Tooltip` lately? 🙇🏻‍♀️  

If it seems like a more involved fix is needed (>1 hour of investigation), please leave any notes in this issue and we can decide how to prioritize from there.
