### ISSUE TITLE
Unable to style Select with sx prop

### ISSUE THREAD

**Issue by robaish** [primer/react#3599]
### Description

Hi! I'm unable to style the `Select` [component](https://github.com/primer/react/blob/main/src/Select.tsx) with the `sx` prop as follows:

`<Select sx={{ borderRadius: '4px', border: '1px solid #eee' }}>`

Looking at the component, it's border-radius is set to `inherit`, but shouldn't the `sx` prop override styling?

### Steps to reproduce

1. Import `Select` from @primer/react
2. Style with `sx` prop
3. See no change

### Version

v35.26.1

### Browser

Chrome

**Comment by lesliecdubs** [comment]
Thanks for reporting, @robaish!

@radglob would you be willing to take a quick look into this and see why `sx` isn't getting applied on `Select`? We think it might be a straightforward fix that the prop just isn't getting passed down.

**Comment by robaish** [comment]
Thanks @lesliecdubs ! 🙏

**Comment by Nagendra88688** [comment]
Hi @lesliecdubs ,
Is this issue solved or should I pick this task ?
Please let me know.

**Comment by lesliecdubs** [comment]
@Nagendra88688 I believe this issue is still outstanding. I would invite you to review the [contribution docs](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md) if you'd like to try contributing a fix.
