### ISSUE TITLE
[InlineAutocomplete] Support showing suggestions list above the insertion point

### ISSUE THREAD

**Issue by iansan5653** [primer/react#3608]
When `InlineAutocomplete` is used at the bottom of a screen, it can overflow and even cause scrollbars to appear. It would be better if it auto-positioned itself to to appear above the caret.

This is a little more challenging than just repositioning the suggestions though, because we have two conflicting goals:

1. We want to have the most-relevant suggestion be the one closest to the text, because this is the one inserted if the user presses <kbd>Enter</kbd> without navigating into the list. If it's far away, it could be confusing. 
2. For screen reader / keyboard users, we want the most-relevant suggestion to be at the top of the list so it can quickly be accessed by pressing <kbd>Down</kbd> (and because lists are naturally sorted by relevance, descending).

This works fine when the suggestions are below the text:

![screenshot of the suggestions showing that the highlighted suggestion is at the top of the list](https://github.com/primer/react/assets/2294248/b55961d9-4137-43f0-954d-1d48002130c8)

However, if we reposition the suggestions to be above the insertion point, the two goals conflict.

There are a few options here:

1. Simply reposition the suggestions, allowing the most-relevant suggestion to show up farthest from the insertion point. This is the approach taken by VSCode:
    ![screenshot of inline autocomplete in VSCode, showing the suggestions list above the insertion point and the top-most item highlighted](https://github.com/primer/react/assets/2294248/a0489e41-bbb6-4653-b067-c28d92622d7f)
2. Reposition and reverse the suggestions list so that the most-relevant suggestion is at the bottom of the list
3. Reposition and reverse the suggestions list, but keep the same order in the DOM and reverse the keyboard navigation, so that screen reader users don't experience any difference. This is the most ergonomic for screen reader users but would be confusing for sighted keyboard users

My inclination is (1), if only to be consistent with VSCode and other editors.

**Comment by rileymiller** [comment]
This would be an awesome extension to the component. I've been working on a side project off and on over the past couple of months that uses this component for custom LLM prompts and had this on my todo list to put a PR up for this. Let me know if there's anything I could help with (screenshot)
![image](https://github.com/primer/react/assets/24517783/952be680-83fa-4411-a6c0-4d27192babaf)
