### ISSUE TITLE
Customizing Primer Primitives instead of theme object

### ISSUE THREAD

**Issue by robaish** [primer/react#3659]
### Discussed in https://github.com/primer/react/discussions/3602

<div type='discussions-op-text'>

<sup>Originally posted by **robaish** August  8, 2023</sup>
**TL;DR**: is it possible to customize/define own Primitives that Primer React's `theme` object would fetch?

I'm basing a design system on Primer and I've created a `customTheme` object that's passed on to `ThemeProvider`. However, rather than e.g. defining all colors separately for each component in the `customTheme`, it would be nice to customize higher-level primitives directly. Is this possible to do and how?

There's a separate repo for [Primitives](https://github.com/primer/primitives) so I thought about forking it, and perhaps there's a way to tell Primer React or our build tool (we use Vite) to not fetch the default Primitives and instead fetch the custom Primitives.

Any ideas greatly appreciated! 🙏</div>

**Comment by joshblack** [comment]
Hi there @robaish! Replied over in the discussion here: https://github.com/primer/react/discussions/3602#discussioncomment-6855314 let me know what you think!
