### ISSUE TITLE
Theme object not referenced consistently

### ISSUE THREAD

**Issue by robaish** [primer/react#3665]
### Description

I'm using the Overlay component (in ActionMenu) and noticed that the border-radius value is defined as 12px within the Overlay component instead of referencing the theme object radii: https://github.com/primer/react/blob/main/src/Overlay/Overlay.tsx

I'm wondering why this is so? In other components, the radii are derived from the theme object so this feels inconsistent (especially as the 12px is not in the theme).

### Steps to reproduce

1. Go to the Overlay component
2. View line 66

### Version

v35.26.1

### Browser

Chrome

**Comment by amarmanhala** [comment]
Hi @lesliecdubs, Can I work on this issue?

**Comment by tallys** [comment]
Hi @amarmanhala, we're going to look at this component and triage the issue in an upcoming Primer Patterns issue. Is this an urgent change that is blocking you?

**Comment by amarmanhala** [comment]
> Hi @amarmanhala, we're going to look at this component and triage the issue in an upcoming Primer Patterns issue. Is this an urgent change that is blocking you?

Hi @tallys, Thank you for updating me. This change isn't urgent and doesn't currently block us.

**Comment by langermank** [comment]
This will be updated in the future when we tackle bringing CSS variables into Primer React. There's no harm in adding it as an option to the theme object now, but it's not a priority (to my knowledge) for the team right now.

These are the border-radius options we support: https://primer.style/primitives/storybook/?path=/story/size-functional-border--border-radius
