### ISSUE TITLE
`AvatarStack`: `disableExpand` does not disable animation when `Avatar` components within are changed

### ISSUE THREAD

**Issue by gr2m** [primer/react#3688]
### Description

follow up to https://github.com/github/github/pull/286539#discussion_r1309192548

### Steps to reproduce

https://github.com/primer/react/assets/39992/0647e600-3f25-4357-938d-8f2eb18b0018

### Version

v35.28.0

**Comment by mperrotti** [comment]
If this comes up in any planning sessions, you can assign me.
