### ISSUE TITLE
Update `@lit-labs/react` from 1.1.1 to 2.0.1

### ISSUE THREAD

**Issue by joshblack** [primer/react#3710]
This is a follow-up to our revert here: https://github.com/primer/react/pull/3708

Unfortunately, we had to rollback updating `@lit-labs/react` from v2 to v1 due to how we bundle in ESM-only modules currently in `@primer/react`.

For background, `@primer/react` ships with support for both ESM and CommonJS. However, not all the dependencies we consume provide a CommonJS compatible output. Since we depend on these dependencies and need to continue supporting ESM and CommonJS, an interim solution was created that inlined a CommonJS-compatabile version of these dependencies only for the CommonJS entrypoint.

However, packages like `@lit-labs/react` make use of the `exports` field in their `package.json` file in order to properly coordinate entrypoints depending on the environment. Specifically, v2 of this package will use an entrypoint only for Node.js if that environment is detected and one for the client in order to avoid usage of `useLayoutEffect`.

This information is lost in the current transformation and we would need to find a way to restore it in order to support `@lit-labs/react` v2 while continuing to support CommonJS.

**Comment by lesliecdubs** [comment]
Discussed at the PRC planning meeting and while we don't want this dep to get too out-of-date, it seems like there isn't an immediate need to take this on. Moving to unprioritized backlog for now, but please feel free to counter or add more context if/when we should reconsider.
