### ISSUE TITLE
Update Release Schedule workflow to account for new release cadence

### ISSUE THREAD

**Issue by joshblack** [primer/react#3711]
Currently, our [release schedule](https://github.com/primer/react/blob/main/.github/workflows/release-schedule.yml) workflow runs every week and assumes a weekly cadence. Our new release cadence is every two weeks and the workflow should be updated to reflect that.

This may require some investigation into the PagerDuty in order to get the exact schedule as it may be difficult to infer using JS directly. There is also a challenge in that it is difficult to write a CRON schedule that alternates weeks (as far as I know) so this workflow would need to be resilient to running potentially more often than necessary (every two weeks)

**Comment by lesliecdubs** [comment]
Related PR: https://github.com/primer/react/pull/3769
