### ISSUE TITLE
Update Tooltip v2 to use CSS Modules 💖

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#3767]
- Subset of https://github.com/github/primer/issues/3154

I'm creating this issue for tracking purposes. We plan to update the Tooltip v2 (draft) to use CSS modules and here are CSS variable suggestions @langermank left on the https://github.com/primer/react/pull/3394

1. https://github.com/primer/react/blob/main/src/drafts/Tooltip/Tooltip.tsx#L16

```diff
- padding: 0.5em 0.75em;
+ padding: var(--base-size-8) var(--base-size-4);
```

2. https://github.com/primer/react/blob/main/src/drafts/Tooltip/Tooltip.tsx#L44

```diff
- font: normal normal 11px/1.5 ${get('fonts.normal')};
+ font: var(--text-body-shorthand-small);
``` 

3. https://github.com/primer/react/blob/main/src/drafts/Tooltip/Tooltip.tsx#L46

```diff
-  color: ${get('colors.fg.onEmphasis')};
+  color: var(--fgColor-onEmphasis);
```

4. https://github.com/primer/react/blob/main/src/drafts/Tooltip/Tooltip.tsx#L50

```diff
-  background: ${get('colors.neutral.emphasisPlus')};
+  background: var(--bgColor-emphasis);
```

5. https://github.com/primer/react/blob/main/src/drafts/Tooltip/Tooltip.tsx#L51

```diff
-   border-radius: ${get('radii.2')};
+  border-radius: var(--borderRadius-medium);
```

**Comment by jonrohan** [comment]
Closing this to track in https://github.com/orgs/github/projects/19578/views/1 and part of https://github.com/github/primer/issues/4028
