### ISSUE TITLE
Update component layout styling to avoid `matchMedia`

### ISSUE THREAD

**Issue by joshblack** [primer/react#3771]
Context over in Slack: https://github.slack.com/archives/C01L618AEP9/p1695731160423449

Components allow for responsive positioning using props that have responsive values. These often are passed through to `useResponsiveValue` under-the-hood.

This hook is problematic for layout styling because it will only evaluate the given media queries once the JavaScript on the page is hydrated and the underlying `matchMedia` calls are evaluated. This results in a flash as the inferred value present during SSR swaps to the dynamic value for the media query.

> **Note**
> While this issue is more apparent in server-side rendering, it also exists in client-side rendering, as well

As a result, we should limit usage of `useResponsiveValue` and not use it for layout-related purposes to avoid this apparent shift. Instead, these should map to static values that tie into CSS rules that can be evaluated before JS hydrates on the page. 

For example:

```tsx
const StyledComponent = styled.div`
  [data-position="end"] {
    /* ... */
  }

  [data-position="start"] {
    /* .. */
  }
`;

function ExampleComponent({ position }) {
  return <StyledComponent data-position={position} />;
}
```

**Comment by lesliecdubs** [comment]
Suggestion from PRC planning sync: use CSS for this. Could probably leverage existing CSS but refactor it a bit.
