### ISSUE TITLE
Fork repo PRs are not deployed to GitHub Pages

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#3777]
This issue came up while I was reviewing one of the fork PRs (https://github.com/primer/react/pull/3634) that the forks don't get deployed to GitHub Pages. 

Although [the job](https://github.com/primer/react/actions/runs/6308172991/job/17126027575) runs successfully, it doesn't deploy the commit that comes from the pull request branch, rather it checkouts out main and deploy the last `SHA` of `main`. The reason of it does this is because on `pull_request_target` the `ref` is the PR base branch and the`SHA` is the last commit of the PR base branch. ([docs reference](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)). Also see this in the fork PR by visiting "Checking out the ref" section under "Checkout default branch" in the [built job](https://github.com/primer/react/actions/runs/6331617090/job/17196538829).

**Comment by siddharthkp** [comment]
> The reason of it does this is because on pull_request_target the ref is the PR base branch and theSHA is the last commit of the PR base branch.

Woooow, that means it hasn't worked in forever?!

Turns out I added `pull_request_target` 😅 in https://github.com/primer/react/pull/2207,

> Right now, forks don't get deployment previews because secrets/tokens can not be shared with forks safely.
> However, there's an event called pull_request_target, which runs github actions on the target repo (primer/react) but runs the code from the source repo (example: user/primer-react-fork), this is the perfect solution for 99% of contributions (1% is when you are making changes to github actions workflows)

**Comment by lesliecdubs** [comment]
Suggestion from PRC planning: sounds like a fix could be similar to how we have our VRT flow set up, cc @joshblack.

**Comment by joshblack** [comment]
From an implementation perspective, I think this could follow a similar flow to VRT where we basically build up things like storybook and the docs and pass those along to a separate workflow that runs on workflow_run. A rough sketch of this could be:

- Add a job to CI, or a separate workflow, that uploads a `github-pages` artifact with `upload-artifact`
  - Here is a similar step in [vrt](https://github.com/primer/react/blob/main/.github/workflows/vrt.yml#L67-L73)
- Add a `github-pages` workflow that runs on `workflow_run` after the `CI` workflow (or whatever the name is of the one created in step 1)
  - This workflow can add a conditional to only run if [CI passes](https://github.com/primer/react/blob/main/.github/workflows/update-snapshots.yml#L16-L18) or if `github-pages` exists as an artifact
  - If the workflow can download github-pages, then it can use https://github.com/actions/deploy-pages to deploy it for the pull request
