### ISSUE TITLE
The contributing docs link in the documentation is broken and shows 'not found,' but it works perfectly on primer.style/react

### ISSUE THREAD

**Issue by kondapalli19** [primer/react#3833]

**Comment by kondapalli19** [comment]
I would like to work on this issue. thankyou

**Comment by lesliecdubs** [comment]
@kondapalli19 thank for your offer to contribute! We recently shipped some updates to the primer.style documentation site. Would you mind double checking the contributing docs link to see if it's working now?

If not, could you please update the issue summary with more information about which "contributing" link was not working for you?

**Comment by kondapalli19** [comment]
@lesliecdubs Thank you for your message. I've just checked the contributing docs link, and it seems to be working perfectly fine for me. I didn't encounter any issues. If you need any further assistance or if there are any other aspects you'd like me to look into, please feel free to let me know.

**Comment by lesliecdubs** [comment]
Thanks for confirming! Since this appears to be resolved, I'm going to close this out.
