### ISSUE TITLE
NavList impossible to dynamically open with `defaultOpen`

### ISSUE THREAD

**Issue by peterbe** [primer/react#3835]
### Description

I can't open a NavList programmatically. It only stays open if you set `aria-current="page"`.

I have a nested `NavList` which contains `NavList.SubNav`. All is well, it works great. 
The list looks something like this:

- Home
- About
   - Things
   - General
      -  General 1
      -  General 2
- Contact

When I'm on `/about/things` the "About" and then "Things" is opened:

![Sample app on localhost:3000](https://github.com/primer/react/assets/26739/0f30a1ff-0540-481b-af84-65b3e0b6aed6)

But suppose I don't want it to be controlled by the URL. But some other reason. For example, I might want to expand ALL items fully all the time. 
An application of this would be if you have a tree of pages, and a search/filter and when something is searched for, I remove all that don't match but to make it clear, I want all nodes fully opened. I.e. to not depend on click state, but controlled dynamically from the outside. 

### Steps to reproduce

1. Clone `https://github.com/peterbe/primer-navlist-repro`
2. `npm install`
3. `npm run dev`
4. View on http://localhost:3000
5. Click around. And click the "Open" button

**Expected result**

That when you press "Open" ALL nodes fully expand. Nothing hidden/collapsed.

**Actual result**

Nothing happens. 

### Version

35.32.0

**Comment by siddharthkp** [comment]
Hi! 

Thanks for the repro, really appreciate it! It's in our inbox for prioritisation now, you'd hear from soon :)

Tiny optional repro tip, no big deal: Love getting a repro, I would love it even more if the repro uses the storybook setup in primer/react because then we can use the pull request tooling we have in the repo 😇

**Comment by lesliecdubs** [comment]
Thanks for filing! This sounds like a feature request as I don't believe it's functionality we had scoped in to the `NavList` originally. That said, I think it would be great for us to discuss at Primer Patterns (cc @tallys) to explore whether this is a use case we want to support.

**Comment by peterbe** [comment]
> sounds like a feature request as I don't believe it's functionality we had scoped

yeah maybe. It's unclear. If anything, it's a bug in intuition :)
You'd expect a prop called `defaultOpen` mean that it's open by default. But I can see how it can also be interpreted as "open, yes, unless there's an override reason not to".

**Comment by peterbe** [comment]
My intention, by the way, is to build a search filter above the left-hand sidebar on docs.github.com that filters the big navlist. If you type something into it, it would hide all the leafs that don't match-by-title, and hide all the parents that have 0 leafs in them. But it's not yet scoped work. Just a prototype.

**Comment by mperrotti** [comment]
@peterbe - we'll send you an invite to the next Primer patterns working session to talk through your specific use case.

**Comment by peterbe** [comment]
We chatted about this in Primer Design Pattern meeting. 
The origins of this issue was that; it's a bug (in React primer). 
But more importantly, it's worth considering if it's accessible at all, even if it was possible (...with React Primer). 

As a reminder, the prototype that stirred this looks like this:



![Docs sidebar with filter search made](https://github.com/primer/react/assets/26739/c22f5258-8618-4516-9627-592d7113c94b)

It rewrites the tree of links in the sidebar to only show leaves that match the search input and/or nodes in the tree that *contain* a leaf that matches. 
This would/could/should reduce the number of items shown so that they eyes can easily scan and find the best title to click on. 
The problem is that after the filtering has been applied you now have to click to expand the NavList tree to see the good matches. It would be easier if, typing "contain", automatically makes the sidebar look like this:



![Docs sidebar with filter search made (items expanded)](https://github.com/primer/react/assets/26739/45c49f88-f682-436f-908f-25062a482d00)

But it's not possible.


### However...

We pondered if it's even a good idea. How can it be accessible by default? Is it obvious with a live region that the listing has refreshed and is now showing matches?

Another option is that of the Microsoft Learn site. For example: https://learn.microsoft.com/en-us/azure/data-explorer/
They too have long list of options in their side bar. And they place a search input widget above the tree ("Filter by title"). But what they do is that they do an autocomplete-like widget to find within the tree. That could be an option for us (GitHub Docs) too. 

With that in mind; it's not obvious that React Primer has a bug here. Yes, it became impossible to implement the prototype the intended way, but perhaps the prototype idea was wrong in the first place. 

@mperrotti @siddharthkp Do you want to close this or leave it open?

**Comment by mperrotti** [comment]
> The origins of this issue was that; it's a bug (in React primer).

I'd argue that this isn't actually a bug. `defaultOpen` follows a common React pattern where props that start with `default` or `initial` (e.g.: `defaultValue`) are just intended to initialize state.

That being said, **I think we should close this issue**. If we find an accessible way to have a controlled NavList component, then we can revisit this.

**Comment by tallys** [comment]
Sounds good @mperrotti, we can always reopen if anything
