### ISSUE TITLE
Data table pagination breaks when setting defaultPageIndex

### ISSUE THREAD

**Issue by apataky** [primer/react#3856]
### Description

Created a data table with pagination, and when I set the `defaultPageIndex` the pagination completely bugs out. See screenshots below:

Settings the pagination:

![Image](https://github.com/primer/react/assets/36776987/115fce50-a5ae-4da3-8839-674fe1c9f19f)

Result:

![Image](https://github.com/primer/react/assets/36776987/6416d534-f47e-429c-b8ef-22215b93bcb3)

Expected to see pages with the correct page numbers (page 8 is the maximum so no 9, 10, 11, 12, 8 again), and page 7 selected and shown

### Steps to reproduce

Create a data table with a pagination component setting the `defaultPageIndex` as follows:

```tsx
import {DataTable, Table} from '@primer/react/drafts'

<Table.Pagination
  aria-label="Pagination for table"
  pageSize={10}
  totalCount={75}
  onChange={pageInfo => { }}
  defaultPageIndex={5}
/>
```

### Version

whatever is in gh/gh

### Browser

Chrome

**Comment by apataky** [comment]
@strackoverflow something else I noticed today that might be related or might be another bug--the table pagination only updates the value the first time `defaultPageIndex` is set. For example if I set it using a hook and it rerenders with a different page index it wont update the UI to show the correct page. I have to force it by updating the key on the component.

This functionality is important to me because I'm trying to tie the page index to a query string, so when a user clicks the back button and the page changes I need the correct pagination to show

**Comment by cs25-esc** [comment]
hi! is the issue resolved?

**Comment by lesliecdubs** [comment]
Hi @cs25-esc 👋  This work is currently in progress and @strackoverflow has linked a PR (refer to the timeline item just before your comment) that may resolve it. Are you looking for an opportunity to contribute to Primer React?

**Comment by cs25-esc** [comment]
Hi @lesliecdubs indeed !!
i have already forked this project and working on issue - TextInput action hover state is incorrect #3867 .
i looking for someone to assign me TextInput action hover state is incorrect #3867 .

**Comment by apataky** [comment]
@strackoverflow do you know how long it takes after the PR is merged to see the fix on dotcom?

**Comment by strackoverflow** [comment]
@apataky yes, we typically publish new releases weekly (though sometimes it ends up taking two weeks if there's an especially complex rollout). So you should hopefully see this fix within a week or two. 

We have a [release conductor](https://github.com/github/primer-engineering/blob/main/how-we-work/release-conductor.md) rotation and you can always ask the current release conductor if you need more detail!
