### ISSUE TITLE
ActionMenu: Selected items use checkboxes instead of checkmarks

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#3878]
### Description

Our [multi-selection ActionMenu](https://primer.style/react/storybook/?path=/story/components-actionmenu-features--multi-select) uses checkboxes, but this is misleading because clicking them actually closes the menu instead of just selecting an option. This isn't what people usually expect from checkboxes and it's also not in line with what [our docs](https://primer.style/components/action-menu) say.

https://github.com/primer/react/assets/980622/d39af7ed-10f7-4b15-890d-00ed144e4c01

In the [Multiple Sections](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--multiple-sections) example we don't close the menu however a menu is always expected to close upon making a selection. Therefore this example is incorrect as well.

On the other hand the [Mixed Selection](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--mixed-selection) example checkmarks behaviour and it closing the menu is correct.

**Requirements**
- Menus always close upon making a selection
- Checkboxes or other form controls are not semantically available within menus
- Multi selection and single selections are indicated by a checkmark and not a checkbox

Don't confuse a multi selection [ActionMenu](https://primer.style/components/action-menu) with a [SelectPanel](https://primer.style/components/selectpanel) dialog (semantically).

### Steps to reproduce

1. Go to the [Multi Select example](https://primer.style/react/storybook/?path=/story/components-actionmenu-features--multi-select)
1. Make a selection
1. Notice how the menu doesn't close and incorrect checkboxes are being used to indicate the selection

I've also checked our internal Figma library and the component is implemented correctly there.

### Version

v35.32.2

### Browser

Safari

**Comment by siddharthkp** [comment]
> but this is misleading because clicking them actually closes the menu instead of just selecting an option. 
 

Yep! This is intentional based on a11y feedback when ActionMenu was created. A role=menu ActionMenu should not stay open on selection. 

Once SelectPanel v2 is ready, we should start recommending that for multiple selection for use cases when the menu should remain open.

> This isn't what people usually expect from checkboxes and it's also not in line with what [our docs](https://primer.style/components/action-menu) say.

True :( The docs were updated, but the implementation were not. 

> In the [Multiple Sections](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--multiple-sections) example we don't close the menu however a menu is always expected to close upon making a selection. Therefore this example is incorrect as well.

Yes! That's definitely a bug.

> On the other hand the [Mixed Selection](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--mixed-selection) example checkmarks behaviour and it closing the menu is correct.

Mixed selection is a misleading name I think 😓 It does not mix single and multiple selection. It mixes single **selection** and an **action**.


Action items to take from here:

1. Change ActionMenu selection to always use checkboxes
2. Close menu in [Multiple Sections](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--multiple-sections) story
3. Rename "[Mixed Selection](https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--mixed-selection)" story to something else - "Selection and Actions"?

**Comment by cs25-esc** [comment]
Hi @maximedegreve / @siddharthkp 
i will provide a fix for this, can you assign this to me?

**Comment by siddharthkp** [comment]
@maximedegreve Maybe this isn't the right place to ask this line from the docs is a bit confusing...

> Single/multi select: Represented by a [check](https://primer.style/foundations/icons/check-16) and never a HTML checkbox. Trailing visuals can be used for keyboard shortcuts.

We don't use a HTML checkbox, we use a svg, so the semantics are still correct.

Using a checkmark to represent single selection feels awkward? 

https://github.com/primer/react/assets/1863771/5cb80426-b1b4-4272-bf2c-921b7ba60a47

In the video, it's not clear if more items can be selected when one item is already selected. + After selecting the second option, it feels reasonable to assume that now only the second option is selected, where in fact both the options are now selected

**Comment by siddharthkp** [comment]
Hi @cs25-esc, thanks for your enthusiasm 🙌  

Let's wait for a little bit till we can decide what the intended outcome should be :)

**Comment by cs25-esc** [comment]
sure @siddharthkp

**Comment by maximedegreve** [comment]
> Using a checkmark to represent single selection feels awkward?

It's available on both Windows and MacOS, so personally I'm used to it.
Especially for settings it does make sense.

**Example:**

![](https://github.com/primer/react/assets/980622/87ad46a6-3764-4a9f-bdca-1d61b384aba1)

**Comment by siddharthkp** [comment]
Fair.

Should we look at the usage and decide instance by instance or do you think we can do a blanket change across dotcom?

**Comment by maximedegreve** [comment]
@siddharthkp I think it would be a blanket change but either way I think we should collect a list of all the instances and check them before merging.

**Comment by lesliecdubs** [comment]
This would be good to fix when we get into the engineering phase of work for `ActionMenu` on https://github.com/github/primer/issues/2695.

**Comment by cs25-esc** [comment]
@maximedegreve will this help you?

https://github.com/primer/react/assets/68850280/81c2d230-6d69-49a9-b111-1fc761ebb99a

**Comment by cs25-esc** [comment]
here [ActionList selectionVariant](https://github.com/primer/react/blob/8cfd7f0f63598d041d736beae7324015f5c4f39e/src/ActionMenu/ActionMenu.features.stories.tsx#L114C39-L114C47) if we make selectionVariant as "single" will solve your issue, however i have also checked that multiple selections stay intact and it behaves same as earlier even if we use selectionVariant as "single"

**Comment by siddharthkp** [comment]
> here ActionList selectionVariant if we make selectionVariant as "single" will solve your issue

`secectionVariant` also has semantic meaning, not just visual. So, we would want to keep that.

**Comment by maximedegreve** [comment]
Because this fix might create complex issues internally, I'm temporarily closing it and we will focus on this similar pull request instead: - https://github.com/primer/react/pull/3994

**Comment by maximedegreve** [comment]
Because this fix might create complex issues internally, I'm temporarily closing it and we will focus on this similar pull request instead: 
- https://github.com/primer/react/pull/3994

**Comment by lesliecdubs** [comment]
@maximedegreve - I assigned this to you since I see you already opened a PR to move this forward. I also commented on the PR to see if we can't unblock next steps to roll out in dotcom.
