### ISSUE TITLE
AvatarStack disableExpand and rightAlign don't work together

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#3884]
### Description

When you right-align the AvatarStack and turn off the "expand" option, it still expands anyway.

This is not a blocker since I can turn off `alignRight` if expanding isn't needed however it still remains a bug.

https://github.com/primer/react/assets/980622/fdbaf639-824d-45ae-9dd3-db5ee83c9eea

 

### Steps to reproduce

1. Go to https://primer.style/react/storybook/?path=/story/components-avatarstack--playground&args=disableExpand:!true;alignRight:!true
2. Hover the avatar stack

### Version

v35.32.2

### Browser

Safari

**Comment by cs25-esc** [comment]
Hi @maximedegreve / @lesliecdubs / @siddharthkp how about this?

https://github.com/primer/react/assets/68850280/ff9991c1-50ce-4d93-98f9-8784c9c74901

**Comment by maximedegreve** [comment]
This looks great 🎉

**Comment by cs25-esc** [comment]
@maximedegreve can you assign this to me?
