### ISSUE TITLE
Add back in support for `string | number` for `id` of items in `Autocomplete`

### ISSUE THREAD

**Issue by joshblack** [primer/react#3886]
In v36, this type was narrowed to be a `string`. We should broaden this type back to the original to be `string | number`

This type is defined by the `items` prop in `AutocompleteMenuInternalProps`, where each item extends [`AutocompletItemProps`](https://github.com/primer/react/blob/main/src/Autocomplete/AutocompleteMenu.tsx#L47). This type extends `AutocompleteMenuItem` which creates an association between `Autocomplete` and `ActionList`, specifically `ActionListItemProps`, which is what specifies `id` as `string`.

This issue is responsible for broadening the type to `string | number` instead of purely a `string`.

**Comment by cs25-esc** [comment]
hi @joshblack can you elaborate the issue and could you please share any url and photo to check the same.
Thanks

**Comment by joshblack** [comment]
Sure thing @cs25-esc! I added some additional information, this is purely a TypeScript change that would be resolved by updating the types used so that a string or number is accepted for the `id` field.

Hope this makes sense! Let me know if you have any questions

**Comment by kudah99** [comment]
@joshblack  can i take on this issue

**Comment by joshblack** [comment]
Sure thing @kudah99! Let me know if I can help or provide assistance in any way 😄
