### ISSUE TITLE
Data table `defaultPageIndex` can only be set once

### ISSUE THREAD

**Issue by strackoverflow** [primer/react#3887]
> @strackoverflow something else I noticed today that might be related or might be another bug--the table pagination only updates the value the first time `defaultPageIndex` is set. For example if I set it using a hook and it rerenders with a different page index it wont update the UI to show the correct page. I have to force it by updating the key on the component.
> 
> This functionality is important to me because I'm trying to tie the page index to a query string, so when a user clicks the back button and the page changes I need the correct pagination to show 

 _Originally posted by @apataky in [#3856](https://github.com/primer/react/issues/3856#issuecomment-1776289017)_

**Comment by joshblack** [comment]
I think something that may be coming up is that currently DataTable is an _uncontrolled_ component and only allows folks to initialize state with `default*` values, e.g. `defaultPageIndex`. These values aren't intended to control the state and are only used to initialize it.

I opened up: https://github.com/github/primer/issues/2816 last week for adding in controlled state which I think is what would help here. This would allow folks to set the state directly in response to events outside of the `DataTable`.

**Comment by strackoverflow** [comment]
We discussed this a bit today and decided it would make sense to close this in favor of https://github.com/github/primer/issues/2816!
