### ISSUE TITLE
Accept `ReactNode` in `Button`'s `leadingVisual` and `trailingVisual` props

### ISSUE THREAD

**Issue by iansan5653** [primer/react#3948]
The `leadingVisual` and `trailingVisual` props only accept `React.ElementType<{}>`, which is any component function that takes no props. This works great for icons out of `@primer/octicons-react` because all of those icons are React components that take no props:

```tsx
<Button leadingVisual={HeartIcon}>Like this</Button>
```

That's OK, but it's really limiting. You can't easily add a trailing or leading visual that is not an icon. For example, maybe you want a [`CounterLabel`](https://primer.style/react/CounterLabel) after your button. `CounterLabel` requires children to render a count -- how can we pass this to the button? The only way is to pass a function that returns the JSX we want:

```tsx
<Button
  leadingVisual={HeartIcon}
  trailingVisual={() => <CounterLabel>12</CounterLabel>}
>Like this</Button>
```

This has several problems:

- It's awkward and unintuitive
- It breaks React performance optimization by always forcing extra renders because the prop always changes (this could be worked around by wrapping it in `useCallback`, which makes it significantly more unintuitive)
- It encourages anonymous unnamed components (that function is just a component after all) which are hard to debug

This would be significantly better if the props just accept rendered JSX via `ReactNode` instead. There's no need for the additional level of function. Icons still are easy to render, and everything else gets much easier:

```tsx
<Button
  leadingVisual={<HeartIcon />}
  trailingVisual={<CounterLabel>12</CounterLabel>}
>Like this</Button>
```

This doesn't have to be a breaking change - we can just accept `ReactElement | ReactNode`. It's easy to just change the rendering strategy based on whether the passed value is a function. Inside `Button` we can just do:

```tsx
<>
  {typeof leadingVisual === "function" ? leadingVisual() : leadingVisual}
</>
```

**Comment by joshblack** [comment]
Hey @iansan5653! Thanks for taking the time to make this issue 🙏 

This may be a potential dupe of: https://github.com/primer/react/issues/2457 (albeit that issue is using the older prop names and needs to be updated for v36 😅)

Either way, definitely agreed that these props (and others like it) should accept `ReactNode`

**Comment by iansan5653** [comment]
Looks like it :+1:

**Comment by iansan5653** [comment]
Duplicate of https://github.com/primer/react/issues/2457

**Comment by langermank** [comment]
@iansan5653 since you mentioned adding a counter label, we actually have that functionality built in: https://primer.style/react/storybook/?path=/story/components-button-features--trailing-counter&globals=colorScheme:light

**Comment by iansan5653** [comment]
Ah, we do! Not a great supporting example for sure then. Here are some other use-cases:

- Styled icons, like the leading visual on the close/reopen issue button:
    ```tsx
    <Button leadingVisual={() => <Octicon icon={ReopenIcon} color="success.fg" />}>Reopen issue</Button>
    ```
- Loading spinners for pending actions:
    ```tsx
    <Button leadingVisual={() => <Spinner />}>Save</Button>
    ```
- Keyboard shortcut hints:
    ```tsx
    <Button leadingVisual={() => <kbd>⌘↵</kbd>}>Submit</Button>
    ```
