### ISSUE TITLE
AvatarStack has a fixed width set when disableExpand is set.

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#3964]
### Description

The avatar stack with expanding disabled has fixed width set on its container and can't be changed. [This causes friction in a grid layout (internal access only)](https://github.com/github/github/assets/980622/e145c734-627f-4114-ae3a-5dbcdec1716e) where the stack is followed by text because it adds extra space for no reason.

![](https://github.com/primer/react/assets/980622/a91cd63d-2219-4d30-8023-8c590f42c626)

### Version

Latest

### Browser

Safari

**Comment by mperrotti** [comment]
I think this is intentional to prevent a layout shift when the avatars expand. What behavior do you have in mind?

**Comment by mperrotti** [comment]
I suspect that the expand behavior has been disabled in the dropdown example you shared. Is that the case? If so, we could do something to try and "trim" that extra space off when the AvatarStack doesn't need to expand.

Let me know what you think @maximedegreve

**Comment by maximedegreve** [comment]
Yup that's exactly what is happening there. If it's not expanding it would be good to not include the space and leave this up to the consumer.
