### ISSUE TITLE
Double focus outline appearing on MarkdownEditor

### ISSUE THREAD

**Issue by joshblack** [primer/react#3997]
### Description

When editing a markdown editor in React, there are two focus outlines present

### Steps to reproduce

Focus a markdown editor in React and observe the two focus outlines present

### Version

v36.3.0

**Comment by iansan5653** [comment]
Based on the recent changes to the PVC component, I think the goal here should be to only show the inner outline (the one on the `textarea` element itself). We may also want to add some margin but that's not directly related to this bug.



![PVC commentbox component, focused](https://github.com/primer/react/assets/2294248/f70099ca-e1be-4681-9691-b45f70c34be4)

**Comment by joshblack** [comment]
Issue addressed by revert and fixed in #4008 

Opened up: https://github.com/primer/react/issues/4017 for the visual change!
