### ISSUE TITLE
Putting a modal dialog in TreeView causes a crash.

### ISSUE THREAD

**Issue by keithamus** [primer/react#4015]
### Description

When adding a `<dialog>` element within the contents of a TreeView, and showing the dialog as modal, it will trap the focus to the contents of the dialog, however moving the focus causes TreeView to check where focus is, and assumes the next items to be within the TreeView. This is not the case for Dialogs.

### Steps to reproduce

1. Use a `<TreeView>`.
2. Add a `<dialog>` in the contents of the `TreeView` and call `.showModal()`
3. See an error `Element is not a treeitem`.

### Version

v36.3.1

### Browser

Chrome, Safari, Firefox, Edge, iOS Safari

**Comment by lesliecdubs** [comment]
@keithamus are you running into a crash in a particular area of the product that prompted this bug report? Understanding where this is showing up live (if at all) will help with prioritization.

**Comment by keithamus** [comment]
I've just added this issue for tracking https://github.com/primer/react/pull/4013, which is an attempt to split out the dialog work in https://github.com/primer/react/pull/3840. I discovered the crash in https://github.com/primer/react/pull/3840
