### ISSUE TITLE
Update focus style in MarkdownEditor to match changes in PVC

### ISSUE THREAD

**Issue by joshblack** [primer/react#4017]
@iansan5653 pointed this out in: https://github.com/primer/react/issues/3997#issuecomment-1836720679

> Based on the recent changes to the PVC component, I think the goal here should be to only show the inner outline (the one on the `textarea` element itself). We may also want to add some margin but that's not directly related to this bug.
>
> ![PVC commentbox component, focused](https://github.com/primer/react/assets/2294248/f70099ca-e1be-4681-9691-b45f70c34be4)

**Comment by lesliecdubs** [comment]
Proposing that this change gets bundled into `MarkdownEditor` when the component gets moved out of PRC in #3604.
