### ISSUE TITLE
Typecheck fails in v36

### ISSUE THREAD

**Issue by robaish** [primer/react#4057]
### Description

I bumped to the latest [v36](https://github.com/primer/react/releases/tag/v36.0.0) release and I'm getting the following type error in CI:

![Screen Shot 2023-12-13 at 5 25 32 PM](https://github.com/primer/react/assets/17624418/94cb9f2e-d36b-4cd7-a477-2344080f71d7)

### Steps to reproduce

1. Run a typecheck in version v36.4.0
2. See error 

### Version

v36.4.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi! 

Can you please check which typescript version are you on? (Internally we are using v5.2.2)

**Comment by robaish** [comment]
Hi @siddharthkp ! Thanks for the quick response. We're using v4.5.5.

**Comment by siddharthkp** [comment]
> We're using v4.5.5.

Looks like you will to have to upgrade to at least v4.7.4

- [errors on v4.5.5](https://www.typescriptlang.org/play?ts=4.5.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAZQBsIYA1FBgVyQB4BhCAHaZgAcwA0cAAo4asSnCQAPGEgEATAM5wA1kkoRMcfkNEA+OAF4jg4SIDa0iLKoBdBctWbExGADoAogxIIKowACrUtAD0UXBoNqJwTjDAgnAAjKRwcAD83uh+yAWBwaHcRRi+-OCCoY5gGgDqwDAAFhAcMMiYfAn29UhyLqYSxrYOMoOupllwAFzWJv2TQ+4q6lpEKGqCDPJ2s9nZwEKDcCUhAuGRa55aFX4XoRE0EjFxfUlgKWkATBInTBnFBQKAoSh2AAMbhQWniNQEoUOR3eSA0DBOMAAtGpgBoUAAjIJYxHKLEYxFwAACVBoGjQUGA3yxaIpMCiAggWI4Ag4GiQaixADcQRpkcdTlA4AB9FQaGAAMQEb1iSCFqjgbQ6IlacAA7rQdgJ8PA+bQ5YrlfraIiBZqIHBAWcWva4BoOGBILBNZEtJhoG6mDANL4AFS+MAyMVHOAuWZ5B6+B5PK7lHxVXCQRFXepNFrtTrdbgp640EbnIKXUtIGbZBaI9VS95mzAcBhwf1SgQgnB6k4iH10iRtYBQNRfH4CR1aTnwSAaDTAIlIUhAA)
- [no errors on v4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAZQBsIYA1FBgVyQB4BhCAHaZgAcwA0cAAo4asSnCQAPGEgEATAM5wA1kkoRMcfkNEA+OAF4jg4SIDa0iLKoBdBctWbExGADoAogxIIKowACrUtAD0UXBoNqJwTjDAgnAAjKRwcAD83uh+yAWBwaHcRRi+-OCCoY5gGgDqwDAAFhAcMMiYfAn29UhyLqYSxrYOMoOupllwAFzWJv2TQ+4q6lpEKGqCDPJ2s9nZwEKDcCUhAuGRa55aFX4XoRE0EjFxfUlgKWkATBInTBnFBQKAoSh2AAMbhQWniNQEoUOR3eSA0DBOMAAtGpgBoUAAjIJYxHKLEYxFwAACVBoGjQUGA3yxaIpMCiAggWI4Ag4GiQaixADcQRpkcdTlA4AB9FQaGAAMQEb1iSCFqjgbQ6IlacAA7rQdgJ8PA+bQ5YrlfraIiBZqIHBAWcWva4BoOGBILBNZEtJhoG6mDANL4AFS+MAyMVHOAuWZ5B6+B5PK7lHxVXCQRFXepNFrtTrdbgp640EbnIKXUtIGbZBaI9VS95mzAcBhwf1SgQgnB6k4iH10iRtYBQNRfH4CR1aTnwSAaDTAIlIUhAA)

**Comment by robaish** [comment]
@siddharthkp Thanks for looking into it, I appreciate it!
