### ISSUE TITLE
The popover for `UnderlineNav` is clipped in mobile viewports

### ISSUE THREAD

**Issue by joshblack** [primer/react#4059]
### Description

The popover for `UnderlineNav` is clipped in mobile viewports

### Steps to reproduce

I noticed this when using the latest repo beta opt-in 👀 

1. Visit a repo: https://github.com/primer/react
2. Scroll down to the UnderlineNav usage for the README, Code of Conduct, etc
3. Narrow the viewport` to a mobile viewport size (so that the More button is visible)
4. Activate the button to trigger the popover
5. Observe that the popover is clipped by the viewport

### Version

v36.x

### Browser

Chrome

**Comment by lesliecdubs** [comment]
@joshblack can you share a screenshot? We tried replicating by enabling the "New organization repositories view" feature preview and then testing mobile size using the reproduction steps, but couldn't see the nav getting clipped 👀

**Comment by joshblack** [comment]
@lesliecdubs definitely! Here's one:

<img alt="Image of popover clipped for underline nav" width="247" alt="Screenshot 2023-12-19 at 1 32 32 PM" src="https://github.com/primer/react/assets/3901764/927404f2-c034-428f-a8e4-471532c82321">

Basically the underline nav needs to have all items except the first one truncated to get it to happen.

**Comment by broccolinisoup** [comment]
Thanks @joshblack! Yeah this is still in the supported viewport range and we need to fix it. I guess we could leverage [anchor positioning](https://github.com/primer/behaviors/blob/main/docs/anchored-position.md#L1) here, I'll look into it 👀
