### ISSUE TITLE
Button hides count if trailingVisual is present

### ISSUE THREAD

**Issue by robaish** [primer/react#4060]
### Description

Both count and trailing visual fill the same slot, so count is not shown when trailing visual is present

```tsx
<Button count={2} trailingVisual={TriangleDownIcon}>Button</Button>
```

![count is ignored if trailingVisual is present](https://github.com/primer/react/assets/1863771/f16a5691-9e01-47a8-8ec9-b88c69658534)

    
### Version

v36.4.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Hi! 

This is not unique to SelectPanel, this is true for Button. Both `count` and `trailingVisual` fill the same slot with preference given to `trailingVisual`


![count is ignored if trailingVisual is present](https://github.com/primer/react/assets/1863771/3c06c311-f7d7-4071-8453-e2409e0c0e97)

**Comment by siddharthkp** [comment]
I can see how the API is a bit confusing 🤔 

Also, trailingAction is not yet documented: https://primer.style/components/button/react

**Comment by robaish** [comment]
Thanks again @siddharthkp ! Much appreciated 🙌
