### ISSUE TITLE
The default components running on my computer is not the same style as the one displayed on the official website

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4066]
### Description

- The appearance of the **Action Menu** component on the official website is as follows：

<img width="421" alt="Screenshot 2023-12-16 at 04 25 13" src="https://github.com/primer/react/assets/10324017/71a36051-ab7e-4c29-8626-f7bb547629ee">

- And the appearance of the **Action Menu** component running locally on my computer is different, with an anomaly in the shadow background display when hovering over items：

<img width="421" alt="Screenshot 2023-12-16 at 04 25 33" src="https://github.com/primer/react/assets/10324017/e9931cf0-5b42-40a2-bfe9-55429e67d949">

- They use the same default code segment：

```
<ActionMenu>
  <ActionMenu.Button className='mt-3'>Open menu</ActionMenu.Button>
  <ActionMenu.Overlay width=“medium”>
    <ActionList>
      <ActionList.Item onSelect={() => alert('Copy link clicked’)}>
        Copy link
        <ActionList.TrailingVisual>⌘C</ActionList.TrailingVisual>
      </ActionList.Item>
      <ActionList.Item onSelect={() => alert('Quote reply clicked’)}>
        Quote reply
        <ActionList.TrailingVisual>⌘Q</ActionList.TrailingVisual>
      </ActionList.Item>
      <ActionList.Item onSelect={() => alert('Edit comment clicked’)}>
        Edit comment
        <ActionList.TrailingVisual>⌘E</ActionList.TrailingVisual>
      </ActionList.Item>
      <ActionList.Divider />
      <ActionList.Item
        variant=“danger”
        onSelect={() => alert('Delete file clicked’)}
      >
        Delete file
        <ActionList.TrailingVisual>⌘D</ActionList.TrailingVisual>
      </ActionList.Item>
    </ActionList>
  </ActionMenu.Overlay>
</ActionMenu>
```

- This frontend testing project uses **React.js + Vite + pnpm**. The entire source code of the **App.tsx** page is as follows:

```
import './App.scss'
import '@primer/css/index.scss'
import { ActionList, ActionMenu, BaseStyles, Button, ThemeProvider } from '@primer/react'

function App() {

  return (
    <ThemeProvider colorMode='light'>
      <BaseStyles>
        <div className='d-flex flex-justify-center flex-items-center flex-column'>
          <Button className='mt-3 color-bg-accent color-fg-accent color-border-accent'>Hello button</Button>

          <ActionMenu>
            <ActionMenu.Button className='mt-3'>Open menu</ActionMenu.Button>
            <ActionMenu.Overlay width="medium">
              <ActionList>
                <ActionList.Item onSelect={() => alert('Copy link clicked')}>
                  Copy link
                  <ActionList.TrailingVisual>⌘C</ActionList.TrailingVisual>
                </ActionList.Item>
                <ActionList.Item onSelect={() => alert('Quote reply clicked')}>
                  Quote reply
                  <ActionList.TrailingVisual>⌘Q</ActionList.TrailingVisual>
                </ActionList.Item>
                <ActionList.Item onSelect={() => alert('Edit comment clicked')}>
                  Edit comment
                  <ActionList.TrailingVisual>⌘E</ActionList.TrailingVisual>
                </ActionList.Item>
                <ActionList.Divider />
                <ActionList.Item
                  variant="danger"
                  onSelect={() => alert('Delete file clicked')}
                >
                  Delete file
                  <ActionList.TrailingVisual>⌘D</ActionList.TrailingVisual>
                </ActionList.Item>
              </ActionList>
            </ActionMenu.Overlay>
          </ActionMenu>

        </div>
      </BaseStyles>
    </ThemeProvider>
  )
}

export default App
```

- The **Action List** component also has the same issue.

### Steps to reproduce

1. No solution was found on the official website or elsewhere.

### Version

v36.4.0

### Browser

Chrome, Safari, Edge

**Comment by lesliecdubs** [comment]
Hi @meiyingqishi! It seems like it's possible this style issue is occurring due to how you are combining `primer/css` and `primer/react` reusage. Please take a look at this comment https://github.com/primer/react/issues/4071#issuecomment-1861809728 and let us know if it doesn't help resolve this issue as well.

**Comment by meiyingqishi** [comment]
Thank you for your response!

This issue is not the same as #4071.

I don't believe the exception is caused by a conflict between `primer/css` and `primer/react` because even after removing the statement `import '@primer/css/index.scss’`, the issue persists, and the exception remains the same.

**Comment by meiyingqishi** [comment]
Conflict with `Tailwind`.

**Comment by meiyingqishi** [comment]
The incompatibility between @primer/react and styled-components versions resulted in an issue. The default installation of styled-components is the latest version, 6.1.8, while @primer/react is compatible with version 5.x.x. My solution is to execute `pnpm add styled-components@^5.0.0`. A preferable resolution would be for the @primer/react component team to maintain updated component versions for compatibility with newer releases.
