### ISSUE TITLE
When will there be a React version of the Action bar?

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4068]
Excuse me, when will Action bar have a React.js version?

**Comment by lesliecdubs** [comment]
👋 @meiyingqishi we are currently planning to work on developing an `ActionBar` component in Primer React in the coming months, likely to be available as a draft by April 2024. Feel free to check the [Primer status page](https://primer.style/guides/status/) and [changelog](https://github.com/primer/react/releases) for updates which will announce when the component is available.
