### ISSUE TITLE
It’s hard to use primer design system, because the documentation is very very unclear and incomplete.

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4070]
Primer Design System's colors and component designs are very beautiful, but the documentation is unclear, causing confusion and frustration. It is difficult to use and perhaps the most challenging frontend UI framework. For example, I often don't know which modules to import in a tsx file, which modules to import in an SCSS file, and the color-bg-accent that can be used in the className doesn't exist in the SCSS file as background-color: var(--color-bg-accent). I want to use colors fg.accent, bg.accent, and border.accent in React.js, but I don't know how to use them; I can only resort to using className='color-bg-accent'. There are too many problems and difficulties. Please improve the documentation, make it clearer, and guide users on how to use your framework, so users won't be left struggling, guessing, and exploring.

**Comment by lesliecdubs** [comment]
Hello @meiyingqishi 👋 I'm sorry to hear you've had trouble finding the documentation you need.

Do these pages on theming in Primer React help address your questions? https://primer.style/react/theming & https://primer.style/react/theme-reference

I'm going to go ahead and close this issue for now, but please feel free to write back with an example of where you're getting stuck if this doesn't unblock you.
