### ISSUE TITLE
Failure in execution due to compatibility issues with the Primer Design System.

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4071]
### Description

I created a **Next.js project** that utilizes the **Primer Design System** framework. While building the project with `yarn dev`, there are no issues,

<img width="643" alt="Screenshot 2023-12-17 at 03 45 32” alt=“screenshot for success" src="https://github.com/primer/react/assets/10324017/6dc6e3d2-34d6-45bf-b7a9-0f308c18e34c">

 but an error occurs when using `yarn dev —turbo`.

<img width="1000" alt="Screenshot 2023-12-17 at 03 44 51” alt=“screenshot for error" src="https://github.com/primer/react/assets/10324017/10ab97a3-6cd4-49f5-aecf-a7ca80d9a8db">

### Steps to reproduce

1. Install and initialize the project: `yarn create next-app`.
2. Add the framework: `yarn add @primer/css @primer/react @primer/octicons-react styled-components sass @emotion`.
3. Create the component `PrimerThemeProvider.tsx`
```
'use client'

import { ThemeProvider, BaseStyles } from '@primer/react'
import { StyleSheetManager } from 'styled-components'
import isPropValid from '@emotion/is-prop-valid'

export default function PrimerThemeProvider({
  colorMode,
  children,
}: {
  colorMode: 'light' | 'dark' | 'auto',
  children: React.ReactNode,
}) {
  return (
    <StyleSheetManager shouldForwardProp={isPropValid}>
      <ThemeProvider colorMode={colorMode}>
        <BaseStyles>{children}</BaseStyles>
      </ThemeProvider>
    </StyleSheetManager>
  )
}
```
4. Use the newly created theme and style management component in the **layout.tsx** file located in the root directory.
```
import type { Metadata } from 'next';
import '@primer/css/index.scss';
import './globals.scss';
import PrimerThemeProvider from './components/PrimerThemeProvider';

export const metadata: Metadata = {
  title: 'Primer Demo',
  description: 'Primer Design System framework study.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang=“en">
      <body>
        <PrimerThemeProvider colorMode='light'>
          <div className='d-flex flex-column flex-justify-center flex-items-center' id='content'>{children}</div>
        </PrimerThemeProvider>
      </body>
    </html>
  )
}
```
5. Use Primer's styles and components in the **page.tsx** file located in the root directory.
```
import { ActionList, ActionListItem, Button } from './lib/primerDesignSystem'
import { BookmarkIcon } from '@primer/octicons-react'

export default function Home() {return (
    <>
      <h1 className='mt-4 h1'>ttttt</h1>

      <button className='mt-4 btn color-bg-attention color-fg-attention color-border-attention'>button 1</button>

      <Button className='mt-4 color-bg-accent color-fg-accent color-border-accent'>Click Me</Button>

      <p className='mt-4 f3'>12312sdfsfsfs</p>

      <BookmarkIcon className="mt-4" size={24} />

      <ActionList className='mt-4' variant='inset'>
        <ActionListItem>Copy link</ActionListItem>
        <ActionListItem>Quote reply</ActionListItem>
        <ActionListItem>Edit comment</ActionListItem>
      </ActionList>
    </>
  )
}
```
- The code for primerDesignSystem is
```
'use client'

import { ActionList } from '@primer/react'

export const ActionListItem = ActionList.Item

export * from '@primer/react'
```
6. Running the test command `yarn dev` as shown above is fine. However, when exiting and then running `yarn dev —turbo`, an error occurs.

### Version

v36.2.0

### Browser

Chrome, Safari, Edge

**Comment by lesliecdubs** [comment]
Hi @meiyingqishi 👋 Sorry for the trouble you're having here.

It looks like you're trying to import `primer/css` alongside `primer/react`. You shouldn't need to utilize `primer/css` as the React components include styles alongside them. I'm going to go ahead and close this issue, but please feel free to write back if this doesn't resolve your concern. Thanks!

**Comment by meiyingqishi** [comment]
I don't think it's due to this reason because there are no issues when running with `yarn dev`. The problem only occurs when running with `yarn dev —turbo`. I'm unsure if it's a compatibility issue with the new build tool in **Next.js**, **Turbopack**, or if it's a compatibility issue with your **Primer Design System**.

**Comment by lesliecdubs** [comment]
@meiyingqishi I have to admit that I'm unfamiliar with `-turbo` and cannot confirm that Primer has been tested for complete compatibility with Turbopack. We do plan for Primer to be compatible with Next.js, so if you're able to confirm whether that is part of the problem please let us know.
