### ISSUE TITLE
SelectPanel's "Clear selection" tooltip pops automatically

### ISSUE THREAD

**Issue by robaish** [primer/react#4080]
### Description

The new `SelectPanel`'s (imported from experimental) "clear selection" tooltip pops open when opening the panel. I haven't found a way to prevent it.

![image](https://github.com/primer/react/assets/17624418/43ac57ce-4021-4dcc-a863-501f857dd5cb)

### Steps to reproduce

1. Use `SelectPanel`
2. Open it

The same behavior is visible in the [storybook example](https://primer.style/react/storybook/?path=/story/drafts-components-selectpanel--default).

### Version

v36.4.0

### Browser

Chrome

**Comment by lesliecdubs** [comment]
Thanks for the report! @siddharthkp could you take a look at this as part of your active work on the new `SelectPanel`?

**Comment by siddharthkp** [comment]
Yep, I'm tracking it here: (github staff only) https://github.com/github/primer/issues/2926

Here's the gist:

When the icon button gets focus, we show a tooltip.

When the dialog is opened, an icon button like close button or clear selection button might be auto-focused. Because the icon button gets focus, we show a tooltip.
>
> This looks perfect when the user interacts with the page with a keyboard, you see focus ring and tooltip. However, when using a mouse pointer, the icon button still gets focus (and a tooltip), but has no focus ring on it, which makes it feel like the tooltip randomly opened

**Comment by robaish** [comment]
Makes sense to me, thanks @siddharthkp !

**Comment by syedbarimanjan** [comment]
@siddharthkp are you working on this? If yes need help?

**Comment by siddharthkp** [comment]
- Update: This was fixed in https://github.com/primer/react/pull/4224, released in `primer/react@36.14.0`
