### ISSUE TITLE
TextInput.Action tooltip is clipped

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#4091]
### Description

Not sure what update cause this but currently with the default direction of the tooltip, the text is not visible because it is clipped. We should update it to use Tooltip v2 and also add a VRT test for this story.

![Text input screenshot with the trailing action is in focus and only the tooltip's caret is visible and the text of the tooltip is clipped](https://github.com/primer/react/assets/1446503/9edf4900-89ac-4b47-925a-4bfeb106b7c8)

### Steps to reproduce

1. Go to https://primer.style/react/storybook/?path=/story/components-textinput-features--with-trailing-action
2. Focus on the `X` (trailing action) or hover over it
3. Observe that the tooltip appears but it is clipped

### Version

v36.4.0

**Comment by lesliecdubs** [comment]
Assigning to @broccolinisoup and moving to "In Progress" since I saw an open PR: https://github.com/primer/react/pull/4097
