### ISSUE TITLE
Using `<Tooltip>` within `<ButtonGroup>` affects styling

### ISSUE THREAD

**Issue by tmelliottjr** [primer/react#4129]
### Description

Using `<Tooltip>` within `<ButtonGroup>` affects the group's styling.

#### Expected:

![Image showing expected output](https://github.com/primer/react/assets/13594679/064bb08f-c5eb-40b3-ad8a-f34f84db5bdd)

#### Actual:

![Image showing actual output](https://github.com/primer/react/assets/13594679/f0d18d11-a109-49c0-a7fb-c6be57a009d5)

### Steps to reproduce

```typescript
<ButtonGroup>
 <Tooltip aria-label="Some text">
  <Button>😜</Button>
 </Tooltip>
 <Tooltip aria-label="Some more text">
  <Button>😳</Button>
 </Tooltip>
 <Tooltip aria-label="Even more text">
  <Button>😭</Button>
 </Tooltip>
</ButtonGroup>
```

### Version

v36.5.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Ah, yes. This is definitely a bug!

@broccolinisoup FYI, something to take care of in https://github.com/primer/react/pull/4046 as well!

**Comment by broccolinisoup** [comment]
Thanks @siddharthkp for the ping! When the button group have text buttons with tooltip, there is a style issue there too. This time, the tooltip style is broken; doesn't have the rounded borders. I suspect this is the issue in the tooltip itself. I added this as a task under https://github.com/github/primer/issues/1244 and will look into it.

![Button group that includes three text buttons. The first one has tooltip and the tooltip appears without any radius on the borders. ](https://github.com/primer/react/assets/1446503/2f4de77c-a191-42e0-b154-953276e6282b)

**Comment by broccolinisoup** [comment]
not stale
