### ISSUE TITLE
Remove `StyledOcticon` reference in `Tooltip.mdx`

### ISSUE THREAD

**Issue by joshblack** [primer/react#4137]
> [!NOTE]
> This issue was first reported by @DavidMeu [over in Slack ](https://github.slack.com/archives/CSGAVNZ19/p1704899157705119)

This component was deprecated in v35 and removed in v36 but is still being referenced in [this example](https://primer.style/react/drafts/Tooltip#as-a-label). We should remove this from this page in our docs along with updating the side nav to be in alphabetical order (Octicon is currently in the "S" grouping in the nav)

### Checklist

- [ ] Remove `StyledOcticon` from `Tooltip.mdx`
- [ ] Update side nav to have alphabetical order with `Octicon`

**Comment by broccolinisoup** [comment]
Hi @joshblack 👋 Since you have an open PR, I assigned this issue to you but let me know if you have any concern!
