### ISSUE TITLE
Data attributes are not forward to a components

### ISSUE THREAD

**Issue by vitonsky** [primer/react#4139]
### Description

We use a `data-testid` attribute to markup a DOM for test scripts, but `MarkdownEditor` are not forward data attributes to a components (like `textarea`), so it is not possible to test interactions with editor on frontend.

I checked it as in my code as in docs https://primer.style/react/drafts/MarkdownEditor#props, i see that `MarkdownEditor` does not provide a way to forward attributes on `textarea`.

I tried to use a `name` attribute, it works, but i can't use this attribute by some reasons. I feel that component `MarkdownEditor` are blocks our development process, so if it will not be fixed we will be forced to replace this editor to some alternative solution.

Please add some way to provide data attributes to a components. It would may be implemented as additional property `dataAttributes` or you can just spread provided attributes (it looks for me that developers just missed out the code like `{...restProps}`)

### Steps to reproduce

- import `MarkdownEditor` from "@primer/react/drafts"
- set data attribute `<MarkdownEditor value={value} onChange={onChange} onRenderPreview={renderMarkdown} data-testid="testId123">`
- try to render page and explore DOM with browser inspector tool to find a `testId123`

Expected
- found a textarea element with `data-testid="testId123"`

Actual result
- nothing found

### Version

35.29.0

**Comment by broccolinisoup** [comment]
Hello @vitonsky 👋 Thanks for raising this issue. We recently deprecated the [MarkdownEditor component](https://primer.style/react/drafts/MarkdownEditor) and we are not actively resolving deprecated components' bugs. ([reference](https://github.com/primer/react/blob/main/contributor-docs/deprecating-components.md#faq)). That said, you are welcome to raise a pull request and we will make sure to review it. Please let us know if you have any concern!

**Comment by vitonsky** [comment]
@broccolinisoup what alternative component we can use instead of deprecated editor? In primer, or maybe in another package

**Comment by vitonsky** [comment]
not stale

**Comment by lesliecdubs** [comment]
Hi @vitonsky 👋  Primer does not currently offer another component option for text editing. Perhaps the open source MDXEditor https://github.com/mdx-editor/editor will meet your needs.
