### ISSUE TITLE
What data does the onSelectedChange of the SelectPanel component require in TypeScript format?

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4144]
I reviewed the usage guide for components on your latest documentation page （https://primer.style/components/selectpanel/react） and found that the introduction to component properties is not comprehensive. Some properties that can be set are not mentioned in the documentation (this is the case for many components, such as the ability to use the `sx` property, which is not included in the property descriptions). Additionally, there is a lack of detailed information on the data types and formats used for component properties. This often leaves me uncertain about what data to pass and the format it should have, leading to frequent guesswork and trial-and-error. In some cases, it's challenging to determine these details, especially when developing with TypeScript. For instance, I encountered difficulties when using the `SelectPanel` component in TypeScript this time.

I followed the example code for the `SelectPanel` component but encountered issues as the example code is incomplete. Some libraries and methods used in the example are not included, making it difficult for readers to construct these methods on their own. I suggest that the documentation be as comprehensive and detailed as possible, including the necessary import statements for libraries and methods in the example code. For instance, import statements like `import {TriangleDownIcon} from '@primer/octicons-react'` should be included in the example code.

Furthermore, it would be beneficial if the documentation uses the latest versions of development libraries. For example, in the latest version of React.js, there is no need to explicitly import and use `React`, and `useState()` can be used directly without `React.useState()`. However, the example code still uses the old version, causing errors for less experienced software engineers who might spend time searching for solutions. Keeping the documentation up-to-date with the latest library versions would help avoid these issues.

When using the SelectPanel example code from the new documentation（https://primer.style/components/selectpanel/react）, the first error I encountered was the direct usage of an undeclared `items` in the example code. I was unsure how to construct this `items`. Later, I referred to the old documentation（https://primer.style/react/SelectPanel）, which included the declaration for `items`. However, I encountered another unresolved issue. The example code contains an undeclared data type `ItemInput`, and I'm uncertain about how to construct this `ItemInput`. I am using TypeScript (I tested with JavaScript, and it ran successfully, but TypeScript requires type descriptions, which I couldn't provide since I don't know the data type structure of `ItemInput`).

Many of the previous points were suggestions. I have resolved many issues and reached this point. However, there is still one unresolved problem. The question is: What is the TypeScript type declaration for `ItemInput` (specifically, the type declaration for the `leadingVisual` value type)?

**Comment by Adityabandaru18** [comment]
@meiyingqishi I'd be glad if you assign me this task.

**Comment by broccolinisoup** [comment]
Hi @meiyingqishi 👋 Thank you for your thoughtful feedback on our documentation. We have an internal issue that collects feedback and I am going to link this issue to it. Also cc'ing our PM @dipree.

@Adityabandaru18 thanks for your willingness to work on this issue. This is more of a feedback than a bug that requires our team to go through it first. Watch [this space](https://github.com/primer/react/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22%20) to pick up any good first issues and we will be happy to help you with it!

**Comment by broccolinisoup** [comment]
Hello @meiyingqishi again, sorry I missed that you asked a question at the end.

>What is the TypeScript type declaration for ItemInput (specifically, the type declaration for the leadingVisual value type)?

it should be React.ElementType https://github.com/primer/react/blob/bs/iconbutton-tooltip/src/deprecated/ActionList/Item.tsx#L46

Let us know if you have further questions 🙌

**Comment by dipree** [comment]
@meiyingqishi thank you for the feedback. It's worth noting that we are working on a new version of the SelectPanel and that we would love to improve the documentation to make it more useful.

**Comment by meiyingqishi** [comment]
Think you for your reply @broccolinisoup.

 I still haven't resolved this issue. May I ask how to import **ItemInput** in TypeScript project?

I tried to build the ItemInput data type, but I still couldn't succeed:
```TypeScript
interface ItemInput {
    leadingVisual: React.ElementType;
    text: string;
    id: number;
}
```

Here is the complete code：
```TypeScript
import {
  useState 
} from "react";

import {
  BaseStyles,
  Box,
  Button,
  SelectPanel,
  ThemeProvider
} from "@primer/react";

import {
  TriangleDownIcon
 } from "@primer/octicons-react";

import "@primer/css/index.scss";

export default function App() {

  // I don't know how to import "ItemInput" and build it myself.
  interface ItemInput {
    leadingVisual: React.ElementType;
    text: string;
    id: number;
  }

  function getColorCircle(color: string) {
    return () => (
      <Box
        borderWidth="1px"
        borderStyle="solid"
        bg={color}
        borderColor={color}
        width={14}
        height={14}
        borderRadius={10}
        margin="auto"
      />
    )
  }

  const items = [
    {leadingVisual: getColorCircle('#a2eeef'), text: 'enhancement', id: 1},
    {leadingVisual: getColorCircle('#d73a4a'), text: 'bug', id: 2},
    {leadingVisual: getColorCircle('#0cf478'), text: 'good first issue', id: 3},
    {leadingVisual: getColorCircle('#ffd78e'), text: 'design', id: 4},
    {leadingVisual: getColorCircle('#ff0000'), text: 'blocker', id: 5},
    {leadingVisual: getColorCircle('#a4f287'), text: 'backend', id: 6},
    {leadingVisual: getColorCircle('#8dc6fc'), text: 'frontend', id: 7},
  ]

  const [selected, setSelected] = useState<ItemInput[]>([items[0], items[1]])
  const [filter, setFilter] = useState('')
  const filteredItems = items.filter(item => item.text.toLowerCase().startsWith(filter.toLowerCase()))
  const [open, setOpen] = useState(false)

  return (
    <ThemeProvider>
      <BaseStyles>
        <main className="d-flex flex-justify-center flex-items-center flex-column">

          <SelectPanel
            renderAnchor={({children, 'aria-labelledby': ariaLabelledBy, ...anchorProps}) => (
              <Button className="mt-3" trailingAction={TriangleDownIcon} aria-labelledby={` ${ariaLabelledBy}`} {...anchorProps}>
                {children || 'Select Labels'}
              </Button>
            )}
            placeholderText="Filter Labels"
            open={open}
            onOpenChange={setOpen}
            items={filteredItems}
            selected={selected}
            onSelectedChange={setSelected}
            onFilterChange={setFilter}
            showItemDividers={true}
            overlayProps={{width: 'small', height: 'xsmall'}}
          />

        </main>
      </BaseStyles>
    </ThemeProvider>
  )
}
```

Screenshot of code error prompt：
<img width="1049" alt="code-error-message" src="https://github.com/primer/react/assets/10324017/9bbaa5d1-f07b-43b5-b803-1c961d80f20f">

Screenshot of abnormal interface display (the first two options should be checked by default)：
<img width="334" alt="Screenshot 2024-01-17 at 04 06 39" src="https://github.com/primer/react/assets/10324017/8dec91cc-56bf-43fd-ad67-f42a6a4df894">

Screenshot of the abnormal interface display (the check box will not be selected by default. After clicking the option again, the text on the button will not be canceled, but duplicate items will be added continuously)：
<img width="421" alt="Screenshot 2024-01-17 at 04 09 51" src="https://github.com/primer/react/assets/10324017/33b35718-13d5-4e81-a2f5-8eefe3da3a05">

**Comment by meiyingqishi** [comment]
I have solved the last question I asked (What is the TypeScript type declaration for ItemInput (specifically, the type declaration for the leadingVisual value type) by following the solution replied by the author.

Declare the ItemInput type：
```typescript
interface ItemInput {
  leadingVisual: React.ElementType;
  text: string;
  id: number;
}
```

Create getColorCircle function：
```typescript
function getColorCircle(color: string) {
  return () => (
    <Box
      borderWidth="1px"
      borderStyle="solid"
      bg={color}
      borderColor={color}
      width={14}
      height={14}
      borderRadius={10}
      margin="auto"
    />
  )
}
```

Construct items data：
```typescript
const items = [
  {leadingVisual: getColorCircle('#a2eeef'), text: 'enhancement', id: 1},
  {leadingVisual: getColorCircle('#d73a4a'), text: 'bug', id: 2},
  {leadingVisual: getColorCircle('#0cf478'), text: 'good first issue', id: 3},
  {leadingVisual: getColorCircle('#ffd78e'), text: 'design', id: 4},
  {leadingVisual: getColorCircle('#ff0000'), text: 'blocker', id: 5},
  {leadingVisual: getColorCircle('#a4f287'), text: 'backend', id: 6},
  {leadingVisual: getColorCircle('#8dc6fc'), text: 'frontend', id: 7},
]
```

And move the **ItemInput**, **getColorCircle**, and **items** that I originally placed in the `export default function App()` outside the App function.
