### ISSUE TITLE
Checkbox label gets `not-allowed` cursor but input itself still has `pointer`

### ISSUE THREAD

**Issue by dylanatsmith** [primer/react#4171]
### Description

This is especially confusing when `FormControl.label` has `visuallyHidden`.

https://github.com/primer/react/assets/6905903/cd5a6ae9-6aa2-4c8b-96f5-8ed3ebb5929f

### Steps to reproduce

https://primer.style/react/storybook/?path=/story/components-checkbox-features--disabled

### Version

dotcom prod

### Browser

Firefox

**Comment by siddharthkp** [comment]
Definitely looks like a bug! (automatically) Added to the weekly prioritisation call.
