### ISSUE TITLE
`<ActionList.Item>` doesn't correctly handle keyboard events

### ISSUE THREAD

**Issue by tmelliottjr** [primer/react#4194]
### Description

[<ActionList.Item>](https://github.com/primer/react/blob/main/src/ActionList/Item.tsx) does not properly handle keyboard selection events when a modifier key is used.

Currently `<ActionList.Item>` registers a handler for the [`onKeyPress` event](https://github.com/primer/react/blob/691adc6ff5593f3e7e847c42bffc8bdb29d7bfab/src/ActionList/Item.tsx#L252). `keypress` events are fired when a key -or- key combination produces a character value. This works fine in most cases, but on Windows for example, <kbd>Alt+Enter</kbd> does not produce a character value and an event is not emitted.

Additionally, `keypress` is now considered an [obsolete](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#obsolete_events) event and is [no longer recommended](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event) for use. 

Separately, on Mac, the key combination <kbd>Option+Space</kbd> results in a [non-break space](https://en.wikipedia.org/wiki/Non-breaking_space) character value, which is different than typical <kbd>Space</kbd> resulting in the conditional check for `' '` on [line 231](https://github.com/primer/react/blob/691adc6ff5593f3e7e847c42bffc8bdb29d7bfab/src/ActionList/Item.tsx#L231) to fail.

### Steps to reproduce

1. Create a new [GitHub Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/creating-a-project)
2. Ensure there is a [table view](https://docs.github.com/en/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/managing-your-views) on the project
3. Click the view's option button and then choose sort by

#### Mac:
Use the keyboard to select a secondary sort by using <kbd>Option+Space</kbd> and notice selection does not get made.

#### Windows
Use the keyboard to select a secondary sort by using <kbd>Alt+Enter</kbd> and notice selection does not get made.

### Version

v36.6.0

### Browser

Chrome

**Comment by joshblack** [comment]
Hi there @tmelliottjr! Thanks for taking the time to make the issue 🙏 

When going through this during issue triage, we could totally confirm the issue and we added it to our backlog. There isn't an ETA on when this will be picked up so feel free to submit a fix for this or reach out if this is something you'd want to pair on.

Hope this makes sense, let me know if you have any questions!

**Comment by tmelliottjr** [comment]
I've taken a crack at this here: https://github.com/primer/react/pull/4212
