### ISSUE TITLE
ActionMenu.Overlay doesn't render aria attributes consistently on the same elements

### ISSUE THREAD

**Issue by skw** [primer/react#4207]
### Description

When using `aria-label` on a `ActionMenu.Overlay`

```jsx
<ActionMenu.Overlay
  role="dialog"
  aria-label="Configure vertical markers to display on roadmap"
>
...
```

the aria-label is rendered onto the dialog:

![Image](https://github.com/primer/react/assets/113158/2f940c0f-9ef2-4906-8fc7-fcf903f839e0)

but when using 

```jsx
<ActionMenu.Overlay aria-labelledby="testing">
...
```

The `aria-labelledby` is rendered onto the child menu:

![Image](https://github.com/primer/react/assets/113158/81dbacfd-d22e-433e-a2b1-a3a38ca55b6a)

I would expect that these aria attributes to be rendered both onto the dialog or that there's a way to set the `aria-labelledby` onto the dialog.

### Steps to reproduce

See description.

### Version

v36.6.0

### Browser

Chrome

**Comment by siddharthkp** [comment]
Good catch!

The intention in this component is to always label the "menu" and not the overlay container. Passing `aria-label` to the Overlay does not do that, which can be seen as a bug.

When you are marking `ActionMenu.Overlay` as `role=dialog`, would both the dialog and the menu inside the dialog have the same label? The semantics aren't super clear to met yet.
