### ISSUE TITLE
Dropdown remains fixed in place and doesn't scroll with parent container

### ISSUE THREAD

**Issue by surishubham** [primer/react#4227]
The dropdown does not move along with the page when it is open and we scroll the page.

**Comment by surishubham** [comment]
<SelectPanel
                title={`${label ? label : 'Select'}`}
                subtitle={subtitle}
                renderAnchor={({
                    children,
                    'aria-labelledby': ariaLabelledBy,
                    ...anchorProps
                }) => (
                    <Button
                        trailingAction={TriangleDownIcon}
                        trailingIcon={() => {
                            if (selected?.length > 0)
                                return <CounterLabel>{selected?.length}</CounterLabel>;

                            return null;
                        }}
                        aria-labelledby={` ${ariaLabelledBy}`}
                        {...anchorProps}
                        aria-haspopup="dialog"
                        sx={{
                            fontWeight: 600,
                            '[data-component="buttonContent"]': {
                                maxWidth: '92px',
                                justifyContent: 'start',
                                overflow: 'hidden',
                                whiteSpace: 'nowrap',
                                textOverflow: 'ellipsis',
                            },
                            '[data-component="input"]': {
                                backgroundColor: '#F7F7F7',
                            },
                        }}
                    >
                        {label}
                    </Button>
                )}
                placeholderText={placeholder ? placeholder : 'Filter List'}
                open={open}
                onOpenChange={setOpen}
                items={filteredItems}
                selected={selected}
                onSelectedChange={handleSelectedChange}
                onFilterChange={setFilter}
                showItemDividers={false}
                overlayProps={{
                    width: 'medium',
                    height: 'auto',
                    maxWidth: 'medium',
                    maxHeight: 'medium',
                    anchorSide: 'outside-bottom',
                }}
            />

**Comment by surishubham** [comment]
have code in **_https://gist.github.com/surishubham/4c2cf935e082e5c53678911a0793b5ea_**

**Comment by joshblack** [comment]
Hi there @surishubham! 👋 Thanks for taking the time to make this issue 🙏 

It seems like you're reporting an issue with the `SelectPanel` component. If so, would you mind filling out an issue using the [`Bug issue template`](https://github.com/primer/react/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml)?

Thanks!

**Comment by surishubham** [comment]
sure
