### ISSUE TITLE
Dropdown remains fixed in place and doesn't scroll with parent container

### ISSUE THREAD

**Issue by surishubham** [primer/react#4229]
### Description

The dropdown does not move along with the page when it is open and we scroll the page.

### Steps to reproduce

have code in https://gist.github.com/surishubham/4c2cf935e082e5c53678911a0793b5ea

1- Click on select panel
2- Move page with open dropdown
3- You are able too see dropdown is fixed even on page scroll

### Version

v35.26.1

### Browser

Chrome, Safari, Firefox, Edge, iOS Safari

**Comment by broccolinisoup** [comment]
Hello @surishubham 👋 Would it be possible to provide a codesandbox and/or a screen recording so that we can better understand the issue you are describing? Thank you!

**Comment by surishubham** [comment]
Hi @broccolinisoup, please find the attached video link. In the video, you can observe that the dropdown is not moving with its parent.

https://github.com/primer/react/assets/70204532/449c9c00-4b7d-4f73-8225-9ba233607cb7
