### ISSUE TITLE
Source links of the components are broken on the primer.style/react

### ISSUE THREAD

**Issue by broccolinisoup** [primer/react#4240]
### Description

We need to update our components' source links to reflect the new file paths after the monorepo changes.

As an example https://github.com/primer/react/blob/main/src/Tooltip/Tooltip.tsx should be https://github.com/primer/react/blob/main/packages/react/src/Tooltip/Tooltip.tsx

### Steps to reproduce

1. Go to https://primer.style/react
2. Go to any component page (Directly linking the component page i.e. https://primer.style/react/Tooltip redirects to the new website and view source link is not present on the new docs side)
3. Click the source link to access the source code of the component
4. Observe that the link is broken.
### Version

v36.7.2

**Comment by joshblack** [comment]
Thanks for catching this! Opened a PR over at: https://github.com/primer/react/pull/4243 to address this
