### ISSUE TITLE
(Autocomplete) - Last typed character is lost on blur, when the value matches a suggestion

### ISSUE THREAD

**Issue by timges** [primer/react#4289]
### Description

https://github.com/primer/react/assets/13063135/a908fe24-f3e3-4729-ad1b-93932a03c052

When the string you type into the autocomplete input field exactly matches a suggestion, the last character is lost on blur

### Steps to reproduce

1. Go here https://primer.style/components/autocomplete/react/alpha#examples
2. focus the autocomplete & clear the input
3. type 'css'
4. hit tab

-> last character is lost

### Version

v36.9.0

### Browser

Chrome, Safari, Firefox, Edge

**Comment by broccolinisoup** [comment]
Hi @timges 👋 Thanks for raising this issue and creating a PR to fix it! We really appreciate it 🙏 One of us from the team will review your PR hopefully soon! Thanks for contributing to Primer!
