### ISSUE TITLE
ActionList.Item danger variant changes color on hover

### ISSUE THREAD

**Issue by jdrush89** [primer/react#4296]
### Description

It looks like there are conflicting styles on ActionList.Items when using the danger variant. There are two that have the same specificity that change the color of the text on hover, and it seems like the behavior you get depends on which style sheet happens to load first.

![Image](https://github.com/primer/react/assets/955442/fa269ba7-3076-4739-a86f-6ee8cb8c8793)

### Steps to reproduce

Create an ActionList with an ActionList.Item variant="danger"
Hover over the item
Check in the inspector that there are two styles that can possibly change the color if you don't see the color change to default.

![Image](https://github.com/primer/react/assets/955442/ef692c76-f68e-4e59-a9e5-e5f053f9efd8)

### Version

v36.9.0

### Browser

Chrome

**Comment by langermank** [comment]
I'm not able to reproduce this in Storybook, can you link to the code for this specific menu? I see it in production but that item is disabled. Is it meant to be disabled in your screenshot?

**Comment by jdrush89** [comment]
The code is [here](https://github.com/github/github/blob/master/ui/packages/copilot-chat/components/Header.tsx#L376), it's not doing anything special with the styles. It's not disabled in the screenshot, you can enable the button by sending a message to start a thread.

**Comment by broccolinisoup** [comment]
@langermank we moved this to in progress since you assigned it to yourself. Let us know if you have any concern with it 🙌
