### ISSUE TITLE
IconButton is using color `fg.default` instead of `fg.muted`

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#4344]
### Description

Throughout GitHub I suddenly noticed that all our IconButton components use a `fg.default` instead of `fg.muted`. This creates inconsistencies with high surfacing areas like the global navigation or UnderlineNav where the icons are always muted. It also doesn't match the previews in our documentation.

For context our icons inside a normal button are also `fg.muted`.

![Storybook example demonstrating the issue](https://github.com/primer/react/assets/980622/e6582f72-6988-45c7-9ac5-12a0e3b5400e)

### Steps to reproduce

[Visit our storybook](https://primer.style/react/storybook/?path=/story/components-iconbutton--default&globals=colorScheme:light)

### Version

Latest

### Browser

Safari

**Comment by joshblack** [comment]
@maximedegreve just wanted to confirm, are you also seeing this behavior in PVC, as well? Was taking a look over at: https://view-components-storybook.eastus.cloudapp.azure.com/view-components/lookbook/inspect/primer/beta/icon_button/default and it seems like it may also have the same issue but wanted to confirm first.
