### ISSUE TITLE
Dialog: Focus shifts unexpectedly on opening

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#4363]
### Description

I've made a [Dialog](https://primer.style/components/dialog) that has 4 items you can choose from (ActionList items). When I open the dialog, it automatically highlights the last item you can choose.

**There are multiple problems happening here.**

- There is a visual focus state when navigating by mouse
- It focuses on the last ActionList item.

https://github.com/primer/react/assets/980622/f750b27c-8c1e-4e5d-925d-5f644d156f4e

### Steps to reproduce

1. Internally go to our [Primer Recipes](https://ui.githubapp.com/storybook/?path=/story/templates-application--narrow) example
2. Click `Assigned`

### Version

Latest

### Browser

Safari

**Comment by siddharthkp** [comment]
@maximedegreve Tried to reproduce and couldn't 🤔. Tested on Safari and Chrome



https://github.com/primer/react/assets/1863771/f66f2dcc-a5c9-4171-a62b-afc54bdffb46

**Comment by maximedegreve** [comment]
@siddharthkp I'm not sure why this works differently on mine here.

I've took a full window video to demonstrate my setup.

https://github.com/primer/react/assets/980622/63c5e7b4-98ee-4378-85ae-6a3d7e77c602

**Comment by siddharthkp** [comment]
Figured out how to reproduce this:

MacOS → Settings → Appearance → Show scroll bars → Always

![MacOS settings with always show scroll bars selected](https://github.com/user-attachments/assets/094fa2b7-a3a5-4bdf-ad90-c47632f37818)

**Comment by dipree** [comment]
@siddharthkp this is likely related, I believe it wasn't like this before we switched the component here recently 🤔:

https://github.com/user-attachments/assets/98772be2-28bf-42f1-938b-85f0832dc671

**Comment by siddharthkp** [comment]
Yep, same component. The change isn't new (July 2023) but as the Dialog gets more usage, this keeps popping up in more places

https://github.com/user-attachments/assets/653f814e-1a33-46aa-8bdf-ce12dc04def5

Notes:
1. top-layer / popover does not solve for this
2. `overscroll-behavior: contain` would help but only if the dialog has overflow not otherwise (like in the sidebar example)

@keithamus @mperrotti Do you have thoughts?

**Comment by maximedegreve** [comment]
@keithamus is correct. This is not about the scrollbars here.

**Comment by siddharthkp** [comment]
Oh, my bad. I may have mixed a different issue with this one and went on the wrong track

I tried reproducing the focus jumping and could not reproduce it in Safari or Chrome 😔 

> I presume there's a bug in our focus trap code which our React dialog is using.

That's possible, @keithamus were you able to reproduce it as well?

**Comment by siddharthkp** [comment]
Confirmed with @maximedegreve, we can't reproduce it anymore. My guess is that this was a bug in the recipes component that has now been fixed. Can reopen if we see this or a similar bug again
