### ISSUE TITLE
NavList.Item active state should show up as bold, but doesn't.

### ISSUE THREAD

**Issue by six7** [primer/react#4367]
I noticed that our [NavList in React](https://primer.style/react/NavList) doesnt show the active item with a bold font weight, whereas the Rails example and all the doc images show it as bold. 

I'd say we should treat this the same across all implementations.

![Image](https://github.com/primer/react/assets/4548309/434ad6c4-16f6-48b6-8e1a-962a76cd81ad)

![Image](https://github.com/primer/react/assets/4548309/6337473b-ff3d-4e76-a8d1-5992fa1ad0bd)

**Comment by joshblack** [comment]
Thanks @langermank for tackling this in UI mob pair! 🙌
