### ISSUE TITLE
The theme object inflates bundle size.

### ISSUE THREAD

**Issue by cihad** [primer/react#4432]
### Description

`theme` object gets total 9 `colorSchemes`. And importing these color schemes under the `themes` object does not allow tree shaking. I bundled only theme object:

![Capture](https://github.com/primer/react/assets/691189/da942bd5-bce2-4e61-9b6c-8d9adb74928b)

Only theme object took `327 Kb | gzip: 52 Kb.`

I recommend export each color scheme something like `import { light, dark } fro "@primer/react/color-schemes"`. And it can be pass the `<ThemeProvider>` as generated theme object. Because overall UI's don't need more than 2 schemes.

### Steps to reproduce

1. Go to [Stackblitz example](https://stackblitz.com/edit/vitejs-vite-rnllfg?file=vite.config.js)
2. Run `npm run build`
3. See the results.

### Version

^36.12.0

**Comment by siddharthkp** [comment]
Hi! 

Thanks for taking the time!

Good news: This is a temporary solution which will be replaced soon-ish and should lead to a much smaller bundlesize
Bad news: I don't have a exact date for you right now when that change will happen
