### ISSUE TITLE
TreeView: Remove aria-describedby when leading and trailing visuals do not exist

### ISSUE THREAD

**Issue by JelloBagel** [primer/react#4457]
### Description

We are using TreeView in the NestedListView and I came across this warning in the axe tests: `ARIA attribute element ID does not exist on the page: aria-describedby=":r3: :r4:"`. The `aria-describedby` is [set in the TreeView Primer component](https://github.com/primer/react/blob/06f57f4f6f3b75533fb50beaf9a89cf7040f8e61/packages/react/src/TreeView/TreeView.tsx#L441) by the leading visual and the trailing visual. Because the NestedListView does not use the TreeView.LeadingVisual and TreeView.TrailingVisual, the `id`s do not exist on the page.

### Steps to reproduce

1. Go to [Storybook Recipes > NestedListView > Example](https://ui.githubapp.com/storybook/?path=/story/recipes-nestedlistview--example)
2. Open Accessibility tab in the Add Ons panel
3. Click the Incomplete tab to view test warnings
4. Notice "ARIA attributes must conform to valid values"

### Version

v36.12.0

### Browser

Chrome

**Comment by patrickhlauke** [comment]
Just going to mention that having `aria-describedby` pointing to a non-existent `id` (or even having the attribute, pointing to nothing, a la `aria-describedby=""`) won't have an adverse effect as such, and is more of a "code quality" issue. Of course, if it's easy to avoid, then by all means you should go for fixing it.

**Comment by broccolinisoup** [comment]
Thanks @JelloBagel for filing this issue. We agree it is better to fix it and It is in our backlog now.

**Comment by lesliecdubs** [comment]
Not stale. 

I think there's a case to be made to include this issue in our current PRC remediation efforts: https://github.com/github/primer/issues/3453. @TylerJDev do you have any concerns with adding this issue to that scope?
