### ISSUE TITLE
Does the Primer Design System have card components or similar card-like components?

### ISSUE THREAD

**Issue by meiyingqishi** [primer/react#4460]
I recently have a need to use **Card** components, and upon checking, it seems that the **Primer Design System** does not have such a component.

Does the **Primer Design System** include **Card** components or similar card-like components?

For example, something akin to **react-bootstrap**'s [Card](https://react-bootstrap.github.io/docs/components/cards).

If not, are there any plans to develop such components in the future? I strongly recommend developing card components.

Thanks!

**Comment by broccolinisoup** [comment]
Hello! Thanks for raising this issue. We do not have a foreseeable plan to create a card component in Primer for now. Keep watching the space. I'll close the issue, feel free to re-open if you have further questions. Thanks!
