### ISSUE TITLE
`DialogV2` has incorrect names for width values

### ISSUE THREAD

**Issue by iansan5653** [primer/react#4515]
The new `Dialog` component has a `width` prop:

https://github.com/primer/react/blob/f9eae58360ebaac9f3ada777e11f954d3013782a/packages/react/src/Dialog/Dialog.tsx#L114-L121

These size names do not match the [Primer overlay primitives](https://primer.style/foundations/primitives/size#overlay).

It should be:

- xsmall: 192px
- small: 320px
- medium: 480px
- large: 640px
- xlarge: 960px

Currently the only way to make an actual `xlarge` dialog is to set the width explicitly via `sx`.

**Comment by broccolinisoup** [comment]
Thanks @iansan5653 for raising this issue. I liked it to the [epic (Staff only link)](https://github.com/github/primer/issues/2531) that we do all the dialog work. Let us know if you have any concern with it 🙌
