### ISSUE TITLE
Enhancement: Add support for flush action lists

### ISSUE THREAD

**Issue by gwwar** [primer/react#4518]
Action list items were built with the assumption that list items have some border radius on each item. Some teams are busy porting behavior and have likely chosen this component without redesigning their overall visual styles.

For example it looks like the repos team built out the Code menu with a flush style, and when hovering, there is a subtle border radius visible in the top corners. Without flush style support, there isn't a clean way of fixing this visual bug.

![Screenshot of the Code Menu component hovering over an item and with an incorrect top left and right border radius](https://github.com/primer/react/assets/1270189/82088b11-47a9-4936-b8ba-5bdcedc2c63a)

**Comment by langermank** [comment]
Thanks for opening this issue! We discussed this during our weekly React sync, and feel that we are unlikely to support a flush ActionList unless we have more cases to support. All new Primer menu components include internal padding, so ActionList styles are never full width and maintain the built in border-radius on each item. This menu could probably use a similar treatment. Closing for now and we will reopen if we decide to pursue in the future!
