### ISSUE TITLE
`Stack` `justify` prop has no effect

### ISSUE THREAD

**Issue by iansan5653** [primer/react#4577]
### Description

`Stack` accepts a `justify` prop that is supposed to align with the `justify-content` CSS property. But setting it has no effect other than setting the `data-justify` attribute on the HTML element - it doesn't update the CSS.

### Steps to reproduce

```tsx
<Stack justify="space-between">
  <span>a</span>
  <span>b</span>
</Stack>
```

### Version

v36.17.0

### Browser

Chrome

**Comment by joshblack** [comment]
Hmm, seems like we're missing the styles for this responsive prop 🤔 @langermank did we just miss these or were the lost during the transition/renames? 😅

**Comment by Adarsha186** [comment]
Hi @iansan5653 , I am looking for some open source projects to work on. If this is issue is still open and hasn't been resolved, I'm interested in contributing to this issue.

**Comment by joshblack** [comment]
Hey @Adarsha186! Thanks so much for offering to help! This had a PR open over at #4591 but just wanted to say that if there are any other issues that you're interested in helping out with definitely let us know! We always appreciate the help 🙏

**Comment by iansan5653** [comment]
@Adarsha186 of course we are always happy to accept contributions! Here's a query for unassigned issues with smaller size estimates that may be good candidates: https://github.com/primer/react/issues?q=is%3Aissue%20state%3Aopen%20no%3Aassignee%20label%3A%22size%3A%20sand%22%2C%22size%3A%20pebble%22
