### ISSUE TITLE
Consider modern `moduleResolution`

### ISSUE THREAD

**Issue by swiing** [primer/react#4623]
The typescript config sets `moduleResolution` to value `node`. This issue comments on this setting, and suggests the primer team could revise it (e.g. change to `Bundler` value?)

## From [typescript handbook](https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution)

> [node10](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node): Formerly known as node, this is the unfortunate default when module is set to commonjs. It’s a pretty good model of Node.js versions older than v12, and sometimes it’s a passable approximation of how most bundlers do module resolution. [...]
> Because Node.js v12 introduced different module resolution rules for ES modules, though, it’s a very bad model of modern versions of Node.js. It should not be used for new projects. 

Hence, the `node` value seems kindof outdated.

## From package.json

> engine.node >= v12

Hence; the `node` value seems a mismatch

## From PR #4054 

@joshblack introduces the PR with a changelog, including:

> Set `moduleResolution` to `Bundler`

However, the #4054 does not actually introduce this change. Was it the intention, but forgotten?

**Comment by joshblack** [comment]
Thanks for bringing this up @swiing! Appreciate it 🙏 

Opened a PR over at: https://github.com/primer/react/pull/4680 to address this 👍
