### ISSUE TITLE
Data Table Pagination - when the page numbers in the 1000s the page numbers are unreadable

### ISSUE THREAD

**Issue by apataky** [primer/react#4636]
### Description

You can see how the page numbers in the 1000s all seem to run together so it because hard to see what page numbers actually are:

![Image](https://github.com/primer/react/assets/36776987/4aeaf95b-92f8-45b9-bb5a-64528464681d)

Would expect to see page numbers spread out a little more

### Steps to reproduce

1. Go to a table with pagination greater than 1-2000 and go to last page

### Version

gh/gh

**Comment by lesliecdubs** [comment]
Hi, thanks for letting us know. I'm sending this over to our partners in Primer Design to see what they recommend.

**Comment by tallys** [comment]
@mperrotti should be a css fix, we'll take a look
