### ISSUE TITLE
[ActionMenu.Button] onClick doesn't function

### ISSUE THREAD

**Issue by DavidMeu** [primer/react#4647]
### Description

When trying to pass a function to `ActionMenu.Button ` it doesn't get invoked.

![Image](https://github.com/primer/react/assets/35102691/c6d77c3e-64b5-43c1-9d78-c3e28fa235ef)

### Steps to reproduce

1. Goto: https://primer.style/react/ActionMenu
2. Overload `onClick` and see it doesn't get invoked on clicking.

### Version

^36.19.1

**Comment by patrickhlauke** [comment]
Not an expert on this, but I think the idea is that you'd leverage the `onOpenChange` property on the `ActionMenu`, rather than trying to catch the click on the button itself (which already has the behaviour attached to it to open/close the menu).

**Comment by DavidMeu** [comment]
> Not an expert on this, but I think the idea is that you'd leverage the `onOpenChange` property on the `ActionMenu`, rather than trying to catch the click on the button itself (which already has the behaviour attached to it to open/close the menu).

I see what you are saying.
The thing is I just need a simple `onClick` and I don't want to recreate this state just to overload my method.

**Comment by siddharthkp** [comment]
Hey! Can confirm that the `onClick` is overwritten. Can classify as bug.

Out of curiosity, what are you planning to do in the onClick handler?

**Comment by DavidMeu** [comment]
> Hey! Can confirm that the `onClick` is overwritten. Can classify as bug.
> 
> Out of curiosity, what are you planning to do in the onClick handler?

I want to trigger a check to filter out options from the dropdown.

**Comment by siddharthkp** [comment]
> I want to trigger a check to filter out options from the dropdown.

That's interesting, can you share more? (Note: This repository is open source. Transferring issue to github/primer which is private)

**Comment by siddharthkp** [comment]
👋 @DavidMeu, this came up in the prioritisation call today. Can I get some context around what you are working on, that will help us if we need to prioritise a fix or recommend [the workaround](https://github.com/primer/react/issues/4647#issuecomment-2151954607) Patrick mentioned.

**Comment by DavidMeu** [comment]
> 👋 @DavidMeu, this came up in the prioritisation call today. Can I get some context around what you are working on, that will help us if we need to prioritise a fix or recommend [the workaround](https://github.com/primer/react/issues/4647#issuecomment-2151954607) Patrick mentioned.

This is part of [devportal](devportal.github app.com) pipeline runs.
Recently Heaven UI got deprecated and devportal will replace it by the end of the quarter.
Here is the [official release post](https://github.com/github/delivery-org/discussions/4299).

**Comment by siddharthkp** [comment]
WIP: https://github.com/primer/react/pull/4648

**Comment by siddharthkp** [comment]
Hi @DavidMeu, sorry this fell through the cracks!

Would this still be useful for you?

**Comment by DavidMeu** [comment]
> Hi [@DavidMeu](https://github.com/DavidMeu), sorry this fell through the cracks!
> 
> Would this still be useful for you?

Yes 🙏🏽

**Comment by siddharthkp** [comment]
@DavidMeu, this is now completed, should be part of the next release: https://github.com/primer/react/pull/4942
