### ISSUE TITLE
"npm run setup" doesn't exist in your package.json

### ISSUE THREAD

**Issue by MajidBabaeifar** [primer/react#4661]
### Description

"npm run setup" doesn't exist in your package.json even though you've mentioned it on your [document](https://github.com/primer/react/blob/main/contributor-docs/CONTRIBUTING.md#developing-components). 

### Steps to reproduce

Just see the link 

### Version

v36.20.0

### Browser

Chrome, Safari, Firefox, Edge

**Comment by broccolinisoup** [comment]
Hey 👋 

We have the [npm setup script](https://github.com/primer/react/blob/main/package.json#L10) on our package.json and I just tried running it and works fine!  After you clone the repo, make sure you are on the root folder `react/` and the setup should work. 

I am going to go ahead and close this issue but please feel free to re-open if there is anything I misunderstand or raise another issue if you come across any issues!
