### ISSUE TITLE
<UnderlineNav.Item /> without counter shows loading indicator

### ISSUE THREAD

**Issue by cihad** [primer/react#4672]
### Description

If `loadingCounters` is true and an `UnderlineNav.Item` does not have a `counter` prop, the loading indicator is shown. Normally, if there are 10 items, if 1 or 2 of them do not have a `counter` prop, it does not pose a problem. But if there are no counters in 5 of them, it is not a nice view.

`loadingCounters: true`:

![Screenshot 2024-06-14 115757](https://github.com/primer/react/assets/691189/7eaec651-f4e2-439b-b5bb-732bd06a1d03)

`loadingCounters: false`:
![Screenshot 2024-06-14 115648](https://github.com/primer/react/assets/691189/5190b592-1300-45ad-8e16-1089f9644082)

### Steps to reproduce

Sample view:

```jsx
<UnderlineNav aria-label="Repository" loadingCounters={true}>
  <UnderlineNav.Item>Inspect</UnderlineNav.Item>
  <UnderlineNav.Item counter={0}>Resources</UnderlineNav.Item>
  <UnderlineNav.Item counter={0}>Packages</UnderlineNav.Item>
  <UnderlineNav.Item>Code</UnderlineNav.Item>
  <UnderlineNav.Item>Docs</UnderlineNav.Item>
  <UnderlineNav.Item>Debug</UnderlineNav.Item>
</UnderlineNav>
```

### Version

36.7.1

**Comment by broccolinisoup** [comment]
Hello @cihad 👋 Thanks for raising this issue. We think it makes sense and will give it a try. Feel free to push a PR if you would like, otherwise we will move this in our backlog.
