### ISSUE TITLE
Add support for `className` to `<AnchoredOverlay>`

### ISSUE THREAD

**Issue by sampart** [primer/react#4739]
At present, `<AnchoredOverlay>` can't be assigned classes. This means that styling can't be applied to the associated overlay.

In our case, we needed to adjust its z-index, for example.

**Comment by broccolinisoup** [comment]
Hello @sampart 👋 Thanks for raising this issue. We agree that `AnchoredOverlay` should have support for `className` as same as our other components do. You are welcome to push a PR (I always appreciate contributions 🙏 ). Otherwise it is in our backlog now and we will get to it. Thanks!

**Comment by sampart** [comment]
Thank you! I'm not expecting to get time on this one myself, but I'll keep it in mind.

**Comment by romanpozdnov** [comment]
Hey everyone!

In the [PR](https://github.com/primer/react/pull/4752) above, the relevant changes have been made. Type definitions have been accounted for, and documentation has been updated.

Happy to help out!
