### ISSUE TITLE
Confusion between Dialog and DialogV1

### ISSUE THREAD

**Issue by cihad** [primer/react#4756]
### Description

There are two Dialog component under `@primer/react` package.

- Storybook Dialog addresses to `import { Dialog } from "@primer/react/lib-esm/Dialog/Dialog"`
- Storybook DialogV1: `import { Dialog } from "@primer/react"`

Please resolve these confussions.

### Steps to reproduce

1. Go to [Storybook Dialog](https://primer.style/react/storybook/?path=/story/components-dialog--default)
2. Go to [Storybook DialogV1](https://primer.style/react/storybook/?path=/story/components-dialogv1--default)
3. Repo [exports `packages/react/src/Dialog.tsx`](https://github.com/primer/react/blob/c7c0c47be3fe0d9eb526a29bccec572bb5dbbb57/packages/react/src/index.ts#L94)

### Version

36.26.0

**Comment by joshblack** [comment]
Hi there @cihad! Thanks for taking the time to make this issue.

The dialog component available from `@primer/react/experimental` is the newest version of Dialog and will be the default in the next major version of Primer React. Feel free to use that as opposed to Dialog from `@primer/react` 👍 

Hope this helps! Let me know if you have any other questions.
