### ISSUE TITLE
TextInput: Value/Placeholder font size doesn't respect it's size variant

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#4851]
### Description

We've noticed an issue on the platform where small buttons are paired with small text inputs, the text inputs use a medium font size instead of a small font-size. This creates a mismatch in the visual hierarchy, as shown below:

![Example of a list in Figma with secondary buttons. The first row has a small button with small text and the second row has a small input with medium text](https://github.com/user-attachments/assets/f0aa2aec-336f-4b4f-adec-916d04d42748)

Upon investigation, we found that small text fields are implemented correctly in Rails. However, in React and Figma, this implementation isn't consistent.

You can check the correct Rails implementation here: [Text Field Playground](https://primer-lookbook.github.com/view-components/lookbook/inspect/primer/alpha/text_field/playground?placeholder=Hello&size=small).

### Steps to reproduce

Go in Figma or the React playground and set the size to `small`. Then inspect the font-size which will indicate a medium size.

### Version

Latest

### Browser

Safari

**Comment by siddharthkp** [comment]
@maximedegreve Should this be in primer/view_components?

**Comment by lesliecdubs** [comment]
Sending this over to @langermank since she helps run the UI mob pair meeting on @tallys's recommendation 😄

**Comment by onehanddev** [comment]
Hi! @lesliecdubs @langermank 
I’m interested in working on this bug. Is it still available for someone to take? If there are any specific details I should consider, please let me know. Thanks!

**Comment by langermank** [comment]
Hey @onehanddev! Thanks for offering to help with this one. The issue came up again while we were working on another work stream, so @hussam-i-am has already started to fix it.
