### ISSUE TITLE
Spacing is off when using Banner with `hideTitle`, actions, and dismiss button

### ISSUE THREAD

**Issue by dylanatsmith** [primer/react#5050]
### Description

In the similar [With hidden title and actions](https://primer.style/react/storybook/?path=/story/drafts-components-banner-features--with-hidden-title-and-actions&globals=colorScheme:light) example, the alignment is correct. Adding the dismiss button results in too much padding below the actions wrapper.

The margin should not be applied to dismissable banners when the title is hidden.

> ![Image](https://github.com/user-attachments/assets/e6fba407-bfa4-449d-a110-96554db1c1ae)

> ![Image](https://github.com/user-attachments/assets/c4af45a6-6e79-47bf-8862-ef0181456e8c)

> ![Image](https://github.com/user-attachments/assets/a8ce82c9-10fa-4d06-ba84-d86e316be51a)

### Steps to reproduce

Example code:

```tsx
<Banner
  hideTitle
  description={<>Example description</>}
  primaryAction={<Banner.PrimaryAction>Button</Banner.PrimaryAction>}
  onDismiss={action('onDismiss')}
/>
```

### Version

dotcom (37.0.0-rc.6)

**Comment by siddharthkp** [comment]
- Maybe related: https://github.com/github/primer/issues/3720

**Comment by siddharthkp** [comment]
Thanks @dylanatsmith! Keep em coming!

- Fixed in https://github.com/primer/react/pull/5053

**Comment by dylanatsmith** [comment]
Thanks for the quick fix @siddharthkp!
