### ISSUE TITLE
KeybindingHint component styling doesn’t match global <kbd> element styling

### ISSUE THREAD

**Issue by dylanatsmith** [primer/react#5125]
### Description

The `<kbd>` element has a lil shadow/border that looks keycappy, while the `<kbd>` element output by KeybindingHint just has a border.

https://github.com/user-attachments/assets/295a4794-638b-49ff-810c-587bc2d4cc40

### Steps to reproduce

1. Compare any `<kbd>` element with any rendered `<KeybindingHint>` element

Note: I’m flagged into the CSS modules staff ship

### Version

Latest in dotcom

### Browser

Firefox

**Comment by iansan5653** [comment]
This was intentional when we originally built this for Projects; we wanted a more minimal and modern looking design that wouldn't be so distracting in menus and tooltips. The `kbd` element default styling feels targeted more for rendering in Markdown than as a keyboard shortcut hint.

**Comment by dylanatsmith** [comment]
Cool, thanks for the context!
