### ISSUE TITLE
CheckboxGroup and RadioGroup don't pair well with FormControl due to missing size variants

### ISSUE THREAD

**Issue by maximedegreve** [primer/react#5311]
When using a [CheckboxGroup](https://primer.style/react/storybook/?path=/story/components-formcontrol-features--with-checkbox-and-radio-inputs) or [RadioGroup](https://primer.style/react/storybook/?path=/story/components-formcontrol-features--with-checkbox-and-radio-inputs), it inherits a large heading. This doesn't align well with our other FormControl components, which typically use a medium font size and bold heading. Additionally, I couldn't find a group component/variant for Checkbox or Radio components in Figma.

The larger heading for CheckboxGroup and RadioGroup was likely intended to improve separation from the options. However, upon reviewing other design systems, a more consistent approach is to use regular styling for the options instead. 

![Comparison diagram showing three form designs labeled Code, Figma now, and Proposal with captions. All include a "Fruits" checkbox list for Banana, Pear, and Apple, followed by an "Other" text input field labeled Grapes. Arrows highlight hierarchy issues in "Figma now," with notes reading "Conflicting hierarchy" and "Doesn’t work well in medium size forms." The "Proposal with captions" design includes descriptive text like "Yellow and mushy" under Banana.](https://github.com/user-attachments/assets/7922e6c1-c495-41e2-8c2d-83d5d73d5af1)

I also believe we are missing size variants for those components to ensure they pair well with TextInput which has 3 different sizes.

**Comment by mperrotti** [comment]
Emily and I discussed this during the Primer patterns working session and we're on board with the proposed change.

**Comment by lukasoppermann** [comment]
Figma is update:

![Image](https://github.com/user-attachments/assets/2d291393-e4ee-4ce2-ac32-000e840b22f7)
