### ISSUE TITLE
[Bug] Invalid `line-height` CSS property for `StyledTable`

### ISSUE THREAD

**Issue by Eta0** [primer/react#5362]
# Invalid `StyledTable` `line-height`

The default `line-height` CSS property defined for a `StyledTable` uses an invalid `calc` expression, causing it to be ignored in most browsers.

https://github.com/primer/react/blob/dc2f083eb3c07a4bcb9adcf9d2e8395d4daef1a9/packages/react/src/DataTable/Table.tsx#L34

(Nearby, `--table-font-size` is defined as `0.75rem`, so this ends up as `calc(20 / 0.75rem)`).

Due to a bug in Chromium (seemingly fixed in commit chromium/chromium@9928efc7df89412bf06496c5c1025dcd286a622d), for some newer Chromium builds, this was briefly *not* ignored, and resulted in illegibly short lines. This property should be removed or changed to a more correct default like `line-height: 1.5`.

Interestingly, [this exact calculation was added as a test case](https://github.com/chromium/chromium/commit/9928efc7df89412bf06496c5c1025dcd286a622d#diff-966884bd0650a389adfe88dbb37abb35875a873de4a110a80a2ca3478d05d54cR69-R70) as an example of an invalid `calc` expression in the Chromium source tree (`calc(20 / 0.75rem)`), possibly motivated by this CSS snippet, so that should serve as quick proof that this line is currently not correct:

```js
assert_invalid_value("margin-left", "calc(20 / 0.75rem)", // invalid calc expression
                     "division by non-number");
```

**Comment by joshblack** [comment]
Hi there, @Eta0! Thanks so much for taking the time to make this issue, it was incredibly helpful 🙏 Opened up what I hope will be a fix for this over in: https://github.com/primer/react/pull/5363 so that we're no longer dividing by that `rem` value.

Thanks again!
