### ISSUE TITLE
🐛 [BUG] - Couldn't find story matching 'drafts-components-skeletontext--default'

### ISSUE THREAD

**Issue by 1chooo** [primer/react#5399]
### Describe the bug

When I visit https://primer.style/components/skeleton-text/react/draft, there is the error messages as below:

```
Couldn't find story matching 'drafts-components-skeletontext--default'.
The component failed to render properly, likely due to a configuration issue in Storybook. Here are some common causes and how you can address them:

Missing Context/Providers: You can use decorators to supply specific contexts or providers, which are sometimes necessary for components to render correctly. For detailed instructions on using decorators, please visit the [Decorators documentation](https://storybook.js.org/docs/react/writing-stories/decorators).
Misconfigured Webpack or Vite: Verify that Storybook picks up all necessary settings for loaders, plugins, and other relevant parameters. You can find step-by-step guides for configuring [Webpack](https://storybook.js.org/docs/builders/webpack) or [Vite](https://storybook.js.org/docs/builders/vite) with Storybook.
Missing Environment Variables: Your Storybook may require specific environment variables to function as intended. You can set up custom environment variables as outlined in the [Environment Variables documentation](https://storybook.js.org/docs/configure/environment-variables).
- Are you sure a story with that id exists?
- Please check your stories field of your main.js config.
- Also check the browser console and terminal for error messages.
```

Also, after clicking `View in Storybook`, we could meet the error message.

### Reproduction steps

```bash
1. Go to https://primer.style/components/skeleton-text/
2. Click on 'react'
3. Scroll down to 'Example'
4. See error
```

### Expected behavior

```bash
1. Go to https://primer.style/components/skeleton-text/
2. Click on 'react'
3. Scroll down to 'Example'
4. See the demo of skeleton-text
```

### Screenshots

<img width="1280" alt="Error in components/skeleton-text/react/draft" src="https://github.com/user-attachments/assets/9c141812-0a14-4b1e-a1de-d84c2f57372e">

<img width="1280" alt="Error in Storybook" src="https://github.com/user-attachments/assets/5d6bbb14-9b8b-479f-985e-28aac3cb5a02">

### Browsers

Chrome

### OS

Mac

**Comment by francinelucca** [comment]
Thanks for reporting! @1chooo. A [fix](https://github.com/primer/react/pull/5345) for this is already in the pipeline and should be solved on our next release!

**Comment by francinelucca** [comment]
In the meantime you can access the Skeleton Text stories directly here -> https://primer.style/react/storybook/?path=/story/experimental-components-skeleton-skeletontext--default

**Comment by francinelucca** [comment]
Working now over at https://primer.style/components/skeleton-text/react/draft, closing
