### ISSUE TITLE
`IconButton` with `variant="invisible"` has non-invisible `disabled` styling

### ISSUE THREAD

**Issue by iansan5653** [primer/react#5421]
`IconButton`'s `invisible` variant renders the button as a simple icon with no border. However, if you then apply `disabled` to that button, a border appears. The result is distracting changes (border and background) as buttons switch from disabled to enabled and back:

<img width="228" alt="Demo with enabled & disabled invisible iconbuttons. The disabled button has a border and background." src="https://github.com/user-attachments/assets/e3cea01f-a0af-4a0e-b3dd-1c2da18d31ee" />

The effect of this can be seen in practice in the comment editor toolbar when submitting issue comments: 

https://github.com/user-attachments/assets/f62917a7-b289-4574-954f-9d3609d1a260

I would expect disabled versions of `invisible` buttons to just be the same styling but with a slight fade-out (ie, translucency).

**Comment by siddharthkp** [comment]
Hi! I talked to @langermank about this and she's happy to accept a PR. I might try to create on tomorrow unless you want to race me on it 😄 

cc @francinelucca

**Comment by iansan5653** [comment]
> unless you want to race me on it

🐎 https://github.com/primer/react/pull/5423

**Comment by iansan5653** [comment]
test

**Comment by langermank** [comment]
Addressed via https://github.com/primer/react/pull/5440
