### ISSUE TITLE
`IconButton` with tooltip is incompatible with `ButtonGroup`

### ISSUE THREAD

**Issue by iansan5653** [primer/react#5452]
When `IconButton` renders tooltips, it inserts an additional element after the `button`. This in turn breaks `ButtonGroup`'s use of the `:last-child` selector to set border-radii, causing an `IconButton` at the end of a `ButtonGroup` to have square corners:

<img width="224" alt="Screenshot showing normal button and icon button inside a button group. The icon button's right-side corners are squared off even though it is the last item in the group" src="https://github.com/user-attachments/assets/32161b3a-b274-4f71-b67e-3925ec859b56" />

**Comment by langermank** [comment]
Thanks! I think this is a duplicate and we have an open PR addressing this so going to close.

PR: https://github.com/primer/react/pull/5123
Duplicate issue: https://github.com/primer/react/issues/4129

**Comment by iansan5653** [comment]
Awesome, thanks!
