### ISSUE TITLE
🐞[Bug] `as` prop not compatible with TypeScript

### ISSUE THREAD

**Issue by emplums** [primer/react#558]
Using the `as` prop in Primer Components causes issues with TypeScript because any prop on a 2nd component won't be registered as valid on the base component. Because of this, and general unpredictability of using the `as` prop (not knowing which props & styles will override other props & styles). - I think we should consider discouraging the use of it. Before we do that, we should give some thought to whether or not any component APIs should change given that we won't encourage `as` use.

**Comment by emplums** [comment]
Re: @broccolini's idea in the show & tell - a compromise that we could make would be to disallow using another component with the `as` prop, and only allowing using a native html element.

**Comment by dmarcey** [comment]
If we deprecate or discourage the use of `as` does that mean we have components like `<ButtonLink / >` and `<LinkButton />` to handle those common cases?

**Comment by emplums** [comment]
@dmarcey I think we'd still be fine if we allow native html elements to be passed to `as` - right now we encourage people to pass `link` or `a` to either `Button` or `Link` when they want the styles of the component with just the base element changed

**Comment by emplums** [comment]
but if we discourage the use of `a` all together then yes! I'm leaning towards a compromise where you can only pass a native html element to `as` - it would be relatively easy to enforce because we could only allow strings for the `as` prop instead of strings & nodes :)

**Comment by dmarcey** [comment]
Makes sense!
One other case, that I think is used is `<Link as={ReachLink} to="/" />` where you want all of the styling of a `Link` but need to use your own component.

I'm pretty sure this scenario is why we have the `to` prop on our `BaseProps` today...
