### ISSUE TITLE
📒[Docs] Writing Documentation Guide

### ISSUE THREAD

**Issue by emplums** [primer/react#678]
We should write documentation that describes how to write great documentation. This could come in the form of a documentation template, or another markup file in the root, or both!

Some things to document:
- What amount of usage guidelines should be present
- How to document props
- How to document system props
- How many examples should be shown

Leaving this open for now as we'll probably have a better idea of what the template should look like after @yaili and I work together next week :)

**Comment by yaili** [comment]
Related? https://github.com/github/design-systems/issues/250
