### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by emplums** [primer/react#746]
Let's consider adding the date picker component to Primer Components - another project team at GitHub (DM @emplums for more context) has already built this and it might make sense to add it into Primer Components. We'll likely want to sync up with a systems designer first, to come to an agreement on design, and to check if there are any design changes we need to make on the current implementation

**Comment by emplums** [comment]
@edokoa has been working through the design for this with the Insights team

**Comment by DDKatch** [comment]
Are there any chances to see the date picker component in Primer Components soon?

**Comment by lesliecdubs** [comment]
Hi @DDKatch 👋🏻 We don't currently have plans on the roadmap to add a `DatePicker` to Primer, but it is on the radar. Thanks for registering your interest.

**Comment by echarles** [comment]
DatePicker is listed as an internal component https://primer.style/product/internal-components/date-picker/

Any plan to promote it externally?

**Comment by lesliecdubs** [comment]
Hey @echarles, we don't currently have plans to promote the date picker externally. We are starting a process to review patterns intermittently for upstreaming into Primer libraries, but I don't have any plans to report yet.
