### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by emplums** [primer/react#753]
We've discussed adding a section to the documentation site for "Recipes". These would be snippets of code that showcase how to compose multiple Primer Components to build out larger pieces of UI.

Let's start coming up with a list of UI chunks that might work well in this section.

We also need to think about the best place to showcase these recipes. Should this be a page on the Primer Component docs using a live editor, or should we link to a playroom or code sandbox?

## List
- Merge Box
- GitHub Header
- Common layout patterns?
- Small dark mode theming example

## Examples in other component libraries

- [Theme UI](https://theme-ui.com/recipes/) has a recipes section in their docs, with a bunch of previews of different recipes
- [Chakra UI](https://chakra-ui.com/recipes) also has a recipes page: Form, Responsive Header

**Comment by colebemis** [comment]
Theme UI has a good recipes page: https://theme-ui.com/recipes

**Comment by yaili** [comment]
Would this be related in any way to the work of the [Contributors Group](https://github.com/github/design-systems/projects/41) where we identify upcoming patterns, prioritise that work, etc.?

**Comment by emplums** [comment]
@yaili there might be some overlap! The main purpose of the recipes is to show case what is possible to build with Primer Components, it seems like the contributors group more is more for brainstorming what new components should be built in Primer CSS?

**Comment by yaili** [comment]
@emplums Yes, you're right. I see some overlap, and since there's missing documentation in interface guidelines I wouldn't be surprised if people go to recipes to see how to put things together. 😄
