### ISSUE TITLE
Component Categorization

### ISSUE THREAD

**Issue by emplums** [primer/react#754]
Right now in Primer Components, we've got many "building block" type components, and also many "pattern" type components. 

- Does it make sense to categorize these separately on the documentation site?
- How should we define "building block" vs "pattern"?
- Should we move pattern components into their own packages?

Right now we call them "pattern" & "helper":

Pattern:
Pattern components help us repeat commonly used UI patterns and interactions in order to maintain our brand and provide a great user experience. Some examples of pattern components are Button, Avatar, or Label.

Helper:
Helper components are components that help the user achieve common CSS patterns while maintaining some control over values used. Some examples of helper components are Flex, Text, Grid, and the Position components.

**Comment by emplums** [comment]
## Examples in other design systems

### Twilio Paste
- Components (Alert, Form, Button, Heading, etc)
- Layout (Absolute, Aspect Ratio, Flex, Grid, Media Object)
- Primitives (Box, Text, Modal dialog)

### [Carbon Design System](https://www.carbondesignsystem.com/)
- Components: Components are one of the key building blocks of the design system. Each component has been designed and coded to solve a specific UI problem, such as presenting a list of options, enabling submission of a form, providing feedback to the user, and so on. All of the components in Carbon have been designed to work harmoniously together, as parts of a greater whole.

- Patterns: Patterns are best practice solutions for how a user achieves a goal. They show reusable combinations of components and templates that address common user objectives with sequences and flows.

**Notes:** Carbon seems to not have many "helper" components like position, text, etc

**Comment by emplums** [comment]
Started doing some rough diagramming in Figma: https://www.figma.com/file/6hksZw19FFbqgkDRleYZtF/React-Components?node-id=0%3A1

**Comment by dmarcey** [comment]
As another example, here is the categorization for the Azure Dev Ops Design system:
https://developer.microsoft.com/en-us/azure-devops/components

The high-level categories were:
- Structure and layout
- Input controls
- Overlays and notifications
- Data display
- Supporting visuals

Then we had another separate section for "Utilities" which were basically components, but not UI components - things like `FocusZone` or `Observer` that were used to build complex UIs, but didn't actually produce any DOM themselves.

IIRC, @yaili helped out with this initial categorization, so she would probably be a good person to talk to about these categories!

**Comment by emplums** [comment]
Oooh I really like these categories @dmarcey! I've been struggling with figuring out where things like `Avatar` would fit and I like the wording of "Supporting Visuals: for these kinds of things!

**Comment by yaili** [comment]
I feel that generally **components**, **patterns**, and **utilities** is the simplest way to have _some_ divisions without too many sections.

We divided the Components section of Azure DevOps in categories to be easier to scan, although under the hood they're all components (and in the nav they're all in alphabetical order). 😊

**Comment by yaili** [comment]
More random thoughts:
- Would this change have an effect on the other documentation sites (css, view components)? I think that the CSS docs are organised to mirror the code structure. Is that a rule for other sites? 🤔 
- Helper and utility works equally well for things that do one thing
- My thinking when I see "patterns" is that these are groups of components put together that occur frequently in the product (and that are somehow unrelated to a specific visual direction — ie a card would generally have a heading, content area, button area, regardless of how they look)
