### ISSUE TITLE
[Component Proposal] Typeahead Component

### ISSUE THREAD

**Issue by emplums** [primer/react#766]
@dmarcey has been working with the Hotline team on a typeahead component - would be great to get this in Primer Components

**Comment by emplums** [comment]
@dmarcey would you be up for taking this on?

**Comment by dmarcey** [comment]
Sure! I'll use this issue to try to start some discussion about approaches / APIs etc.

First thing (arguably the hardest!) - what should we call the thing. 🙃 

I've been calling the hook I'm using `useCombobox` as the aria role it is trying to enable is the `combobox` role. https://www.w3.org/TR/wai-aria-practices/#combobox

A quick look through https://open-ui.org/analysis/component-matrix and it looks like there are 4 `Combobox` usages and 2 `Autocomplete`. I didn't see `Typeahead` anywhere, but that also conveys what it is trying to do. I've also seen `Editable Dropdown` but that seems super implementation-y.

Any thoughts?

**Comment by jeffwilcox** [comment]
Interested to watch this one.

Ive been using (and enjoying!) Primer React for some recent project improvements, and this was one gap where I feel like I'm in hook hell trying to build this sort of thing in a few specialized scenarios.

Lots of people (even inside GH) seem to use the Material autocomplete.

**Comment by keithamus** [comment]
An accessible implementation of auto-complete is available as a Web Component with https://github.com/github/auto-complete-element, which has support for server-side fetching of new results.
