### ISSUE TITLE
Heading API

### ISSUE THREAD

**Issue by emplums** [primer/react#768]
I was thinking through our Heading component today and I think we should update it's API.

In Primer CSS, the `h1`, `h2`, `h3`, etc utility classes apply standardized font sizes for each heading tag. I think it makes sense to do the same in Primer Components.

## Proposal

I haven't tested this code yet to see if it works but this would be the general idea:

```
const getFontSize = (props) => {
  const fontSizeMap = {
    h1: get('fontSize.headings.0')(props),
    h2: get('fontSize.headings.1')(props),
    h3: get('fontSize.headings.2')(props),
    h4: get('fontSize.headings.3')(props),
    h5: get('fontSize.headings.4')(props),
    h6: get('fontSize.headings.5')(props),
  }
  return fontSizeMap[props.as]
}

const Heading = styled.h2`
  font-size: ${props => getFontSize(props)};
  font-weight: ${get('fontWeights.bold')};
  margin: 0;
  ${TYPOGRAPHY} ${COMMON};
`
```

**Comment by taylorcjohnson** [comment]
Hi @emplums! I can try getting this to work later in the week if still needed.
