### ISSUE TITLE
[Suggestion][QoL] Add a rhythm property to FlexProps

### ISSUE THREAD

**Issue by clayplumridge** [primer/react#775]
`rhythm` is an idea I've used in the past to describe containers that kept identical spacing between their children. As an example, the phrase "with an 8-pixel vertical rhythm" means that items in the vertical list were separated vertically by 8 pixels.

I've usually implemented this idea with a set of `rhythm-$direction-$spacing` CSS classes that would be applied to Flex containers like this:
```
<div className="flex-column rhythm-vertical-8>{...children}</div>
```

These classes do the following (SCSS):
```
& > :not(:firstChild) {
    margin-top: $spacing; // margin-left for horizontal
}
```

Given that Primer's `Flex` component has `flexDirection` as a prop, exposing a `rhythm` prop would allow `Flex` to automatically generate the appropriate classes.

This paradigm allows for a few things:

1. Use of components that don't actually have any `margin` props exposed without having to manage the margins of elements around them (eg. putting an SVG between two `Text` elements is currently a tiny bit painful if you want any spacing)
2. Less duplication of `mr={2}` on child components for these kinds of scenarios

I'm not sure if this is a thing that's in keeping with the Primer design system, or necessarily something that Primer wants to support as a first-class idea, but I've found a notion of this handy in the past and wanted to float it as an idea.

If this is something Primer wants to support, I'm happy to spend an hour or two this weekend opening a pull-request for it.

**Comment by emplums** [comment]
I do like this idea! If I'm understanding you correctly, it would essentially apply a standard margin to all elements wrapped in `Flex` except the first element?

> Use of components that don't actually have any margin props exposed without having to manage the margins of elements around them (eg. putting an SVG between two Text elements is currently a tiny bit painful if you want any spacing)

Just a heads up - `Text` elements do have access to all margin and padding props! All components have access to the [`COMMON` group]() of system props which include margin, padding, color, and background color

**Comment by colebemis** [comment]
This functionality would be really nice to have in Primer Components! What your proposing seems similar to the `Stack` component in the Braid Design System (https://seek-oss.github.io/braid-design-system/components/Stack), which @dmarcey and I discussed a couple weeks ago. The challenge will be designing an API that balances convenience without reinventing flexbox or grid standards.

**Comment by clayplumridge** [comment]
> I do like this idea! If I'm understanding you correctly, it would essentially apply a standard margin to all elements wrapped in Flex except the first element?

Yep! Only direct children (for obvious reasons) but it keeps spacing equal for all children of a Flex and means you have to manage less margins for scenarios where spacing is mostly consistent.

> Just a heads up - Text elements do have access to all margin and padding props! All components have access to the COMMON group of system props which include margin, padding, color, and background color

I phrased this badly; what I want is basically a margin around a standard DOM element (or another component not set up to use Primer COMMON props), but doing it reflecting the Primer Theme is a tad painful, having to set up a component via `styled` and using `themeGet` etc. Instead I put `mr` on the element preceding it, and `ml` on the element following it:
```
<Flex flexDirection="row">
    <Text ml={2}>Text here</Text>
    <LogoComponent />
    <Text mr={2}>More text!</Text>
</Flex>
```
when what I really want is:
```
<Flex flexDirection="row">
    <Text>Text here</Text>
    <LogoComponent ml={2} mr={2} />
    <Text>More text!</Text>
</Flex>
```
With `rhythm`, this visual effect is achievable via
```
<Flex flexDirection="row" rhythm={2}>
    <Text>Text here</Text>
    <LogoComponent />
    <Text>More text!</Text>
</Flex>
```
but applies `margin-left: ${themeGet(2)};` to the root element of the `LogoComponent` instead of `mr={2}` to the first `Text` element and results in fewer props to be managed for the child elements.

One possibly tricky bit would be ensuring the `ml` prop of the child elements overrides the `rhythm`, eg:
```
<Flex flexDirection="row" rhythm={2}>
    <Text>Text here</Text>
    <LogoComponent />
    <Text ml={6}>More text!</Text>
</Flex>
```

But I think that's solvable.

**Comment by BinaryMuse** [comment]
This is a neat idea, I dig it.

> One possibly tricky bit would be ensuring the `ml` prop of the child elements overrides the `rhythm`

What about a separate component, e.g.:

```javascript
import React from 'react'
import Flex from './Flex'

function Rhythm({direction, spacing, children, ...props}) {
  const margin = direction === 'row' ? 'ml' : 'mt'
  const shorthand = direction === 'row' ? 'mx' : 'my'

  const newChildren = React.Children.map(children, (child, idx) => {
    if (idx === 0) {
      return child
    } else {
      const props = {
        [margin]: child.props[margin] || child.props[shorthand] || spacing
      }
      return React.cloneElement(child, props)
    }
  })

  return (
    <Flex {...props} flexDirection={direction}>
      {newChildren}
    </Flex>
  )
}

export default Rhythm
```

```jsx
<Rhythm as={BorderBox} mb={2} p={4} direction="row" spacing={2}>
  <BorderBox>One</BorderBox>
  <BorderBox>Two</BorderBox>
  <BorderBox>Three</BorderBox>
</Rhythm>

<Rhythm as={BorderBox} mb={2} p={4} direction="row" spacing={2}>
  <BorderBox>One</BorderBox>
  <BorderBox ml={4}>Two</BorderBox>
  <BorderBox>Three</BorderBox>
</Rhythm>

<Rhythm as={BorderBox} mb={2} p={4} direction="column" spacing={2}>
  <BorderBox>One</BorderBox>
  <BorderBox>Two</BorderBox>
  <BorderBox>Three</BorderBox>
</Rhythm>

<Rhythm as={BorderBox} mb={2} p={4} direction="column" spacing={2}>
  <BorderBox>One</BorderBox>
  <BorderBox>Two</BorderBox>
  <BorderBox my={4}>Three</BorderBox>
</Rhythm>
```

![image](https://user-images.githubusercontent.com/189606/80145333-e09f9500-8564-11ea-8a44-a3ff041aea2f.png)

**Comment by BinaryMuse** [comment]
Fully enough I just realized that example could be rewritten:

```jsx
<Rhythm direction="column" spacing={2}>
  <Rhythm as={BorderBox} p={4} direction="row" spacing={2}>
    <BorderBox>One</BorderBox>
    <BorderBox>Two</BorderBox>
    <BorderBox>Three</BorderBox>
  </Rhythm>

  <Rhythm as={BorderBox} p={4} direction="row" spacing={2}>
    <BorderBox>One</BorderBox>
    <BorderBox ml={4}>Two</BorderBox>
    <BorderBox>Three</BorderBox>
  </Rhythm>

  <Rhythm as={BorderBox} p={4} direction="column" spacing={2}>
    <BorderBox>One</BorderBox>
    <BorderBox>Two</BorderBox>
    <BorderBox>Three</BorderBox>
  </Rhythm>

  <Rhythm as={BorderBox} p={4} direction="column" spacing={2}>
    <BorderBox>One</BorderBox>
    <BorderBox>Two</BorderBox>
    <BorderBox my={4}>Three</BorderBox>
  </Rhythm>
</Rhythm>
```

**Comment by clayplumridge** [comment]
@BinaryMuse 

> What about a separate component, e.g.:

I thought about doing it as a separate component, but hesitated given that it's mostly a wrapper around `Flex`, and that I think it'll be a common scenario, and that it is essentially just one prop (with, admittedly, a fair bit of backing behavior). I didn't see a compelling reason to require people to know about another component to get a superset of functionality rather than including it here. Additionally, the pattern of spinning out more and more components for individual features leads to the problem of "I need X and Y but there isn't a component that does both" once you have more than 1 logical "extension" of a given component.

That said, I really like how your implementation deals with the override problem. The one big issue with it is that it relies on all children extending and using `COMMON` props. If I want to use this with a `div` I can't do it easily, as it doesn't respect `mt` and `ml`.

> Funnily enough I just realized that example could be rewritten:
😄

**Comment by BinaryMuse** [comment]
> If I want to use this with a `div` I can't do it easily, as it doesn't respect `mt` and `ml`.

That is a good point. 🤔The specificity issue when using `:not(:last-child)` version feels quite tricky to solve, although I am far from a CSS expert.

**Comment by clayplumridge** [comment]
One possible solution:
```
.container > :not(:first-child):not(.ignore-rhythm) {
  margin-top: 4px;
}
```

Lets you do:
`<Box className='ignore-rhythm' mt={6} />`
on child elements.

Another possibility would be automatically stamping `ignore-rhythm` on all components that specify a `mt` or `ml` no matter what. Honestly, I kinda like this idea, but it really promotes Rhythm as a major concept and might require a somewhat large code change. Not really sure.

**Comment by colebemis** [comment]
> Can you expand on this a little?

Yeah, sorry for being a bit vague. I was talking in general about "Stack"-like components I've seen. For example, some of them have props like `direction="vertical"` that map to `flexDirection="column"`. I just think we need to be careful that we're not reinventing the flexbox API with different names.

Your proposal actually does a good job of not reinventing flexbox 😄

**Comment by colebemis** [comment]
Also, `gap` might be a better prop name than `rhythm` because it's consistent with the `gap` CSS property in CSS grid: https://developer.mozilla.org/en-US/docs/Web/CSS/gap

```jsx
<Flex flexDirection="row" gap={2}>
    <Text>Text here</Text>
    <LogoComponent />
    <Text>More text!</Text>
</Flex> 
```

**Comment by colebemis** [comment]
I think I found a simple way to implement this with just CSS:

[CodeSandbox demo](https://codesandbox.io/s/vibrant-ptolemy-ch1dh?file=/src/App.js)

```jsx
const Flex = styled.div`
  display: flex;

  > * + * {
    ${props => {
      const gap = themeGet("space." + props.gap)(props);
      return props.flexDirection === "column"
        ? `margin-top: ${gap}`
        : `margin-left: ${gap}`;
    }}
  }

  ${color};
  ${space};
  ${layout};
  ${flexbox};
`;

export default function App() {
  return (
    <ThemeProvider theme={theme}>
      <Flex bg="red.3" flexDirection="column" gap={2}>
        <div>one</div>
        <div>two</div>
        <div>three</div>
        <Flex mt={0}>four</Flex>
      </Flex>
    </ThemeProvider>
  );
}
```

Also, this implementation allows children to override the margin without needing any special logic 😄

**Comment by clayplumridge** [comment]
@colebemis I'll be honest, I have no idea how this works but it definitely does. Tested with:

```
export default function App() {
  return (
    <ThemeProvider theme={theme}>
      <Flex bg="red.3" flexDirection="column" gap={2}>
        <div>one</div>
        <div>two</div>
        <div>three</div>
        <div style={{ display:'flex', flexDirection: 'row', marginTop: '40px' }}>
          <div>Test one</div>
          <div>Test two</div>
        </div>
        <Flex mt={0}>four</Flex>
      </Flex>
    </ThemeProvider>
  );
}
```

And it all works entirely as I'd want it to 😄

**Comment by colebemis** [comment]
```
> * + *
```
👆 This funky-looking selector tells CSS to select any element that immediately follows a direct child of the flex container:

![image](https://user-images.githubusercontent.com/4608155/80237089-f9658480-8610-11ea-97fd-10b27581f6e3.png)

It's a combination of a [child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator) (`>`), [adjacent sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator) (`+`), and [universal selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Universal_selectors) (`*`) if you're interested in reading more.

**Comment by colebemis** [comment]
I found out that the `gap` property for flexbox containers might eventually be supported by browsers—it's working draft right now: https://www.w3.org/TR/css-align-3/#gaps. So our implementation would just be a polyfill until browsers implement the spec 😸 

![image](https://user-images.githubusercontent.com/4608155/80238556-80b3f780-8613-11ea-876b-689622f4d182.png)

**Comment by clayplumridge** [comment]
@colebemis Did that branch ever make it into PR?

**Comment by colebemis** [comment]
Sorry, things came up. I can probably get to it next week. But here's the branch if you want to take it over :) https://github.com/primer/components/tree/flex-gap
