### ISSUE TITLE
Building with rollup and @rollup/plugin-commonjs breaks theme export

### ISSUE THREAD

**Issue by SaitamaSama** [primer/react#865]
https://github.com/primer/components/blob/master/src/theme.js results in a `ReferenceError` when built with rollup and using [`@rollup/plugin-commonjs`](https://www.npmjs.com/package/@rollup/plugin-commonjs).

An MCVE is created here https://github.com/SaitamaSama/rollup-mcve

#### Steps to repro the said bug:
1. Clone the above repo `git clone https://github.com/SaitamaSama/rollup-mcve`
2. `npm i`
3. `npx rollup -c -w`
4. Open http://localhost:3000 in browser

#### Expected result
A button is mounted on the DOM.

#### Current Result:
```
ReferenceError: require is not defined
```

**Comment by SaitamaSama** [comment]
Some thing that seems to work instead of the `require`:
```diff
+import {colors, theme} from '@primer/components/lib/theme-preval';
-const themeExport = require('./theme-preval')
-const {theme, colors} = themeExport
```

**Comment by emplums** [comment]
Thanks for the heads up! We're doing a bunch of work on the theme right now and will keep this in mind!
