### ISSUE TITLE
[Component Proposal] UnsetButton

### ISSUE THREAD

**Issue by emplums** [primer/react#931]
(moved over from https://github.com/github/design-systems/issues/860, thanks @smockle 👋 !)
## Problem
Occasionally it’s useful to add an interactive element with the semantics of button (correctly represented in the AT)—but without its visual styles.

## Solution
Other teams at GitHub spread the following object in sx props to destyle Buttons:

// Removes most of 'button'’s visual appearance, so it can be used for functionality/accessibility
// in situations (e.g. 'SelectMenu'’s trigger and menu items) where button styles are undesirable.
export const unstyledButtonStyles = {
    background: "transparent",
    border: 0,
    boxShadow: "unset",
    cursor: "pointer",
    width: "100%"
};

Alternatively, an UnstyledButton component, defined using styled(button), could be provided. This is challenging to use in the SelectMenu, because as="summary" breaks the styled wrapper.

**Comment by velocity23** [comment]
Might try this... my first open source contribution so we'll see how I go.

**Comment by velocity23** [comment]
PR is open and has been for some time now. Anyone able to take a look?
