### ISSUE TITLE
[Perf] Don't render select menu content unless menu is open

### ISSUE THREAD

**Issue by emplums** [primer/react#946]
Right now, we render all of the content inside of select menus into the DOM tree even when modals aren't open (because we rely on the `details` element to show/hide content.

This is causing performance issues in applications where there are a large number of modals on the page at any give time, each one with a decent amount of content in them.

We should explore only rendering the modal content if the modal is open. This might lead to needing to detach the SelectMenu from relying on native `details` behavior

**Comment by emplums** [comment]
Note: doing this will break `autofocus` behaviors

**Comment by colebemis** [comment]
We will soon be deprecating SelectMenu in favor of SelectPanel
