### ISSUE TITLE
[Component Proposal] Details reset + details caret

### ISSUE THREAD

**Issue by emplums** [primer/react#994]
## Description
Primer CSS has the `details-reset` class which removes the caret from the summary and `details-caret` to add a GitHub styled caret back to the summary element.

### Design
- [x] Design is finalized. Link to mockups/prototypes: https://primer.style/css/utilities/details#custom-caret

### Component API
We should either 
- Add a `reset` and `caret` prop to the Details component
- Create a new button that is meant to be used as a summary for Details components

### Usage
Describe how the component should be used, and/or link to usage guidelines.

## Implementation
Can be implemented by anyone

## Timeline
None

**Comment by nodeicode** [comment]
Hey guys,

Here the Base button Component using the ```as= "summary" ``` prop seems to reset the default left triangle that we get from HTML styles already.   
  
I think a reset prop works if someone is using the summary tag, the style is already there I just gotta add the prop.   
  
as for the caret prop,  
we can expose the Caret Component (it can be imported but it's not in docs) and leave Details as it is.
Or: I can just add a caret prop and let the user put in values there. 
in my opinion, the first one is less verbose hence it would be better  
  
if someone can confirm the caret prop for me I can add it. let me open a pull request and get the reset prop done either way!
